In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [9]:
import os

for dirname, _, filenames in os.walk("/kaggle/input"):
    print(dirname)
    for filename in filenames:
        print("   ", filename)

/kaggle/input
/kaggle/input/competitions
/kaggle/input/competitions/mitsui-commodity-prediction-challenge
    target_pairs.csv
    train_labels.csv
    train.csv
    test.csv
/kaggle/input/competitions/mitsui-commodity-prediction-challenge/lagged_test_labels
    test_labels_lag_1.csv
    test_labels_lag_4.csv
    test_labels_lag_3.csv
    test_labels_lag_2.csv
/kaggle/input/competitions/mitsui-commodity-prediction-challenge/kaggle_evaluation
    mitsui_inference_server.py
    mitsui_gateway.py
    __init__.py
/kaggle/input/competitions/mitsui-commodity-prediction-challenge/kaggle_evaluation/core
    templates.py
    base_gateway.py
    relay.py
    kaggle_evaluation.proto
    __init__.py
/kaggle/input/competitions/mitsui-commodity-prediction-challenge/kaggle_evaluation/core/generated
    kaggle_evaluation_pb2.py
    kaggle_evaluation_pb2_grpc.py
    __init__.py
/kaggle/input/datasets
/kaggle/input/datasets/stephenweiler208
/kaggle/input/datasets/stephenweiler208/xg-submission-1
    submission.parquet
/kaggle/input/datasets/stephenweiler208/ground-truth
    test_ground_truth.csv

In [2]:
import pandas as pd

DATA_PATH = "/kaggle/input/competitions/mitsui-commodity-prediction-challenge"

train = pd.read_csv(f"{DATA_PATH}/train.csv")
train_labels = pd.read_csv(f"{DATA_PATH}/train_labels.csv")
test = pd.read_csv(f"{DATA_PATH}/test.csv")
target_pairs = pd.read_csv(f"{DATA_PATH}/target_pairs.csv")

print("train:", train.shape)
print("train_labels:", train_labels.shape)
print("test:", test.shape)
print("target_pairs:", target_pairs.shape)

display(train.head())
display(train_labels.head())
display(test.head())
display(target_pairs.head())

train: (1961, 558)
train_labels: (1961, 425)
test: (134, 559)
target_pairs: (424, 3)

,date_id,LME_AH_Close,LME_CA_Close,LME_PB_Close,LME_ZS_Close,JPX_Gold_Mini_Futures_Open,JPX_Gold_Rolling-Spot_Futures_Open,JPX_Gold_Standard_Futures_Open,JPX_Platinum_Mini_Futures_Open,JPX_Platinum_Standard_Futures_Open,...,FX_GBPCAD,FX_CADCHF,FX_NZDCAD,FX_NZDCHF,FX_ZAREUR,FX_NOKGBP,FX_NOKCHF,FX_ZARCHF,FX_NOKJPY,FX_ZARGBP
0,0,2264.5,7205.0,2570.0,3349.0,NaN,NaN,NaN,NaN,NaN,...,1.699987,0.776874,0.888115,0.689954,0.066653,0.090582,0.119630,0.078135,13.822740,0.059163
1,1,2228.0,7147.0,2579.0,3327.0,NaN,NaN,NaN,NaN,NaN,...,1.695279,0.778682,0.889488,0.692628,0.067354,0.091297,0.120520,0.079066,13.888146,0.059895
2,2,2250.0,7188.5,2587.0,3362.0,4684.0,4691.0,4684.0,3363.0,3367.0,...,1.692724,0.780186,0.894004,0.697490,0.067394,0.091478,0.120809,0.079287,13.983675,0.060037
3,3,2202.5,7121.0,2540.0,3354.0,4728.0,4737.0,4729.0,3430.0,3426.0,...,1.683111,0.785329,0.889439,0.698502,0.067639,0.091558,0.121021,0.079285,14.035571,0.059983
4,4,2175.0,7125.0,2604.0,3386.0,NaN,NaN,NaN,NaN,NaN,...,1.684816,0.787264,0.891042,0.701485,0.067443,0.091266,0.121055,0.078925,14.013760,0.059503

,date_id,target_0,target_1,target_2,target_3,target_4,target_5,target_6,target_7,target_8,...,target_414,target_415,target_416,target_417,target_418,target_419,target_420,target_421,target_422,target_423
0,0,0.005948,-0.002851,-0.004675,-0.000639,NaN,NaN,-0.006729,0.006066,NaN,...,NaN,0.021239,-0.005595,NaN,-0.004628,0.033793,NaN,0.038234,NaN,0.027310
1,1,0.005783,-0.024118,-0.007052,-0.018955,-0.031852,-0.019452,0.003002,-0.006876,-0.002042,...,0.003377,0.021372,-0.001517,0.012846,0.010547,0.030527,-0.000764,0.025021,0.003548,0.020940
2,2,0.001048,0.023836,-0.008934,-0.022060,NaN,NaN,0.037449,0.007658,NaN,...,-0.006712,0.009308,0.001857,-0.012761,-0.002345,0.017529,-0.005394,0.004835,-0.009075,0.001706
3,3,0.001700,-0.024618,0.011943,0.004778,NaN,NaN,-0.012519,-0.016896,NaN,...,NaN,0.036880,-0.015189,NaN,0.008118,0.001079,NaN,-0.015102,NaN,-0.033010
4,4,-0.003272,0.005234,0.006856,0.013312,0.023953,0.010681,-0.011649,0.002019,0.003897,...,NaN,0.004937,NaN,-0.006673,-0.016105,-0.004885,NaN,NaN,0.009514,NaN

,date_id,LME_AH_Close,LME_CA_Close,LME_PB_Close,LME_ZS_Close,JPX_Gold_Mini_Futures_Open,JPX_Gold_Rolling-Spot_Futures_Open,JPX_Gold_Standard_Futures_Open,JPX_Platinum_Mini_Futures_Open,JPX_Platinum_Standard_Futures_Open,...,FX_CADCHF,FX_NZDCAD,FX_NZDCHF,FX_ZAREUR,FX_NOKGBP,FX_NOKCHF,FX_ZARCHF,FX_NOKJPY,FX_ZARGBP,is_scored
0,1827,2684.5,9190.0,1967.0,2942.0,13623.0,13920.0,13618.0,4696.0,4692.0,...,0.631633,0.808485,0.510666,0.051733,0.071654,0.079797,0.048828,13.631347,0.043845,True
1,1828,2691.5,9275.0,1985.0,2963.5,13640.0,13922.0,13634.0,4613.0,4613.0,...,0.633526,0.812571,0.514785,0.051802,0.071793,0.080214,0.048912,13.743387,0.043778,True
2,1829,2646.0,9284.5,1971.0,2914.0,13634.0,13923.0,13638.0,4647.0,4632.0,...,0.632156,0.811948,0.513278,0.051902,0.071630,0.080134,0.048971,13.766241,0.043774,True
3,1830,2634.0,9223.5,1967.0,2900.0,13681.5,13962.0,13680.0,4630.0,4631.0,...,0.629661,0.815155,0.513271,0.051907,0.071972,0.080325,0.048968,13.864629,0.043876,True
4,1831,2623.5,9232.0,1949.0,2846.5,13849.5,14141.0,13844.0,4699.5,4703.0,...,0.630969,0.816284,0.515051,0.051867,0.071790,0.080475,0.049027,13.847691,0.043736,True

     target  lag                                            pair
0  target_0    1                           US_Stock_VT_adj_close
1  target_1    1            LME_PB_Close - US_Stock_VT_adj_close
2  target_2    1                     LME_CA_Close - LME_ZS_Close
3  target_3    1                     LME_AH_Close - LME_ZS_Close
4  target_4    1  LME_AH_Close - JPX_Gold_Standard_Futures_Close

In [3]:
print("train shape:", train.shape)
print("train_labels shape:", train_labels.shape)
print("test shape:", test.shape)
print("target_pairs shape:", target_pairs.shape)

print("\nTrain columns:")
print(train.columns[:20].tolist())

print("\nTrain labels columns:")
print(train_labels.columns[:20].tolist())

print("\nTest columns:")
print(test.columns[:20].tolist())

train shape: (1961, 558)
train_labels shape: (1961, 425)
test shape: (134, 559)
target_pairs shape: (424, 3)

Train columns:
['date_id', 'LME_AH_Close', 'LME_CA_Close', 'LME_PB_Close', 'LME_ZS_Close', 'JPX_Gold_Mini_Futures_Open', 'JPX_Gold_Rolling-Spot_Futures_Open', 'JPX_Gold_Standard_Futures_Open', 'JPX_Platinum_Mini_Futures_Open', 'JPX_Platinum_Standard_Futures_Open', 'JPX_RSS3_Rubber_Futures_Open', 'JPX_Gold_Mini_Futures_High', 'JPX_Gold_Rolling-Spot_Futures_High', 'JPX_Gold_Standard_Futures_High', 'JPX_Platinum_Mini_Futures_High', 'JPX_Platinum_Standard_Futures_High', 'JPX_RSS3_Rubber_Futures_High', 'JPX_Gold_Mini_Futures_Low', 'JPX_Gold_Rolling-Spot_Futures_Low', 'JPX_Gold_Standard_Futures_Low']

Train labels columns:
['date_id', 'target_0', 'target_1', 'target_2', 'target_3', 'target_4', 'target_5', 'target_6', 'target_7', 'target_8', 'target_9', 'target_10', 'target_11', 'target_12', 'target_13', 'target_14', 'target_15', 'target_16', 'target_17', 'target_18']

Test columns:
['date_id', 'LME_AH_Close', 'LME_CA_Close', 'LME_PB_Close', 'LME_ZS_Close', 'JPX_Gold_Mini_Futures_Open', 'JPX_Gold_Rolling-Spot_Futures_Open', 'JPX_Gold_Standard_Futures_Open', 'JPX_Platinum_Mini_Futures_Open', 'JPX_Platinum_Standard_Futures_Open', 'JPX_RSS3_Rubber_Futures_Open', 'JPX_Gold_Mini_Futures_High', 'JPX_Gold_Rolling-Spot_Futures_High', 'JPX_Gold_Standard_Futures_High', 'JPX_Platinum_Mini_Futures_High', 'JPX_Platinum_Standard_Futures_High', 'JPX_RSS3_Rubber_Futures_High', 'JPX_Gold_Mini_Futures_Low', 'JPX_Gold_Rolling-Spot_Futures_Low', 'JPX_Gold_Standard_Futures_Low']

In [4]:
target_cols = [c for c in train_labels.columns if c.startswith("target_")]

print("\nNumber of target columns:", len(target_cols))
print("First 10 targets:", target_cols[:10])

Number of target columns: 424
First 10 targets: ['target_0', 'target_1', 'target_2', 'target_3', 'target_4', 'target_5', 'target_6', 'target_7', 'target_8', 'target_9']

In [5]:
train_full = train.merge(train_labels, on="date_id", how="inner")

print("\nMerged train_full shape:", train_full.shape)
display(train_full.head())

Merged train_full shape: (1961, 982)

,date_id,LME_AH_Close,LME_CA_Close,LME_PB_Close,LME_ZS_Close,JPX_Gold_Mini_Futures_Open,JPX_Gold_Rolling-Spot_Futures_Open,JPX_Gold_Standard_Futures_Open,JPX_Platinum_Mini_Futures_Open,JPX_Platinum_Standard_Futures_Open,...,target_414,target_415,target_416,target_417,target_418,target_419,target_420,target_421,target_422,target_423
0,0,2264.5,7205.0,2570.0,3349.0,NaN,NaN,NaN,NaN,NaN,...,NaN,0.021239,-0.005595,NaN,-0.004628,0.033793,NaN,0.038234,NaN,0.027310
1,1,2228.0,7147.0,2579.0,3327.0,NaN,NaN,NaN,NaN,NaN,...,0.003377,0.021372,-0.001517,0.012846,0.010547,0.030527,-0.000764,0.025021,0.003548,0.020940
2,2,2250.0,7188.5,2587.0,3362.0,4684.0,4691.0,4684.0,3363.0,3367.0,...,-0.006712,0.009308,0.001857,-0.012761,-0.002345,0.017529,-0.005394,0.004835,-0.009075,0.001706
3,3,2202.5,7121.0,2540.0,3354.0,4728.0,4737.0,4729.0,3430.0,3426.0,...,NaN,0.036880,-0.015189,NaN,0.008118,0.001079,NaN,-0.015102,NaN,-0.033010
4,4,2175.0,7125.0,2604.0,3386.0,NaN,NaN,NaN,NaN,NaN,...,NaN,0.004937,NaN,-0.006673,-0.016105,-0.004885,NaN,NaN,0.009514,NaN

In [6]:
id_cols = ["date_id"]
feature_cols = [c for c in train.columns if c not in id_cols]

print("\nNumber of feature columns:", len(feature_cols))
print("First 20 features:", feature_cols[:20])

Number of feature columns: 557
First 20 features: ['LME_AH_Close', 'LME_CA_Close', 'LME_PB_Close', 'LME_ZS_Close', 'JPX_Gold_Mini_Futures_Open', 'JPX_Gold_Rolling-Spot_Futures_Open', 'JPX_Gold_Standard_Futures_Open', 'JPX_Platinum_Mini_Futures_Open', 'JPX_Platinum_Standard_Futures_Open', 'JPX_RSS3_Rubber_Futures_Open', 'JPX_Gold_Mini_Futures_High', 'JPX_Gold_Rolling-Spot_Futures_High', 'JPX_Gold_Standard_Futures_High', 'JPX_Platinum_Mini_Futures_High', 'JPX_Platinum_Standard_Futures_High', 'JPX_RSS3_Rubber_Futures_High', 'JPX_Gold_Mini_Futures_Low', 'JPX_Gold_Rolling-Spot_Futures_Low', 'JPX_Gold_Standard_Futures_Low', 'JPX_Platinum_Mini_Futures_Low']

In [7]:

print("\nMissing values in train features:")
print(train[feature_cols].isna().mean().sort_values(ascending=False).head(10))

print("\nMissing values in train labels:")
print(train_labels[target_cols].isna().mean().sort_values(ascending=False).head(10))

Missing values in train features:
US_Stock_GOLD_adj_open             0.873534
US_Stock_GOLD_adj_close            0.873534
US_Stock_GOLD_adj_volume           0.873534
US_Stock_GOLD_adj_low              0.873534
US_Stock_GOLD_adj_high             0.873534
JPX_Gold_Mini_Futures_Low          0.059153
JPX_Gold_Standard_Futures_Low      0.059153
JPX_Platinum_Mini_Futures_Low      0.059153
JPX_Gold_Standard_Futures_Close    0.059153
JPX_Platinum_Mini_Futures_Close    0.059153
dtype: float64

Missing values in train labels:
target_404    0.188679
target_82     0.183070
target_285    0.178480
target_286    0.178480
target_303    0.178480
target_276    0.178480
target_302    0.178480
target_269    0.178480
target_270    0.178480
target_317    0.178480
dtype: float64

In [8]:
missing_threshold = 0.50

feature_missing_rate = train[feature_cols].isna().mean()

clean_feature_cols = feature_missing_rate[
    feature_missing_rate <= missing_threshold
].index.tolist()

print("Original feature count:", len(feature_cols))
print("Clean feature count:", len(clean_feature_cols))
print("Dropped feature count:", len(feature_cols) - len(clean_feature_cols))

print("\nDropped most-missing features:")
print(feature_missing_rate.sort_values(ascending=False).head(15))

Original feature count: 557
Clean feature count: 552
Dropped feature count: 5

Dropped most-missing features:
US_Stock_GOLD_adj_open                            0.873534
US_Stock_GOLD_adj_close                           0.873534
US_Stock_GOLD_adj_volume                          0.873534
US_Stock_GOLD_adj_low                             0.873534
US_Stock_GOLD_adj_high                            0.873534
JPX_Gold_Mini_Futures_Low                         0.059153
JPX_Gold_Standard_Futures_Low                     0.059153
JPX_Platinum_Mini_Futures_Low                     0.059153
JPX_Gold_Standard_Futures_Close                   0.059153
JPX_Platinum_Mini_Futures_Close                   0.059153
JPX_Platinum_Standard_Futures_Close               0.059153
JPX_RSS3_Rubber_Futures_Close                     0.059153
JPX_Gold_Rolling-Spot_Futures_settlement_price    0.059153
JPX_Platinum_Mini_Futures_settlement_price        0.059153
JPX_RSS3_Rubber_Futures_settlement_price          0.059153
dtype: float64

In [9]:
unique_dates = sorted(train_full["date_id"].unique())

split_idx = int(len(unique_dates) * 0.80)
split_date = unique_dates[split_idx]

print("Split date_id:", split_date)

train_mask = train_full["date_id"] < split_date
valid_mask = train_full["date_id"] >= split_date

X_train = train_full.loc[train_mask, clean_feature_cols]
X_valid = train_full.loc[valid_mask, clean_feature_cols]
X_test = test[clean_feature_cols]

print("X_train shape:", X_train.shape)
print("X_valid shape:", X_valid.shape)
print("X_test shape:", X_test.shape)

Split date_id: 1568
X_train shape: (1568, 552)
X_valid shape: (393, 552)
X_test shape: (134, 552)

In [14]:
import numpy as np
import pandas as pd
import gc

from xgboost import XGBRegressor
from scipy.stats import spearmanr

In [12]:
def safe_spearman(y_true, y_pred):
    mask = ~np.isnan(y_true)

    if mask.sum() < 3:
        return np.nan

    corr = spearmanr(y_true[mask], y_pred[mask]).correlation

    if pd.isna(corr):
        return np.nan

    return corr

In [13]:
targets_to_train = target_cols[:20]

valid_scores = {}
valid_predictions = {}
test_predictions = {}

for i, target in enumerate(targets_to_train):
    print(f"\nTraining {i + 1}/{len(targets_to_train)}: {target}")

    y_train = train_full.loc[train_mask, target].values
    y_valid = train_full.loc[valid_mask, target].values

    train_target_mask = ~np.isnan(y_train)
    valid_target_mask = ~np.isnan(y_valid)

    if train_target_mask.sum() < 100:
        print(f"Skipping {target}: not enough non-missing training labels.")
        valid_scores[target] = np.nan
        test_predictions[target] = np.zeros(len(X_test))
        continue

    model = XGBRegressor(
        n_estimators=300,
        learning_rate=0.03,
        max_depth=4,
        subsample=0.8,
        colsample_bytree=0.8,
        objective="reg:squarederror",
        tree_method="hist",
        device="cuda",
        random_state=42,
        n_jobs=-1,
        eval_metric="rmse"
    )

    model.fit(
        X_train.loc[train_target_mask],
        y_train[train_target_mask],
        eval_set=[
            (
                X_valid.loc[valid_target_mask],
                y_valid[valid_target_mask]
            )
        ],
        verbose=False
    )

    valid_pred = model.predict(X_valid)
    test_pred = model.predict(X_test)

    score = safe_spearman(y_valid, valid_pred)

    valid_scores[target] = score
    valid_predictions[target] = valid_pred
    test_predictions[target] = test_pred

    print(f"{target} validation Spearman: {score:.5f}")

    del model
    gc.collect()

Training 1/20: target_0

/usr/local/lib/python3.12/dist-packages/xgboost/core.py:751: UserWarning: [16:26:39] WARNING: /__w/xgboost/xgboost/src/common/error_msg.cc:62: Falling back to prediction using DMatrix due to mismatched devices. This might lead to higher memory usage and slower performance. XGBoost is running on: cuda:0, while the input data is on: cpu.
Potential solutions:
- Use a data structure that matches the device ordinal in the booster.
- Set the device for booster before call to inplace_predict.

This warning will only be shown once.

  return func(**kwargs)

target_0 validation Spearman: 0.07046

Training 2/20: target_1
target_1 validation Spearman: 0.02032

Training 3/20: target_2
target_2 validation Spearman: 0.06317

Training 4/20: target_3
target_3 validation Spearman: 0.03233

Training 5/20: target_4
target_4 validation Spearman: 0.01271

Training 6/20: target_5
target_5 validation Spearman: -0.06222

Training 7/20: target_6
target_6 validation Spearman: 0.03295

Training 8/20: target_7
target_7 validation Spearman: 0.05914

Training 9/20: target_8
target_8 validation Spearman: 0.01504

Training 10/20: target_9
target_9 validation Spearman: 0.09271

Training 11/20: target_10
target_10 validation Spearman: -0.04609

Training 12/20: target_11
target_11 validation Spearman: 0.14188

Training 13/20: target_12
target_12 validation Spearman: 0.00671

Training 14/20: target_13
target_13 validation Spearman: 0.00146

Training 15/20: target_14
target_14 validation Spearman: 0.00906

Training 16/20: target_15
target_15 validation Spearman: -0.04070

Training 17/20: target_16
target_16 validation Spearman: 0.02928

Training 18/20: target_17
target_17 validation Spearman: 0.07834

Training 19/20: target_18
target_18 validation Spearman: 0.01217

Training 20/20: target_19
target_19 validation Spearman: 0.05712

In [14]:
score_series = pd.Series(valid_scores)

print("\nValidation score summary for first 20 targets:")
display(score_series)

print("\nAverage Spearman:")
print(score_series.mean())

Validation score summary for first 20 targets:

target_0     0.070461
target_1     0.020324
target_2     0.063168
target_3     0.032328
target_4     0.012709
target_5    -0.062219
target_6     0.032949
target_7     0.059141
target_8     0.015043
target_9     0.092708
target_10   -0.046088
target_11    0.141884
target_12    0.006710
target_13    0.001457
target_14    0.009062
target_15   -0.040696
target_16    0.029276
target_17    0.078341
target_18    0.012173
target_19    0.057124
dtype: float64

Average Spearman:
0.029292738301315402

In [19]:
# ============================================================
# 13. Tune XGBoost Configurations on First 20 Targets
# Using Raw Baseline Features Only
# ============================================================

import numpy as np
import pandas as pd
import gc
import time

from xgboost import XGBRegressor
from scipy.stats import spearmanr


def safe_spearman(y_true, y_pred):
    mask = ~np.isnan(y_true)

    if mask.sum() < 3:
        return np.nan

    corr = spearmanr(y_true[mask], y_pred[mask]).correlation

    if pd.isna(corr):
        return np.nan

    return corr


# ------------------------------------------------------------
# Different model setups to test
# ------------------------------------------------------------

xgb_configs = {
    "current_baseline": {
        "n_estimators": 300,
        "learning_rate": 0.03,
        "max_depth": 4,
        "subsample": 0.8,
        "colsample_bytree": 0.8,
        "reg_alpha": 0.0,
        "reg_lambda": 1.0,
        "min_child_weight": 1,
    },

    "more_regularized": {
        "n_estimators": 500,
        "learning_rate": 0.02,
        "max_depth": 3,
        "subsample": 0.8,
        "colsample_bytree": 0.7,
        "reg_alpha": 0.1,
        "reg_lambda": 5.0,
        "min_child_weight": 5,
    },

    "shallower_simple": {
        "n_estimators": 250,
        "learning_rate": 0.04,
        "max_depth": 2,
        "subsample": 0.9,
        "colsample_bytree": 0.9,
        "reg_alpha": 0.0,
        "reg_lambda": 2.0,
        "min_child_weight": 3,
    },

    "deeper_but_regularized": {
        "n_estimators": 400,
        "learning_rate": 0.025,
        "max_depth": 5,
        "subsample": 0.75,
        "colsample_bytree": 0.75,
        "reg_alpha": 0.2,
        "reg_lambda": 8.0,
        "min_child_weight": 8,
    },
}


targets_to_train = target_cols[:20]

config_results = {}
config_target_scores = {}

start_time = time.time()

for config_name, params in xgb_configs.items():
    print("\n" + "=" * 60)
    print(f"Testing config: {config_name}")
    print("=" * 60)

    valid_scores_config = {}

    for i, target in enumerate(targets_to_train):
        print(f"Training {i + 1}/{len(targets_to_train)}: {target}")

        y_train = train_full.loc[train_mask, target].values
        y_valid = train_full.loc[valid_mask, target].values

        train_target_mask = ~np.isnan(y_train)
        valid_target_mask = ~np.isnan(y_valid)

        if train_target_mask.sum() < 100:
            valid_scores_config[target] = np.nan
            continue

        model = XGBRegressor(
            **params,
            objective="reg:squarederror",
            tree_method="hist",
            device="cuda",   # remove this line if GPU causes problems
            random_state=42,
            n_jobs=-1,
            eval_metric="rmse"
        )

        model.fit(
            X_train.loc[train_target_mask],
            y_train[train_target_mask],
            eval_set=[
                (
                    X_valid.loc[valid_target_mask],
                    y_valid[valid_target_mask]
                )
            ],
            verbose=False
        )

        valid_pred = model.predict(X_valid)
        score = safe_spearman(y_valid, valid_pred)

        valid_scores_config[target] = score

        print(f"{target}: {score:.5f}")

        del model
        gc.collect()

    score_series_config = pd.Series(valid_scores_config)

    config_target_scores[config_name] = score_series_config
    config_results[config_name] = score_series_config.mean()

    print(f"\nAverage Spearman for {config_name}: {score_series_config.mean():.5f}")


# ------------------------------------------------------------
# Compare configs
# ------------------------------------------------------------

config_results_series = pd.Series(config_results).sort_values(ascending=False)

print("\n" + "=" * 60)
print("Config comparison")
print("=" * 60)

display(config_results_series)

best_config_name = config_results_series.index[0]
best_config_params = xgb_configs[best_config_name]

print("\nBest config:")
print(best_config_name)

print("\nBest config parameters:")
print(best_config_params)

print("\nOriginal raw baseline average was:")
print(score_series.mean())

============================================================
Testing config: current_baseline
============================================================
Training 1/20: target_0
target_0: 0.07046
Training 2/20: target_1
target_1: 0.02032
Training 3/20: target_2
target_2: 0.06317
Training 4/20: target_3
target_3: 0.03233
Training 5/20: target_4
target_4: 0.01271
Training 6/20: target_5
target_5: -0.06222
Training 7/20: target_6
target_6: 0.03295
Training 8/20: target_7
target_7: 0.05914
Training 9/20: target_8
target_8: 0.01504
Training 10/20: target_9
target_9: 0.09271
Training 11/20: target_10
target_10: -0.04609
Training 12/20: target_11
target_11: 0.14188
Training 13/20: target_12
target_12: 0.00671
Training 14/20: target_13
target_13: 0.00146
Training 15/20: target_14
target_14: 0.00906
Training 16/20: target_15
target_15: -0.04070
Training 17/20: target_16
target_16: 0.02928
Training 18/20: target_17
target_17: 0.07834
Training 19/20: target_18
target_18: 0.01217
Training 20/20: target_19
target_19: 0.05712

Average Spearman for current_baseline: 0.02929

============================================================
Testing config: more_regularized
============================================================
Training 1/20: target_0
target_0: 0.07248
Training 2/20: target_1
target_1: 0.07304
Training 3/20: target_2
target_2: -0.01355
Training 4/20: target_3
target_3: -0.00321
Training 5/20: target_4
target_4: -0.00637
Training 6/20: target_5
target_5: -0.03027
Training 7/20: target_6
target_6: 0.06687
Training 8/20: target_7
target_7: 0.00729
Training 9/20: target_8
target_8: 0.07670
Training 10/20: target_9
target_9: 0.11108
Training 11/20: target_10
target_10: -0.11632
Training 12/20: target_11
target_11: 0.06081
Training 13/20: target_12
target_12: -0.05654
Training 14/20: target_13
target_13: 0.06159
Training 15/20: target_14
target_14: -0.01710
Training 16/20: target_15
target_15: -0.00687
Training 17/20: target_16
target_16: -0.02320
Training 18/20: target_17
target_17: 0.07080
Training 19/20: target_18
target_18: 0.02850
Training 20/20: target_19
target_19: -0.02409

Average Spearman for more_regularized: 0.01658

============================================================
Testing config: shallower_simple
============================================================
Training 1/20: target_0
target_0: 0.07362
Training 2/20: target_1
target_1: -0.01447
Training 3/20: target_2
target_2: 0.05808
Training 4/20: target_3
target_3: 0.06345
Training 5/20: target_4
target_4: 0.00038
Training 6/20: target_5
target_5: -0.04610
Training 7/20: target_6
target_6: 0.06935
Training 8/20: target_7
target_7: 0.05706
Training 9/20: target_8
target_8: 0.01103
Training 10/20: target_9
target_9: 0.09052
Training 11/20: target_10
target_10: -0.00769
Training 12/20: target_11
target_11: 0.07965
Training 13/20: target_12
target_12: 0.01280
Training 14/20: target_13
target_13: 0.03608
Training 15/20: target_14
target_14: 0.03367
Training 16/20: target_15
target_15: -0.01794
Training 17/20: target_16
target_16: 0.06106
Training 18/20: target_17
target_17: 0.04587
Training 19/20: target_18
target_18: 0.02331
Training 20/20: target_19
target_19: 0.06296

Average Spearman for shallower_simple: 0.03463

============================================================
Testing config: deeper_but_regularized
============================================================
Training 1/20: target_0
target_0: 0.10892
Training 2/20: target_1
target_1: 0.05952
Training 3/20: target_2
target_2: -0.02082
Training 4/20: target_3
target_3: -0.01055
Training 5/20: target_4
target_4: -0.02438
Training 6/20: target_5
target_5: -0.05650
Training 7/20: target_6
target_6: 0.04677
Training 8/20: target_7
target_7: -0.06397
Training 9/20: target_8
target_8: 0.02559
Training 10/20: target_9
target_9: 0.04377
Training 11/20: target_10
target_10: -0.10180
Training 12/20: target_11
target_11: 0.08569
Training 13/20: target_12
target_12: -0.06505
Training 14/20: target_13
target_13: 0.07292
Training 15/20: target_14
target_14: -0.03876
Training 16/20: target_15
target_15: 0.00582
Training 17/20: target_16
target_16: -0.03411
Training 18/20: target_17
target_17: 0.08779
Training 19/20: target_18
target_18: 0.00866
Training 20/20: target_19
target_19: -0.01317

Average Spearman for deeper_but_regularized: 0.00582

============================================================
Config comparison
============================================================

shallower_simple          0.034634
current_baseline          0.029293
more_regularized          0.016582
deeper_but_regularized    0.005817
dtype: float64

Best config:
shallower_simple

Best config parameters:
{'n_estimators': 250, 'learning_rate': 0.04, 'max_depth': 2, 'subsample': 0.9, 'colsample_bytree': 0.9, 'reg_alpha': 0.0, 'reg_lambda': 2.0, 'min_child_weight': 3}

Original raw baseline average was:
0.029292738301315402

In [26]:
# ============================================================
# 15. Train Final Models on Full Training Data
# For Kaggle Inference Server Submission
# ============================================================

import numpy as np
import pandas as pd
import gc
import os
import sys
import time

from xgboost import XGBRegressor


best_config_params = {
    "n_estimators": 200,
    "learning_rate": 0.045,
    "max_depth": 2,
    "subsample": 0.9,
    "colsample_bytree": 0.9,
    "reg_alpha": 0.0,
    "reg_lambda": 2.0,
    "min_child_weight": 3,
}

# Final training features
X_full = train[clean_feature_cols]

final_models = {}

start_time = time.time()

for i, target in enumerate(target_cols):
    print(f"Training final model {i + 1}/{len(target_cols)}: {target}")

    y_full = train_labels[target].values
    target_mask = ~np.isnan(y_full)

    if target_mask.sum() < 100:
        print(f"Skipping {target}: not enough non-missing labels.")
        final_models[target] = None
        continue

    model = XGBRegressor(
        **best_config_params,
        objective="reg:squarederror",
        tree_method="hist",
        device="cuda",   # remove this line if GPU causes problems
        random_state=42,
        n_jobs=-1,
        eval_metric="rmse"
    )

    model.fit(
        X_full.loc[target_mask],
        y_full[target_mask],
        verbose=False
    )

    final_models[target] = model

    if (i + 1) % 25 == 0:
        elapsed = (time.time() - start_time) / 60
        print(f"Finished {i + 1}/{len(target_cols)} models in {elapsed:.2f} minutes")

    gc.collect()

print("Finished training final models.")

Training final model 1/424: target_0
Training final model 2/424: target_1
Training final model 3/424: target_2
Training final model 4/424: target_3
Training final model 5/424: target_4
Training final model 6/424: target_5
Training final model 7/424: target_6
Training final model 8/424: target_7
Training final model 9/424: target_8
Training final model 10/424: target_9
Training final model 11/424: target_10
Training final model 12/424: target_11
Training final model 13/424: target_12
Training final model 14/424: target_13
Training final model 15/424: target_14
Training final model 16/424: target_15
Training final model 17/424: target_16
Training final model 18/424: target_17
Training final model 19/424: target_18
Training final model 20/424: target_19
Training final model 21/424: target_20
Training final model 22/424: target_21
Training final model 23/424: target_22
Training final model 24/424: target_23
Training final model 25/424: target_24
Finished 25/424 models in 0.28 minutes
Training final model 26/424: target_25
Training final model 27/424: target_26
Training final model 28/424: target_27
Training final model 29/424: target_28
Training final model 30/424: target_29
Training final model 31/424: target_30
Training final model 32/424: target_31
Training final model 33/424: target_32
Training final model 34/424: target_33
Training final model 35/424: target_34
Training final model 36/424: target_35
Training final model 37/424: target_36
Training final model 38/424: target_37
Training final model 39/424: target_38
Training final model 40/424: target_39
Training final model 41/424: target_40
Training final model 42/424: target_41
Training final model 43/424: target_42
Training final model 44/424: target_43
Training final model 45/424: target_44
Training final model 46/424: target_45
Training final model 47/424: target_46
Training final model 48/424: target_47
Training final model 49/424: target_48
Training final model 50/424: target_49
Finished 50/424 models in 0.55 minutes
Training final model 51/424: target_50
Training final model 52/424: target_51
Training final model 53/424: target_52
Training final model 54/424: target_53
Training final model 55/424: target_54
Training final model 56/424: target_55
Training final model 57/424: target_56
Training final model 58/424: target_57
Training final model 59/424: target_58
Training final model 60/424: target_59
Training final model 61/424: target_60
Training final model 62/424: target_61
Training final model 63/424: target_62
Training final model 64/424: target_63
Training final model 65/424: target_64
Training final model 66/424: target_65
Training final model 67/424: target_66
Training final model 68/424: target_67
Training final model 69/424: target_68
Training final model 70/424: target_69
Training final model 71/424: target_70
Training final model 72/424: target_71
Training final model 73/424: target_72
Training final model 74/424: target_73
Training final model 75/424: target_74
Finished 75/424 models in 0.82 minutes
Training final model 76/424: target_75
Training final model 77/424: target_76
Training final model 78/424: target_77
Training final model 79/424: target_78
Training final model 80/424: target_79
Training final model 81/424: target_80
Training final model 82/424: target_81
Training final model 83/424: target_82
Training final model 84/424: target_83
Training final model 85/424: target_84
Training final model 86/424: target_85
Training final model 87/424: target_86
Training final model 88/424: target_87
Training final model 89/424: target_88
Training final model 90/424: target_89
Training final model 91/424: target_90
Training final model 92/424: target_91
Training final model 93/424: target_92
Training final model 94/424: target_93
Training final model 95/424: target_94
Training final model 96/424: target_95
Training final model 97/424: target_96
Training final model 98/424: target_97
Training final model 99/424: target_98
Training final model 100/424: target_99
Finished 100/424 models in 1.09 minutes
Training final model 101/424: target_100
Training final model 102/424: target_101
Training final model 103/424: target_102
Training final model 104/424: target_103
Training final model 105/424: target_104
Training final model 106/424: target_105
Training final model 107/424: target_106
Training final model 108/424: target_107
Training final model 109/424: target_108
Training final model 110/424: target_109
Training final model 111/424: target_110
Training final model 112/424: target_111
Training final model 113/424: target_112
Training final model 114/424: target_113
Training final model 115/424: target_114
Training final model 116/424: target_115
Training final model 117/424: target_116
Training final model 118/424: target_117
Training final model 119/424: target_118
Training final model 120/424: target_119
Training final model 121/424: target_120
Training final model 122/424: target_121
Training final model 123/424: target_122
Training final model 124/424: target_123
Training final model 125/424: target_124
Finished 125/424 models in 1.35 minutes
Training final model 126/424: target_125
Training final model 127/424: target_126
Training final model 128/424: target_127
Training final model 129/424: target_128
Training final model 130/424: target_129
Training final model 131/424: target_130
Training final model 132/424: target_131
Training final model 133/424: target_132
Training final model 134/424: target_133
Training final model 135/424: target_134
Training final model 136/424: target_135
Training final model 137/424: target_136
Training final model 138/424: target_137
Training final model 139/424: target_138
Training final model 140/424: target_139
Training final model 141/424: target_140
Training final model 142/424: target_141
Training final model 143/424: target_142
Training final model 144/424: target_143
Training final model 145/424: target_144
Training final model 146/424: target_145
Training final model 147/424: target_146
Training final model 148/424: target_147
Training final model 149/424: target_148
Training final model 150/424: target_149
Finished 150/424 models in 1.62 minutes
Training final model 151/424: target_150
Training final model 152/424: target_151
Training final model 153/424: target_152
Training final model 154/424: target_153
Training final model 155/424: target_154
Training final model 156/424: target_155
Training final model 157/424: target_156
Training final model 158/424: target_157
Training final model 159/424: target_158
Training final model 160/424: target_159
Training final model 161/424: target_160
Training final model 162/424: target_161
Training final model 163/424: target_162
Training final model 164/424: target_163
Training final model 165/424: target_164
Training final model 166/424: target_165
Training final model 167/424: target_166
Training final model 168/424: target_167
Training final model 169/424: target_168
Training final model 170/424: target_169
Training final model 171/424: target_170
Training final model 172/424: target_171
Training final model 173/424: target_172
Training final model 174/424: target_173
Training final model 175/424: target_174
Finished 175/424 models in 1.89 minutes
Training final model 176/424: target_175
Training final model 177/424: target_176
Training final model 178/424: target_177
Training final model 179/424: target_178
Training final model 180/424: target_179
Training final model 181/424: target_180
Training final model 182/424: target_181
Training final model 183/424: target_182
Training final model 184/424: target_183
Training final model 185/424: target_184
Training final model 186/424: target_185
Training final model 187/424: target_186
Training final model 188/424: target_187
Training final model 189/424: target_188
Training final model 190/424: target_189
Training final model 191/424: target_190
Training final model 192/424: target_191
Training final model 193/424: target_192
Training final model 194/424: target_193
Training final model 195/424: target_194
Training final model 196/424: target_195
Training final model 197/424: target_196
Training final model 198/424: target_197
Training final model 199/424: target_198
Training final model 200/424: target_199
Finished 200/424 models in 2.16 minutes
Training final model 201/424: target_200
Training final model 202/424: target_201
Training final model 203/424: target_202
Training final model 204/424: target_203
Training final model 205/424: target_204
Training final model 206/424: target_205
Training final model 207/424: target_206
Training final model 208/424: target_207
Training final model 209/424: target_208
Training final model 210/424: target_209
Training final model 211/424: target_210
Training final model 212/424: target_211
Training final model 213/424: target_212
Training final model 214/424: target_213
Training final model 215/424: target_214
Training final model 216/424: target_215
Training final model 217/424: target_216
Training final model 218/424: target_217
Training final model 219/424: target_218
Training final model 220/424: target_219
Training final model 221/424: target_220
Training final model 222/424: target_221
Training final model 223/424: target_222
Training final model 224/424: target_223
Training final model 225/424: target_224
Finished 225/424 models in 2.43 minutes
Training final model 226/424: target_225
Training final model 227/424: target_226
Training final model 228/424: target_227
Training final model 229/424: target_228
Training final model 230/424: target_229
Training final model 231/424: target_230
Training final model 232/424: target_231
Training final model 233/424: target_232
Training final model 234/424: target_233
Training final model 235/424: target_234
Training final model 236/424: target_235
Training final model 237/424: target_236
Training final model 238/424: target_237
Training final model 239/424: target_238
Training final model 240/424: target_239
Training final model 241/424: target_240
Training final model 242/424: target_241
Training final model 243/424: target_242
Training final model 244/424: target_243
Training final model 245/424: target_244
Training final model 246/424: target_245
Training final model 247/424: target_246
Training final model 248/424: target_247
Training final model 249/424: target_248
Training final model 250/424: target_249
Finished 250/424 models in 2.69 minutes
Training final model 251/424: target_250
Training final model 252/424: target_251
Training final model 253/424: target_252
Training final model 254/424: target_253
Training final model 255/424: target_254
Training final model 256/424: target_255
Training final model 257/424: target_256
Training final model 258/424: target_257
Training final model 259/424: target_258
Training final model 260/424: target_259
Training final model 261/424: target_260
Training final model 262/424: target_261
Training final model 263/424: target_262
Training final model 264/424: target_263
Training final model 265/424: target_264
Training final model 266/424: target_265
Training final model 267/424: target_266
Training final model 268/424: target_267
Training final model 269/424: target_268
Training final model 270/424: target_269
Training final model 271/424: target_270
Training final model 272/424: target_271
Training final model 273/424: target_272
Training final model 274/424: target_273
Training final model 275/424: target_274
Finished 275/424 models in 2.96 minutes
Training final model 276/424: target_275
Training final model 277/424: target_276
Training final model 278/424: target_277
Training final model 279/424: target_278
Training final model 280/424: target_279
Training final model 281/424: target_280
Training final model 282/424: target_281
Training final model 283/424: target_282
Training final model 284/424: target_283
Training final model 285/424: target_284
Training final model 286/424: target_285
Training final model 287/424: target_286
Training final model 288/424: target_287
Training final model 289/424: target_288
Training final model 290/424: target_289
Training final model 291/424: target_290
Training final model 292/424: target_291
Training final model 293/424: target_292
Training final model 294/424: target_293
Training final model 295/424: target_294
Training final model 296/424: target_295
Training final model 297/424: target_296
Training final model 298/424: target_297
Training final model 299/424: target_298
Training final model 300/424: target_299
Finished 300/424 models in 3.22 minutes
Training final model 301/424: target_300
Training final model 302/424: target_301
Training final model 303/424: target_302
Training final model 304/424: target_303
Training final model 305/424: target_304
Training final model 306/424: target_305
Training final model 307/424: target_306
Training final model 308/424: target_307
Training final model 309/424: target_308
Training final model 310/424: target_309
Training final model 311/424: target_310
Training final model 312/424: target_311
Training final model 313/424: target_312
Training final model 314/424: target_313
Training final model 315/424: target_314
Training final model 316/424: target_315
Training final model 317/424: target_316
Training final model 318/424: target_317
Training final model 319/424: target_318
Training final model 320/424: target_319
Training final model 321/424: target_320
Training final model 322/424: target_321
Training final model 323/424: target_322
Training final model 324/424: target_323
Training final model 325/424: target_324
Finished 325/424 models in 3.49 minutes
Training final model 326/424: target_325
Training final model 327/424: target_326
Training final model 328/424: target_327
Training final model 329/424: target_328
Training final model 330/424: target_329
Training final model 331/424: target_330
Training final model 332/424: target_331
Training final model 333/424: target_332
Training final model 334/424: target_333
Training final model 335/424: target_334
Training final model 336/424: target_335
Training final model 337/424: target_336
Training final model 338/424: target_337
Training final model 339/424: target_338
Training final model 340/424: target_339
Training final model 341/424: target_340
Training final model 342/424: target_341
Training final model 343/424: target_342
Training final model 344/424: target_343
Training final model 345/424: target_344
Training final model 346/424: target_345
Training final model 347/424: target_346
Training final model 348/424: target_347
Training final model 349/424: target_348
Training final model 350/424: target_349
Finished 350/424 models in 3.75 minutes
Training final model 351/424: target_350
Training final model 352/424: target_351
Training final model 353/424: target_352
Training final model 354/424: target_353
Training final model 355/424: target_354
Training final model 356/424: target_355
Training final model 357/424: target_356
Training final model 358/424: target_357
Training final model 359/424: target_358
Training final model 360/424: target_359
Training final model 361/424: target_360
Training final model 362/424: target_361
Training final model 363/424: target_362
Training final model 364/424: target_363
Training final model 365/424: target_364
Training final model 366/424: target_365
Training final model 367/424: target_366
Training final model 368/424: target_367
Training final model 369/424: target_368
Training final model 370/424: target_369
Training final model 371/424: target_370
Training final model 372/424: target_371
Training final model 373/424: target_372
Training final model 374/424: target_373
Training final model 375/424: target_374
Finished 375/424 models in 4.02 minutes
Training final model 376/424: target_375
Training final model 377/424: target_376
Training final model 378/424: target_377
Training final model 379/424: target_378
Training final model 380/424: target_379
Training final model 381/424: target_380
Training final model 382/424: target_381
Training final model 383/424: target_382
Training final model 384/424: target_383
Training final model 385/424: target_384
Training final model 386/424: target_385
Training final model 387/424: target_386
Training final model 388/424: target_387
Training final model 389/424: target_388
Training final model 390/424: target_389
Training final model 391/424: target_390
Training final model 392/424: target_391
Training final model 393/424: target_392
Training final model 394/424: target_393
Training final model 395/424: target_394
Training final model 396/424: target_395
Training final model 397/424: target_396
Training final model 398/424: target_397
Training final model 399/424: target_398
Training final model 400/424: target_399
Finished 400/424 models in 4.28 minutes
Training final model 401/424: target_400
Training final model 402/424: target_401
Training final model 403/424: target_402
Training final model 404/424: target_403
Training final model 405/424: target_404
Training final model 406/424: target_405
Training final model 407/424: target_406
Training final model 408/424: target_407
Training final model 409/424: target_408
Training final model 410/424: target_409
Training final model 411/424: target_410
Training final model 412/424: target_411
Training final model 413/424: target_412
Training final model 414/424: target_413
Training final model 415/424: target_414
Training final model 416/424: target_415
Training final model 417/424: target_416
Training final model 418/424: target_417
Training final model 419/424: target_418
Training final model 420/424: target_419
Training final model 421/424: target_420
Training final model 422/424: target_421
Training final model 423/424: target_422
Training final model 424/424: target_423
Finished training final models.

In [27]:
# ============================================================
# 16. Kaggle Inference Server Submission Cell
# ============================================================

import os
import sys
import pandas as pd
import polars as pl

# Add competition evaluation package path
sys.path.append("/kaggle/input/competitions/mitsui-commodity-prediction-challenge/kaggle_evaluation")

import kaggle_evaluation.mitsui_inference_server


def predict(test, label_lags_1, label_lags_2, label_lags_3, label_lags_4):
    test_pd = test.to_pandas()

    current_date = int(test_pd["date_id"].iloc[0])
    print(f"Predicting date_id {current_date}")

    if "is_scored" in test_pd.columns:
        test_pd = test_pd.drop(columns=["is_scored"])

    for col in clean_feature_cols:
        if col not in test_pd.columns:
            test_pd[col] = np.nan

    X_batch = test_pd[clean_feature_cols]

    preds = {}

    for target in target_cols:
        model = final_models.get(target)

        if model is None:
            preds[target] = 0.0
        else:
            preds[target] = float(model.predict(X_batch)[0])

    prediction = pd.DataFrame([preds])
    prediction = prediction[target_cols]

    return prediction


inference_server = kaggle_evaluation.mitsui_inference_server.MitsuiInferenceServer(predict)

if os.getenv("KAGGLE_IS_COMPETITION_RERUN"):
    inference_server.serve()
else:
    inference_server.run_local_gateway(
        ("/kaggle/input/competitions/mitsui-commodity-prediction-challenge/",)
    )

Predicting date_id 1827
Predicting date_id 1828
Predicting date_id 1829
Predicting date_id 1830
Predicting date_id 1831
Predicting date_id 1832
Predicting date_id 1833
Predicting date_id 1834
Predicting date_id 1835
Predicting date_id 1836
Predicting date_id 1837
Predicting date_id 1838
Predicting date_id 1839
Predicting date_id 1840
Predicting date_id 1841
Predicting date_id 1842
Predicting date_id 1843
Predicting date_id 1844
Predicting date_id 1845
Predicting date_id 1846
Predicting date_id 1847
Predicting date_id 1848
Predicting date_id 1849
Predicting date_id 1850
Predicting date_id 1851
Predicting date_id 1852
Predicting date_id 1853
Predicting date_id 1854
Predicting date_id 1855
Predicting date_id 1856
Predicting date_id 1857
Predicting date_id 1858
Predicting date_id 1859
Predicting date_id 1860
Predicting date_id 1861
Predicting date_id 1862
Predicting date_id 1863
Predicting date_id 1864
Predicting date_id 1865
Predicting date_id 1866
Predicting date_id 1867
Predicting date_id 1868
Predicting date_id 1869
Predicting date_id 1870
Predicting date_id 1871
Predicting date_id 1872
Predicting date_id 1873
Predicting date_id 1874
Predicting date_id 1875
Predicting date_id 1876
Predicting date_id 1877
Predicting date_id 1878
Predicting date_id 1879
Predicting date_id 1880
Predicting date_id 1881
Predicting date_id 1882
Predicting date_id 1883
Predicting date_id 1884
Predicting date_id 1885
Predicting date_id 1886
Predicting date_id 1887
Predicting date_id 1888
Predicting date_id 1889
Predicting date_id 1890
Predicting date_id 1891
Predicting date_id 1892
Predicting date_id 1893
Predicting date_id 1894
Predicting date_id 1895
Predicting date_id 1896
Predicting date_id 1897
Predicting date_id 1898
Predicting date_id 1899
Predicting date_id 1900
Predicting date_id 1901
Predicting date_id 1902
Predicting date_id 1903
Predicting date_id 1904
Predicting date_id 1905
Predicting date_id 1906
Predicting date_id 1907
Predicting date_id 1908
Predicting date_id 1909
Predicting date_id 1910
Predicting date_id 1911
Predicting date_id 1912
Predicting date_id 1913
Predicting date_id 1914
Predicting date_id 1915
Predicting date_id 1916
Predicting date_id 1917
Predicting date_id 1918
Predicting date_id 1919
Predicting date_id 1920
Predicting date_id 1921
Predicting date_id 1922
Predicting date_id 1923
Predicting date_id 1924
Predicting date_id 1925
Predicting date_id 1926
Predicting date_id 1927
Predicting date_id 1928
Predicting date_id 1929
Predicting date_id 1930
Predicting date_id 1931
Predicting date_id 1932
Predicting date_id 1933
Predicting date_id 1934
Predicting date_id 1935
Predicting date_id 1936
Predicting date_id 1937
Predicting date_id 1938
Predicting date_id 1939
Predicting date_id 1940
Predicting date_id 1941
Predicting date_id 1942
Predicting date_id 1943
Predicting date_id 1944
Predicting date_id 1945
Predicting date_id 1946
Predicting date_id 1947
Predicting date_id 1948
Predicting date_id 1949
Predicting date_id 1950
Predicting date_id 1951
Predicting date_id 1952
Predicting date_id 1953
Predicting date_id 1954
Predicting date_id 1955
Predicting date_id 1956
Predicting date_id 1957
Predicting date_id 1958
Predicting date_id 1959
Predicting date_id 1960

In [28]:
print("Number of final models:", len(final_models))
print("Number of target columns:", len(target_cols))
print("Any missing models:", sum(model is None for model in final_models.values()))

Number of final models: 424
Number of target columns: 424
Any missing models: 0

In [21]:
import os

print(os.listdir("/kaggle/working"))

['.virtual_documents']

In [3]:
# ============================================================
# Score existing submission.parquet against uploaded ground truth
# ============================================================

import os
import numpy as np
import pandas as pd

SOLUTION_NULL_FILLER = -999999

# ------------------------------------------------------------
# 1. Paths
# ------------------------------------------------------------

submission_path = "/kaggle/input/datasets/stephenweiler208/xg-submission-1"
ground_truth_path = "/kaggle/input/datasets/stephenweiler208/ground-truth"
competition_data_path = "/kaggle/input/competitions/mitsui-commodity-prediction-challenge"

# If the ground truth path is a folder, find the CSV inside it
if os.path.isdir(ground_truth_path):
    files = os.listdir(ground_truth_path)
    print("Files in ground truth folder:", files)

    csv_files = [f for f in files if f.endswith(".csv")]

    if len(csv_files) == 0:
        raise FileNotFoundError("No CSV file found inside the ground truth folder.")

    ground_truth_path = os.path.join(ground_truth_path, csv_files[0])

print("Using ground truth file:", ground_truth_path)


# ------------------------------------------------------------
# 2. Load submission and ground truth
# ------------------------------------------------------------

submission = pd.read_parquet(submission_path)
solution = pd.read_csv(ground_truth_path)

print("Original submission shape:", submission.shape)
print("Original solution shape:", solution.shape)

display(submission.head())
display(solution.head())


# ------------------------------------------------------------
# 3. Add date_id to submission if needed
# ------------------------------------------------------------

if "date_id" not in submission.columns:
    test = pd.read_csv(f"{competition_data_path}/test.csv")
    test_date_ids = test["date_id"].drop_duplicates().reset_index(drop=True)

    submission = submission.copy()
    submission.insert(0, "date_id", test_date_ids.iloc[:len(submission)].values)

print("Submission columns after date_id check:", submission.columns[:10].tolist())
print("Solution columns:", solution.columns[:10].tolist())


# ------------------------------------------------------------
# 4. Metric functions
# ------------------------------------------------------------

def rank_correlation_sharpe_ratio(merged_df: pd.DataFrame) -> float:
    """
    Calculates daily rank correlation between predictions and target values,
    then returns mean daily rank correlation divided by its standard deviation.
    """

    prediction_cols = [col for col in merged_df.columns if col.startswith("prediction_")]
    target_cols = [col for col in merged_df.columns if col.startswith("target_")]

    def _compute_rank_correlation(row):
        non_null_targets = [col for col in target_cols if not pd.isnull(row[col])]

        matching_predictions = [
            col for col in prediction_cols
            if col.replace("prediction", "target") in non_null_targets
        ]

        if not non_null_targets:
            raise ValueError("No non-null target values found.")

        if row[non_null_targets].std(ddof=0) == 0 or row[matching_predictions].std(ddof=0) == 0:
            raise ZeroDivisionError("Denominator is zero, unable to compute rank correlation.")

        return np.corrcoef(
            row[matching_predictions].rank(method="average"),
            row[non_null_targets].rank(method="average")
        )[0, 1]

    daily_rank_corrs = merged_df.apply(_compute_rank_correlation, axis=1)

    std_dev = daily_rank_corrs.std(ddof=0)

    if std_dev == 0:
        raise ZeroDivisionError("Denominator is zero, unable to compute Sharpe ratio.")

    sharpe_ratio = daily_rank_corrs.mean() / std_dev

    return float(sharpe_ratio)


def score(solution: pd.DataFrame, submission: pd.DataFrame, row_id_column_name: str) -> float:
    """
    Competition-style score:
    daily Spearman/rank correlation Sharpe ratio.
    """

    solution = solution.copy()
    submission = submission.copy()

    del solution[row_id_column_name]
    del submission[row_id_column_name]

    assert all(solution.columns == submission.columns), "Solution and submission columns do not match."

    submission = submission.rename(
        columns={col: col.replace("target_", "prediction_") for col in submission.columns}
    )

    solution = solution.replace(SOLUTION_NULL_FILLER, None)

    merged_df = pd.concat([solution, submission], axis="columns")

    return rank_correlation_sharpe_ratio(merged_df)


# ------------------------------------------------------------
# 5. Clean and align columns
# ------------------------------------------------------------

# Keep only target columns from the ground truth
target_cols = [c for c in solution.columns if c.startswith("target_")]

if len(target_cols) == 0:
    raise ValueError("No target_ columns found in the ground truth file.")

# Make sure submission has all required target columns
missing_targets = [c for c in target_cols if c not in submission.columns]

if missing_targets:
    raise ValueError(f"Submission is missing these target columns: {missing_targets[:10]}")

# Align rows by date_id
solution = solution[["date_id"] + target_cols].copy()
submission = submission[["date_id"] + target_cols].copy()

solution = solution.sort_values("date_id").reset_index(drop=True)
submission = submission.sort_values("date_id").reset_index(drop=True)

print("Final aligned solution shape:", solution.shape)
print("Final aligned submission shape:", submission.shape)
print("Columns match:", list(solution.columns) == list(submission.columns))

display(solution.head())
display(submission.head())


# ------------------------------------------------------------
# 6. Calculate local score
# ------------------------------------------------------------

local_score = score(
    solution=solution,
    submission=submission,
    row_id_column_name="date_id"
)

print("Local competition-style Sharpe score:")
print(local_score)

Files in ground truth folder: ['test_ground_truth.csv']
Using ground truth file: /kaggle/input/datasets/stephenweiler208/ground-truth/test_ground_truth.csv
Original submission shape: (134, 425)
Original solution shape: (134, 425)

,date_id,target_0,target_1,target_2,target_3,target_4,target_5,target_6,target_7,target_8,...,target_414,target_415,target_416,target_417,target_418,target_419,target_420,target_421,target_422,target_423
0,1827,0.001218,-0.001013,0.001264,0.000467,-0.004418,0.002450,0.000050,-0.001593,0.000028,...,-0.001959,0.001792,-0.008498,-0.011986,0.008698,0.001014,0.005903,-0.000787,-0.009076,0.015054
1,1828,0.000163,-0.001374,0.000133,0.001883,0.001802,0.000558,-0.003093,-0.001060,-0.000469,...,0.003092,0.006736,-0.001855,-0.000428,0.003292,0.003427,-0.006944,0.002664,0.000065,0.000606
2,1829,-0.000169,-0.000755,0.000195,-0.000733,0.000471,0.001316,-0.002088,-0.001473,0.000364,...,0.000425,0.000380,-0.009257,-0.004668,0.002657,0.000097,0.001014,-0.002219,-0.003601,0.004971
3,1830,0.000247,-0.001106,0.002328,0.001984,-0.000157,-0.003161,-0.001540,-0.000799,0.000186,...,0.002367,0.000090,-0.009616,-0.002587,0.004008,-0.000197,0.002520,-0.001617,0.002578,0.029882
4,1831,-0.000258,-0.000302,-0.001286,-0.002469,-0.001241,-0.000028,0.000265,0.000855,-0.000610,...,-0.000808,-0.001364,-0.009257,-0.004674,0.002345,0.000166,-0.001116,-0.001138,-0.002984,0.016641

,date_id,target_0,target_1,target_2,target_3,target_4,target_5,target_6,target_7,target_8,...,target_414,target_415,target_416,target_417,target_418,target_419,target_420,target_421,target_422,target_423
0,1827,NaN,NaN,0.017868,-0.000205,-0.016391,-0.013827,0.009972,NaN,NaN,...,NaN,0.019701,NaN,-0.027030,0.043602,0.027982,NaN,NaN,0.002177,NaN
1,1828,0.002560,-0.004592,-0.001776,0.000271,-0.016696,-0.020025,0.002514,0.002204,-0.011962,...,0.012063,0.012081,-0.020068,0.002858,0.019154,0.019018,0.003875,-0.035202,0.011246,0.099241
2,1829,0.005346,-0.014539,0.019542,0.014626,-0.011631,-0.009223,-0.005199,-0.026092,-0.003865,...,-0.009004,0.016166,-0.028919,-0.007297,0.033262,0.023174,-0.028512,-0.017900,-0.002096,0.121451
3,1830,0.000082,-0.005226,0.011452,0.013346,0.008228,-0.014819,-0.011792,-0.007148,0.005712,...,-0.013857,-0.007742,-0.018436,0.004691,0.013311,0.000589,-0.014500,-0.046444,0.009058,0.109246
4,1831,-0.011469,0.016613,-0.023765,-0.018744,-0.011878,0.007257,0.019829,0.006618,-0.015351,...,-0.015625,-0.018850,-0.025373,0.031197,0.005873,-0.005650,-0.022926,-0.027990,0.011267,0.091318

Submission columns after date_id check: ['date_id', 'target_0', 'target_1', 'target_2', 'target_3', 'target_4', 'target_5', 'target_6', 'target_7', 'target_8']
Solution columns: ['date_id', 'target_0', 'target_1', 'target_2', 'target_3', 'target_4', 'target_5', 'target_6', 'target_7', 'target_8']
Final aligned solution shape: (134, 425)
Final aligned submission shape: (134, 425)
Columns match: True

,date_id,target_0,target_1,target_2,target_3,target_4,target_5,target_6,target_7,target_8,...,target_414,target_415,target_416,target_417,target_418,target_419,target_420,target_421,target_422,target_423
0,1827,NaN,NaN,0.017868,-0.000205,-0.016391,-0.013827,0.009972,NaN,NaN,...,NaN,0.019701,NaN,-0.027030,0.043602,0.027982,NaN,NaN,0.002177,NaN
1,1828,0.002560,-0.004592,-0.001776,0.000271,-0.016696,-0.020025,0.002514,0.002204,-0.011962,...,0.012063,0.012081,-0.020068,0.002858,0.019154,0.019018,0.003875,-0.035202,0.011246,0.099241
2,1829,0.005346,-0.014539,0.019542,0.014626,-0.011631,-0.009223,-0.005199,-0.026092,-0.003865,...,-0.009004,0.016166,-0.028919,-0.007297,0.033262,0.023174,-0.028512,-0.017900,-0.002096,0.121451
3,1830,0.000082,-0.005226,0.011452,0.013346,0.008228,-0.014819,-0.011792,-0.007148,0.005712,...,-0.013857,-0.007742,-0.018436,0.004691,0.013311,0.000589,-0.014500,-0.046444,0.009058,0.109246
4,1831,-0.011469,0.016613,-0.023765,-0.018744,-0.011878,0.007257,0.019829,0.006618,-0.015351,...,-0.015625,-0.018850,-0.025373,0.031197,0.005873,-0.005650,-0.022926,-0.027990,0.011267,0.091318

,date_id,target_0,target_1,target_2,target_3,target_4,target_5,target_6,target_7,target_8,...,target_414,target_415,target_416,target_417,target_418,target_419,target_420,target_421,target_422,target_423
0,1827,0.001218,-0.001013,0.001264,0.000467,-0.004418,0.002450,0.000050,-0.001593,0.000028,...,-0.001959,0.001792,-0.008498,-0.011986,0.008698,0.001014,0.005903,-0.000787,-0.009076,0.015054
1,1828,0.000163,-0.001374,0.000133,0.001883,0.001802,0.000558,-0.003093,-0.001060,-0.000469,...,0.003092,0.006736,-0.001855,-0.000428,0.003292,0.003427,-0.006944,0.002664,0.000065,0.000606
2,1829,-0.000169,-0.000755,0.000195,-0.000733,0.000471,0.001316,-0.002088,-0.001473,0.000364,...,0.000425,0.000380,-0.009257,-0.004668,0.002657,0.000097,0.001014,-0.002219,-0.003601,0.004971
3,1830,0.000247,-0.001106,0.002328,0.001984,-0.000157,-0.003161,-0.001540,-0.000799,0.000186,...,0.002367,0.000090,-0.009616,-0.002587,0.004008,-0.000197,0.002520,-0.001617,0.002578,0.029882
4,1831,-0.000258,-0.000302,-0.001286,-0.002469,-0.001241,-0.000028,0.000265,0.000855,-0.000610,...,-0.000808,-0.001364,-0.009257,-0.004674,0.002345,0.000166,-0.001116,-0.001138,-0.002984,0.016641

Local competition-style Sharpe score:
2.8108107161090703

In [6]:
# ============================================================
# Corrected local scoring using label_date_id alignment
# ============================================================

import os
import numpy as np
import pandas as pd

SOLUTION_NULL_FILLER = -999999

submission_path = "/kaggle/input/datasets/stephenweiler208/xg-submission-1"
ground_truth_path = "/kaggle/input/datasets/stephenweiler208/ground-truth"
competition_data_path = "/kaggle/input/competitions/mitsui-commodity-prediction-challenge"

# ------------------------------------------------------------
# Load submission
# ------------------------------------------------------------

submission = pd.read_parquet(submission_path)

test = pd.read_csv(f"{competition_data_path}/test.csv")
test_date_ids = test["date_id"].drop_duplicates().reset_index(drop=True)

if "date_id" not in submission.columns:
    submission = submission.copy()
    submission.insert(0, "date_id", test_date_ids.iloc[:len(submission)].values)

# ------------------------------------------------------------
# Load target metadata
# ------------------------------------------------------------

target_pairs = pd.read_csv(f"{competition_data_path}/target_pairs.csv")
target_cols = target_pairs["target"].tolist()

# ------------------------------------------------------------
# Rebuild solution using label_date_id, not date_id
# ------------------------------------------------------------

solution_parts = []

for lag in [1, 2, 3, 4]:
    lag_df = pd.read_csv(
        f"{competition_data_path}/lagged_test_labels/test_labels_lag_{lag}.csv"
    )

    lag_targets = target_pairs.loc[target_pairs["lag"] == lag, "target"].tolist()
    available_targets = [c for c in lag_targets if c in lag_df.columns]

    temp = lag_df[["label_date_id"] + available_targets].copy()
    temp = temp.rename(columns={"label_date_id": "date_id"})

    solution_parts.append(temp)

# Merge the different lag-specific truth pieces by the actual label date
solution = solution_parts[0]

for part in solution_parts[1:]:
    solution = solution.merge(part, on="date_id", how="outer")

# Only score dates that appear in your submission
solution = solution[solution["date_id"].isin(submission["date_id"])].copy()

# ------------------------------------------------------------
# Align rows and columns
# ------------------------------------------------------------

submission = submission[["date_id"] + target_cols].copy()
solution = solution[["date_id"] + target_cols].copy()

merged_dates = sorted(set(submission["date_id"]) & set(solution["date_id"]))

submission = submission[submission["date_id"].isin(merged_dates)].sort_values("date_id").reset_index(drop=True)
solution = solution[solution["date_id"].isin(merged_dates)].sort_values("date_id").reset_index(drop=True)

print("Scored dates:", len(merged_dates))
print("Submission shape:", submission.shape)
print("Solution shape:", solution.shape)

# ------------------------------------------------------------
# Metric
# ------------------------------------------------------------

def rank_correlation_sharpe_ratio(merged_df: pd.DataFrame) -> float:
    prediction_cols = [col for col in merged_df.columns if col.startswith("prediction_")]
    target_cols = [col for col in merged_df.columns if col.startswith("target_")]

    def _compute_rank_correlation(row):
        non_null_targets = [col for col in target_cols if not pd.isnull(row[col])]

        matching_predictions = [
            col for col in prediction_cols
            if col.replace("prediction", "target") in non_null_targets
        ]

        if not non_null_targets:
            return np.nan

        if row[non_null_targets].std(ddof=0) == 0 or row[matching_predictions].std(ddof=0) == 0:
            return np.nan

        return np.corrcoef(
            row[matching_predictions].rank(method="average"),
            row[non_null_targets].rank(method="average")
        )[0, 1]

    daily_rank_corrs = merged_df.apply(_compute_rank_correlation, axis=1).dropna()

    std_dev = daily_rank_corrs.std(ddof=0)

    if std_dev == 0:
        raise ZeroDivisionError("Denominator is zero, unable to compute Sharpe ratio.")

    return float(daily_rank_corrs.mean() / std_dev)


def score(solution: pd.DataFrame, submission: pd.DataFrame, row_id_column_name: str) -> float:
    solution = solution.copy()
    submission = submission.copy()

    del solution[row_id_column_name]
    del submission[row_id_column_name]

    assert all(solution.columns == submission.columns)

    submission = submission.rename(
        columns={col: col.replace("target_", "prediction_") for col in submission.columns}
    )

    solution = solution.replace(SOLUTION_NULL_FILLER, None)

    return rank_correlation_sharpe_ratio(
        pd.concat([solution, submission], axis="columns")
    )

local_score = score(solution, submission, row_id_column_name="date_id")

print("Corrected local competition-style Sharpe score:")
print(local_score)

Scored dates: 134
Submission shape: (134, 425)
Solution shape: (134, 425)
Corrected local competition-style Sharpe score:
2.8108107161090703

In [7]:
# ============================================================
# Diagnostic checks for suspiciously high local score
# ============================================================

import pandas as pd
import numpy as np

submission_path = "/kaggle/input/datasets/stephenweiler208/xg-submission-1"
ground_truth_path = "/kaggle/input/datasets/stephenweiler208/ground-truth"
competition_data_path = "/kaggle/input/competitions/mitsui-commodity-prediction-challenge"

submission = pd.read_parquet(submission_path)

# If ground_truth_path is a folder, find CSV inside
import os
if os.path.isdir(ground_truth_path):
    csv_files = [f for f in os.listdir(ground_truth_path) if f.endswith(".csv")]
    ground_truth_path = os.path.join(ground_truth_path, csv_files[0])

solution = pd.read_csv(ground_truth_path)

print("submission shape:", submission.shape)
print("solution shape:", solution.shape)

print("\nsubmission columns first 10:")
print(submission.columns[:10].tolist())

print("\nsolution columns first 10:")
print(solution.columns[:10].tolist())

display(submission.head())
display(solution.head())


# ------------------------------------------------------------
# 1. Check date_id situation
# ------------------------------------------------------------

test = pd.read_csv(f"{competition_data_path}/test.csv")

if "date_id" not in submission.columns:
    test_date_ids = test["date_id"].drop_duplicates().reset_index(drop=True)
    submission = submission.copy()
    submission.insert(0, "date_id", test_date_ids.iloc[:len(submission)].values)

print("\nsubmission date_id range:", submission["date_id"].min(), submission["date_id"].max())
print("solution date_id range:", solution["date_id"].min(), solution["date_id"].max())
print("matching date_ids:", set(submission["date_id"]) == set(solution["date_id"]))


# ------------------------------------------------------------
# 2. Check if submission accidentally equals / strongly matches solution
# ------------------------------------------------------------

target_cols = [c for c in solution.columns if c.startswith("target_")]

common_dates = sorted(set(submission["date_id"]) & set(solution["date_id"]))

sub_aligned = (
    submission[submission["date_id"].isin(common_dates)]
    .sort_values("date_id")
    .reset_index(drop=True)
)

sol_aligned = (
    solution[solution["date_id"].isin(common_dates)]
    .sort_values("date_id")
    .reset_index(drop=True)
)

sub_values = sub_aligned[target_cols].to_numpy()
sol_values = sol_aligned[target_cols].to_numpy()

# Compare exact equality where both are non-null
mask = ~pd.isna(sol_values) & ~pd.isna(sub_values)

exact_match_rate = np.mean(np.isclose(sub_values[mask], sol_values[mask], equal_nan=False))

print("\nExact/near exact match rate between submission and ground truth:")
print(exact_match_rate)


# ------------------------------------------------------------
# 3. Check daily correlations directly
# ------------------------------------------------------------

daily_corrs = []

for i in range(len(common_dates)):
    y_pred = sub_aligned.loc[i, target_cols]
    y_true = sol_aligned.loc[i, target_cols]

    mask = (~pd.isna(y_pred)) & (~pd.isna(y_true))

    if mask.sum() < 3:
        daily_corrs.append(np.nan)
    else:
        corr = np.corrcoef(
            y_pred[mask].rank(method="average"),
            y_true[mask].rank(method="average")
        )[0, 1]
        daily_corrs.append(corr)

daily_corrs = pd.Series(daily_corrs, index=common_dates).dropna()

print("\nDaily rank correlation summary:")
display(daily_corrs.describe())

print("\nMean daily rank corr:", daily_corrs.mean())
print("Std daily rank corr:", daily_corrs.std(ddof=0))
print("Sharpe:", daily_corrs.mean() / daily_corrs.std(ddof=0))

print("\nTop 10 daily correlations:")
display(daily_corrs.sort_values(ascending=False).head(10))

print("\nBottom 10 daily correlations:")
display(daily_corrs.sort_values(ascending=True).head(10))


# ------------------------------------------------------------
# 4. Check lag file date_id vs label_date_id
# ------------------------------------------------------------

for lag in [1, 2, 3, 4]:
    lag_df = pd.read_csv(f"{competition_data_path}/lagged_test_labels/test_labels_lag_{lag}.csv")
    print(f"\nLag {lag} date columns:")
    display(lag_df[["date_id", "label_date_id"]].head(10))

submission shape: (134, 425)
solution shape: (134, 425)

submission columns first 10:
['date_id', 'target_0', 'target_1', 'target_2', 'target_3', 'target_4', 'target_5', 'target_6', 'target_7', 'target_8']

solution columns first 10:
['date_id', 'target_0', 'target_1', 'target_2', 'target_3', 'target_4', 'target_5', 'target_6', 'target_7', 'target_8']

,date_id,target_0,target_1,target_2,target_3,target_4,target_5,target_6,target_7,target_8,...,target_414,target_415,target_416,target_417,target_418,target_419,target_420,target_421,target_422,target_423
0,1827,0.001218,-0.001013,0.001264,0.000467,-0.004418,0.002450,0.000050,-0.001593,0.000028,...,-0.001959,0.001792,-0.008498,-0.011986,0.008698,0.001014,0.005903,-0.000787,-0.009076,0.015054
1,1828,0.000163,-0.001374,0.000133,0.001883,0.001802,0.000558,-0.003093,-0.001060,-0.000469,...,0.003092,0.006736,-0.001855,-0.000428,0.003292,0.003427,-0.006944,0.002664,0.000065,0.000606
2,1829,-0.000169,-0.000755,0.000195,-0.000733,0.000471,0.001316,-0.002088,-0.001473,0.000364,...,0.000425,0.000380,-0.009257,-0.004668,0.002657,0.000097,0.001014,-0.002219,-0.003601,0.004971
3,1830,0.000247,-0.001106,0.002328,0.001984,-0.000157,-0.003161,-0.001540,-0.000799,0.000186,...,0.002367,0.000090,-0.009616,-0.002587,0.004008,-0.000197,0.002520,-0.001617,0.002578,0.029882
4,1831,-0.000258,-0.000302,-0.001286,-0.002469,-0.001241,-0.000028,0.000265,0.000855,-0.000610,...,-0.000808,-0.001364,-0.009257,-0.004674,0.002345,0.000166,-0.001116,-0.001138,-0.002984,0.016641

,date_id,target_0,target_1,target_2,target_3,target_4,target_5,target_6,target_7,target_8,...,target_414,target_415,target_416,target_417,target_418,target_419,target_420,target_421,target_422,target_423
0,1827,NaN,NaN,0.017868,-0.000205,-0.016391,-0.013827,0.009972,NaN,NaN,...,NaN,0.019701,NaN,-0.027030,0.043602,0.027982,NaN,NaN,0.002177,NaN
1,1828,0.002560,-0.004592,-0.001776,0.000271,-0.016696,-0.020025,0.002514,0.002204,-0.011962,...,0.012063,0.012081,-0.020068,0.002858,0.019154,0.019018,0.003875,-0.035202,0.011246,0.099241
2,1829,0.005346,-0.014539,0.019542,0.014626,-0.011631,-0.009223,-0.005199,-0.026092,-0.003865,...,-0.009004,0.016166,-0.028919,-0.007297,0.033262,0.023174,-0.028512,-0.017900,-0.002096,0.121451
3,1830,0.000082,-0.005226,0.011452,0.013346,0.008228,-0.014819,-0.011792,-0.007148,0.005712,...,-0.013857,-0.007742,-0.018436,0.004691,0.013311,0.000589,-0.014500,-0.046444,0.009058,0.109246
4,1831,-0.011469,0.016613,-0.023765,-0.018744,-0.011878,0.007257,0.019829,0.006618,-0.015351,...,-0.015625,-0.018850,-0.025373,0.031197,0.005873,-0.005650,-0.022926,-0.027990,0.011267,0.091318

submission date_id range: 1827 1960
solution date_id range: 1827 1960
matching date_ids: True

Exact/near exact match rate between submission and ground truth:
0.0

Daily rank correlation summary:

count    134.000000
mean       0.540894
std        0.193155
min       -0.459835
25%        0.441030
50%        0.564604
75%        0.681009
max        0.941363
dtype: float64

Mean daily rank corr: 0.5408937377215429
Std daily rank corr: 0.19243335548054533
Sharpe: 2.8108107161090703

Top 10 daily correlations:

1883    0.941363
1879    0.916474
1884    0.861611
1878    0.832272
1856    0.820445
1932    0.819537
1882    0.814109
1885    0.787456
1881    0.782732
1874    0.781640
dtype: float64

Bottom 10 daily correlations:

1891   -0.459835
1919    0.098566
1939    0.190639
1946    0.192361
1848    0.217839
1841    0.221687
1915    0.227085
1870    0.228487
1845    0.242519
1827    0.265042
dtype: float64

Lag 1 date columns:

   date_id  label_date_id
0     1829           1827
1     1830           1828
2     1831           1829
3     1832           1830
4     1833           1831
5     1834           1832
6     1835           1833
7     1836           1834
8     1837           1835
9     1838           1836

Lag 2 date columns:

   date_id  label_date_id
0     1830           1827
1     1831           1828
2     1832           1829
3     1833           1830
4     1834           1831
5     1835           1832
6     1836           1833
7     1837           1834
8     1838           1835
9     1839           1836

Lag 3 date columns:

   date_id  label_date_id
0     1831           1827
1     1832           1828
2     1833           1829
3     1834           1830
4     1835           1831
5     1836           1832
6     1837           1833
7     1838           1834
8     1839           1835
9     1840           1836

Lag 4 date columns:

   date_id  label_date_id
0     1832           1827
1     1833           1828
2     1834           1829
3     1835           1830
4     1836           1831
5     1837           1832
6     1838           1833
7     1839           1834
8     1840           1835
9     1841           1836

In [20]:
# ============================================================
# 15. Train Final Models on Pre-Test Data Only
# For Non-Leaky Local Ground Truth Evaluation
# ============================================================

import numpy as np
import pandas as pd
import gc
import os
import sys
import time

from xgboost import XGBRegressor


best_config_params = {
    "n_estimators": 200,
    "learning_rate": 0.045,
    "max_depth": 2,
    "subsample": 0.9,
    "colsample_bytree": 0.9,
    "reg_alpha": 0.0,
    "reg_lambda": 2.0,
    "min_child_weight": 3,
}

# Ground truth / local test starts at date_id 1827
local_test_start = 1827

# Train only on dates before the local test period
train_nonleaky_mask = train["date_id"] < local_test_start

X_full = train.loc[train_nonleaky_mask, clean_feature_cols]

final_models = {}

start_time = time.time()

for i, target in enumerate(target_cols):
    print(f"Training final model {i + 1}/{len(target_cols)}: {target}")

    # Use only labels before date_id 1827
    y_full = train_labels.loc[train_nonleaky_mask, target].values
    target_mask = ~np.isnan(y_full)

    if target_mask.sum() < 100:
        print(f"Skipping {target}: not enough non-missing labels.")
        final_models[target] = None
        continue

    model = XGBRegressor(
        **best_config_params,
        objective="reg:squarederror",
        tree_method="hist",
        device="cuda",   # remove this line if GPU causes problems
        random_state=42,
        n_jobs=-1,
        eval_metric="rmse"
    )

    model.fit(
        X_full.loc[target_mask],
        y_full[target_mask],
        verbose=False
    )

    final_models[target] = model

    if (i + 1) % 25 == 0:
        elapsed = (time.time() - start_time) / 60
        print(f"Finished {i + 1}/{len(target_cols)} models in {elapsed:.2f} minutes")

    gc.collect()

print("Finished training non-leaky final models.")
print("Training rows used:", X_full.shape[0])
print("Training date range:", train.loc[train_nonleaky_mask, "date_id"].min(), "to", train.loc[train_nonleaky_mask, "date_id"].max())

Training final model 1/424: target_0
Training final model 2/424: target_1
Training final model 3/424: target_2
Training final model 4/424: target_3
Training final model 5/424: target_4
Training final model 6/424: target_5
Training final model 7/424: target_6
Training final model 8/424: target_7
Training final model 9/424: target_8
Training final model 10/424: target_9
Training final model 11/424: target_10
Training final model 12/424: target_11
Training final model 13/424: target_12
Training final model 14/424: target_13
Training final model 15/424: target_14
Training final model 16/424: target_15
Training final model 17/424: target_16
Training final model 18/424: target_17
Training final model 19/424: target_18
Training final model 20/424: target_19
Training final model 21/424: target_20
Training final model 22/424: target_21
Training final model 23/424: target_22
Training final model 24/424: target_23
Training final model 25/424: target_24
Finished 25/424 models in 0.27 minutes
Training final model 26/424: target_25
Training final model 27/424: target_26
Training final model 28/424: target_27
Training final model 29/424: target_28
Training final model 30/424: target_29
Training final model 31/424: target_30
Training final model 32/424: target_31
Training final model 33/424: target_32
Training final model 34/424: target_33
Training final model 35/424: target_34
Training final model 36/424: target_35
Training final model 37/424: target_36
Training final model 38/424: target_37
Training final model 39/424: target_38
Training final model 40/424: target_39
Training final model 41/424: target_40
Training final model 42/424: target_41
Training final model 43/424: target_42
Training final model 44/424: target_43
Training final model 45/424: target_44
Training final model 46/424: target_45
Training final model 47/424: target_46
Training final model 48/424: target_47
Training final model 49/424: target_48
Training final model 50/424: target_49
Finished 50/424 models in 0.54 minutes
Training final model 51/424: target_50
Training final model 52/424: target_51
Training final model 53/424: target_52
Training final model 54/424: target_53
Training final model 55/424: target_54
Training final model 56/424: target_55
Training final model 57/424: target_56
Training final model 58/424: target_57
Training final model 59/424: target_58
Training final model 60/424: target_59
Training final model 61/424: target_60
Training final model 62/424: target_61
Training final model 63/424: target_62
Training final model 64/424: target_63
Training final model 65/424: target_64
Training final model 66/424: target_65
Training final model 67/424: target_66
Training final model 68/424: target_67
Training final model 69/424: target_68
Training final model 70/424: target_69
Training final model 71/424: target_70
Training final model 72/424: target_71
Training final model 73/424: target_72
Training final model 74/424: target_73
Training final model 75/424: target_74
Finished 75/424 models in 0.79 minutes
Training final model 76/424: target_75
Training final model 77/424: target_76
Training final model 78/424: target_77
Training final model 79/424: target_78
Training final model 80/424: target_79
Training final model 81/424: target_80
Training final model 82/424: target_81
Training final model 83/424: target_82
Training final model 84/424: target_83
Training final model 85/424: target_84
Training final model 86/424: target_85
Training final model 87/424: target_86
Training final model 88/424: target_87
Training final model 89/424: target_88
Training final model 90/424: target_89
Training final model 91/424: target_90
Training final model 92/424: target_91
Training final model 93/424: target_92
Training final model 94/424: target_93
Training final model 95/424: target_94
Training final model 96/424: target_95
Training final model 97/424: target_96
Training final model 98/424: target_97
Training final model 99/424: target_98
Training final model 100/424: target_99
Finished 100/424 models in 1.05 minutes
Training final model 101/424: target_100
Training final model 102/424: target_101
Training final model 103/424: target_102
Training final model 104/424: target_103
Training final model 105/424: target_104
Training final model 106/424: target_105
Training final model 107/424: target_106
Training final model 108/424: target_107
Training final model 109/424: target_108
Training final model 110/424: target_109
Training final model 111/424: target_110
Training final model 112/424: target_111
Training final model 113/424: target_112
Training final model 114/424: target_113
Training final model 115/424: target_114
Training final model 116/424: target_115
Training final model 117/424: target_116
Training final model 118/424: target_117
Training final model 119/424: target_118
Training final model 120/424: target_119
Training final model 121/424: target_120
Training final model 122/424: target_121
Training final model 123/424: target_122
Training final model 124/424: target_123
Training final model 125/424: target_124
Finished 125/424 models in 1.33 minutes
Training final model 126/424: target_125
Training final model 127/424: target_126
Training final model 128/424: target_127
Training final model 129/424: target_128
Training final model 130/424: target_129
Training final model 131/424: target_130
Training final model 132/424: target_131
Training final model 133/424: target_132
Training final model 134/424: target_133
Training final model 135/424: target_134
Training final model 136/424: target_135
Training final model 137/424: target_136
Training final model 138/424: target_137
Training final model 139/424: target_138
Training final model 140/424: target_139
Training final model 141/424: target_140
Training final model 142/424: target_141
Training final model 143/424: target_142
Training final model 144/424: target_143
Training final model 145/424: target_144
Training final model 146/424: target_145
Training final model 147/424: target_146
Training final model 148/424: target_147
Training final model 149/424: target_148
Training final model 150/424: target_149
Finished 150/424 models in 1.59 minutes
Training final model 151/424: target_150
Training final model 152/424: target_151
Training final model 153/424: target_152
Training final model 154/424: target_153
Training final model 155/424: target_154
Training final model 156/424: target_155
Training final model 157/424: target_156
Training final model 158/424: target_157
Training final model 159/424: target_158
Training final model 160/424: target_159
Training final model 161/424: target_160
Training final model 162/424: target_161
Training final model 163/424: target_162
Training final model 164/424: target_163
Training final model 165/424: target_164
Training final model 166/424: target_165
Training final model 167/424: target_166
Training final model 168/424: target_167
Training final model 169/424: target_168
Training final model 170/424: target_169
Training final model 171/424: target_170
Training final model 172/424: target_171
Training final model 173/424: target_172
Training final model 174/424: target_173
Training final model 175/424: target_174
Finished 175/424 models in 1.85 minutes
Training final model 176/424: target_175
Training final model 177/424: target_176
Training final model 178/424: target_177
Training final model 179/424: target_178
Training final model 180/424: target_179
Training final model 181/424: target_180
Training final model 182/424: target_181
Training final model 183/424: target_182
Training final model 184/424: target_183
Training final model 185/424: target_184
Training final model 186/424: target_185
Training final model 187/424: target_186
Training final model 188/424: target_187
Training final model 189/424: target_188
Training final model 190/424: target_189
Training final model 191/424: target_190
Training final model 192/424: target_191
Training final model 193/424: target_192
Training final model 194/424: target_193
Training final model 195/424: target_194
Training final model 196/424: target_195
Training final model 197/424: target_196
Training final model 198/424: target_197
Training final model 199/424: target_198
Training final model 200/424: target_199
Finished 200/424 models in 2.13 minutes
Training final model 201/424: target_200
Training final model 202/424: target_201
Training final model 203/424: target_202
Training final model 204/424: target_203
Training final model 205/424: target_204
Training final model 206/424: target_205
Training final model 207/424: target_206
Training final model 208/424: target_207
Training final model 209/424: target_208
Training final model 210/424: target_209
Training final model 211/424: target_210
Training final model 212/424: target_211
Training final model 213/424: target_212
Training final model 214/424: target_213
Training final model 215/424: target_214
Training final model 216/424: target_215
Training final model 217/424: target_216
Training final model 218/424: target_217
Training final model 219/424: target_218
Training final model 220/424: target_219
Training final model 221/424: target_220
Training final model 222/424: target_221
Training final model 223/424: target_222
Training final model 224/424: target_223
Training final model 225/424: target_224
Finished 225/424 models in 2.40 minutes
Training final model 226/424: target_225
Training final model 227/424: target_226
Training final model 228/424: target_227
Training final model 229/424: target_228
Training final model 230/424: target_229
Training final model 231/424: target_230
Training final model 232/424: target_231
Training final model 233/424: target_232
Training final model 234/424: target_233
Training final model 235/424: target_234
Training final model 236/424: target_235
Training final model 237/424: target_236
Training final model 238/424: target_237
Training final model 239/424: target_238
Training final model 240/424: target_239
Training final model 241/424: target_240
Training final model 242/424: target_241
Training final model 243/424: target_242
Training final model 244/424: target_243
Training final model 245/424: target_244
Training final model 246/424: target_245
Training final model 247/424: target_246
Training final model 248/424: target_247
Training final model 249/424: target_248
Training final model 250/424: target_249
Finished 250/424 models in 2.67 minutes
Training final model 251/424: target_250
Training final model 252/424: target_251
Training final model 253/424: target_252
Training final model 254/424: target_253
Training final model 255/424: target_254
Training final model 256/424: target_255
Training final model 257/424: target_256
Training final model 258/424: target_257
Training final model 259/424: target_258
Training final model 260/424: target_259
Training final model 261/424: target_260
Training final model 262/424: target_261
Training final model 263/424: target_262
Training final model 264/424: target_263
Training final model 265/424: target_264
Training final model 266/424: target_265
Training final model 267/424: target_266
Training final model 268/424: target_267
Training final model 269/424: target_268
Training final model 270/424: target_269
Training final model 271/424: target_270
Training final model 272/424: target_271
Training final model 273/424: target_272
Training final model 274/424: target_273
Training final model 275/424: target_274
Finished 275/424 models in 2.94 minutes
Training final model 276/424: target_275
Training final model 277/424: target_276
Training final model 278/424: target_277
Training final model 279/424: target_278
Training final model 280/424: target_279
Training final model 281/424: target_280
Training final model 282/424: target_281
Training final model 283/424: target_282
Training final model 284/424: target_283
Training final model 285/424: target_284
Training final model 286/424: target_285
Training final model 287/424: target_286
Training final model 288/424: target_287
Training final model 289/424: target_288
Training final model 290/424: target_289
Training final model 291/424: target_290
Training final model 292/424: target_291
Training final model 293/424: target_292
Training final model 294/424: target_293
Training final model 295/424: target_294
Training final model 296/424: target_295
Training final model 297/424: target_296
Training final model 298/424: target_297
Training final model 299/424: target_298
Training final model 300/424: target_299
Finished 300/424 models in 3.22 minutes
Training final model 301/424: target_300
Training final model 302/424: target_301
Training final model 303/424: target_302
Training final model 304/424: target_303
Training final model 305/424: target_304
Training final model 306/424: target_305
Training final model 307/424: target_306
Training final model 308/424: target_307
Training final model 309/424: target_308
Training final model 310/424: target_309
Training final model 311/424: target_310
Training final model 312/424: target_311
Training final model 313/424: target_312
Training final model 314/424: target_313
Training final model 315/424: target_314
Training final model 316/424: target_315
Training final model 317/424: target_316
Training final model 318/424: target_317
Training final model 319/424: target_318
Training final model 320/424: target_319
Training final model 321/424: target_320
Training final model 322/424: target_321
Training final model 323/424: target_322
Training final model 324/424: target_323
Training final model 325/424: target_324
Finished 325/424 models in 3.48 minutes
Training final model 326/424: target_325
Training final model 327/424: target_326
Training final model 328/424: target_327
Training final model 329/424: target_328
Training final model 330/424: target_329
Training final model 331/424: target_330
Training final model 332/424: target_331
Training final model 333/424: target_332
Training final model 334/424: target_333
Training final model 335/424: target_334
Training final model 336/424: target_335
Training final model 337/424: target_336
Training final model 338/424: target_337
Training final model 339/424: target_338
Training final model 340/424: target_339
Training final model 341/424: target_340
Training final model 342/424: target_341
Training final model 343/424: target_342
Training final model 344/424: target_343
Training final model 345/424: target_344
Training final model 346/424: target_345
Training final model 347/424: target_346
Training final model 348/424: target_347
Training final model 349/424: target_348
Training final model 350/424: target_349
Finished 350/424 models in 3.75 minutes
Training final model 351/424: target_350
Training final model 352/424: target_351
Training final model 353/424: target_352
Training final model 354/424: target_353
Training final model 355/424: target_354
Training final model 356/424: target_355
Training final model 357/424: target_356
Training final model 358/424: target_357
Training final model 359/424: target_358
Training final model 360/424: target_359
Training final model 361/424: target_360
Training final model 362/424: target_361
Training final model 363/424: target_362
Training final model 364/424: target_363
Training final model 365/424: target_364
Training final model 366/424: target_365
Training final model 367/424: target_366
Training final model 368/424: target_367
Training final model 369/424: target_368
Training final model 370/424: target_369
Training final model 371/424: target_370
Training final model 372/424: target_371
Training final model 373/424: target_372
Training final model 374/424: target_373
Training final model 375/424: target_374
Finished 375/424 models in 4.02 minutes
Training final model 376/424: target_375
Training final model 377/424: target_376
Training final model 378/424: target_377
Training final model 379/424: target_378
Training final model 380/424: target_379
Training final model 381/424: target_380
Training final model 382/424: target_381
Training final model 383/424: target_382
Training final model 384/424: target_383
Training final model 385/424: target_384
Training final model 386/424: target_385
Training final model 387/424: target_386
Training final model 388/424: target_387
Training final model 389/424: target_388
Training final model 390/424: target_389
Training final model 391/424: target_390
Training final model 392/424: target_391
Training final model 393/424: target_392
Training final model 394/424: target_393
Training final model 395/424: target_394
Training final model 396/424: target_395
Training final model 397/424: target_396
Training final model 398/424: target_397
Training final model 399/424: target_398
Training final model 400/424: target_399
Finished 400/424 models in 4.29 minutes
Training final model 401/424: target_400
Training final model 402/424: target_401
Training final model 403/424: target_402
Training final model 404/424: target_403
Training final model 405/424: target_404
Training final model 406/424: target_405
Training final model 407/424: target_406
Training final model 408/424: target_407
Training final model 409/424: target_408
Training final model 410/424: target_409
Training final model 411/424: target_410
Training final model 412/424: target_411
Training final model 413/424: target_412
Training final model 414/424: target_413
Training final model 415/424: target_414
Training final model 416/424: target_415
Training final model 417/424: target_416
Training final model 418/424: target_417
Training final model 419/424: target_418
Training final model 420/424: target_419
Training final model 421/424: target_420
Training final model 422/424: target_421
Training final model 423/424: target_422
Training final model 424/424: target_423
Finished training non-leaky final models.
Training rows used: 1827
Training date range: 0 to 1826

In [22]:
# ============================================================
# Create Non-Leaky submission.parquet from final_models
# No inference server needed for local evaluation
# ============================================================

import numpy as np
import pandas as pd
import os

submission_nonleaky = pd.DataFrame(index=test.index)

X_test = test[clean_feature_cols]

for i, target in enumerate(target_cols):
    model = final_models.get(target)

    if model is None:
        submission_nonleaky[target] = 0.0
    else:
        submission_nonleaky[target] = model.predict(X_test)

    if (i + 1) % 50 == 0:
        print(f"Predicted {i + 1}/{len(target_cols)} targets")

# Add date_id as first column for local scoring
submission_nonleaky.insert(0, "date_id", test["date_id"].values)

# Save it
submission_nonleaky.to_parquet("/kaggle/working/submission.parquet", index=False)

print("Saved new non-leaky submission.parquet")
print("Shape:", submission_nonleaky.shape)
print("Date range:", submission_nonleaky["date_id"].min(), "to", submission_nonleaky["date_id"].max())

display(submission_nonleaky.head())

print("\nFiles in /kaggle/working:")
print(os.listdir("/kaggle/working"))

/usr/local/lib/python3.12/dist-packages/xgboost/core.py:751: UserWarning: [00:02:13] WARNING: /__w/xgboost/xgboost/src/common/error_msg.cc:62: Falling back to prediction using DMatrix due to mismatched devices. This might lead to higher memory usage and slower performance. XGBoost is running on: cuda:0, while the input data is on: cpu.
Potential solutions:
- Use a data structure that matches the device ordinal in the booster.
- Set the device for booster before call to inplace_predict.

This warning will only be shown once.

  return func(**kwargs)

Predicted 50/424 targets
Predicted 100/424 targets

/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)

Predicted 150/424 targets

/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)

Predicted 200/424 targets

/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)

Predicted 250/424 targets

/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)

Predicted 300/424 targets

/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)

Predicted 350/424 targets

/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)

Predicted 400/424 targets

/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)

Saved new non-leaky submission.parquet
Shape: (134, 425)
Date range: 1827 to 1960

/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky[target] = model.predict(X_test)
/tmp/ipykernel_57/1178997062.py:26: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_nonleaky.insert(0, "date_id", test["date_id"].values)

,date_id,target_0,target_1,target_2,target_3,target_4,target_5,target_6,target_7,target_8,...,target_414,target_415,target_416,target_417,target_418,target_419,target_420,target_421,target_422,target_423
0,1827,0.001397,-0.007244,-0.003714,0.001716,0.004354,0.006134,-0.003262,-0.001005,-0.002267,...,0.014999,-0.000096,-0.004643,-0.014272,-0.004188,-0.005748,0.015238,-0.003963,-0.012463,-0.039340
1,1828,-0.000192,-0.001668,0.000783,0.002531,0.002945,0.003765,-0.004928,-0.002346,-0.000172,...,-0.004429,0.005148,-0.001666,-0.003991,0.002126,-0.000042,-0.014805,0.005662,-0.002776,-0.011279
2,1829,0.000522,-0.000267,-0.002634,-0.002265,0.004392,0.005285,-0.004283,0.001195,-0.000623,...,0.014770,-0.001177,-0.002916,-0.012869,-0.006690,-0.006117,0.010024,-0.003807,-0.008481,-0.045432
3,1830,0.001464,-0.000927,-0.001004,0.000064,0.000979,0.006482,-0.001933,0.001609,-0.000206,...,0.012618,0.000052,-0.004643,-0.001133,-0.005401,-0.009232,0.013605,-0.002726,-0.001440,-0.020131
4,1831,0.000205,-0.000881,-0.001867,-0.003818,0.001591,0.005174,-0.003177,0.001528,-0.001974,...,0.011643,-0.001033,-0.003363,-0.018808,-0.005433,-0.004857,0.009465,0.000193,-0.006613,-0.020118

Files in /kaggle/working:
['submission.parquet', '.virtual_documents']

In [23]:
# ============================================================
# Evaluate Non-Leaky submission.parquet Against Ground Truth CSV
# ============================================================

import os
import numpy as np
import pandas as pd

SOLUTION_NULL_FILLER = -999999

submission_path = "/kaggle/working/submission.parquet"
ground_truth_path = "/kaggle/input/datasets/stephenweiler208/ground-truth"
competition_data_path = "/kaggle/input/competitions/mitsui-commodity-prediction-challenge"

# ------------------------------------------------------------
# 1. Find/load ground truth CSV
# ------------------------------------------------------------

if os.path.isdir(ground_truth_path):
    csv_files = [f for f in os.listdir(ground_truth_path) if f.endswith(".csv")]
    if len(csv_files) == 0:
        raise FileNotFoundError("No CSV file found in ground truth folder.")
    ground_truth_path = os.path.join(ground_truth_path, csv_files[0])

solution = pd.read_csv(ground_truth_path)

# ------------------------------------------------------------
# 2. Load new submission.parquet
# ------------------------------------------------------------

submission = pd.read_parquet(submission_path)

print("Submission shape:", submission.shape)
print("Solution shape:", solution.shape)

# ------------------------------------------------------------
# 3. Add date_id to submission if missing
# ------------------------------------------------------------

if "date_id" not in submission.columns:
    test = pd.read_csv(f"{competition_data_path}/test.csv")
    test_date_ids = test["date_id"].drop_duplicates().reset_index(drop=True)

    submission = submission.copy()
    submission.insert(0, "date_id", test_date_ids.iloc[:len(submission)].values)

# ------------------------------------------------------------
# 4. Align target columns
# ------------------------------------------------------------

target_cols = [c for c in solution.columns if c.startswith("target_")]

solution = solution[["date_id"] + target_cols].copy()
submission = submission[["date_id"] + target_cols].copy()

solution = solution.sort_values("date_id").reset_index(drop=True)
submission = submission.sort_values("date_id").reset_index(drop=True)

print("Solution date range:", solution["date_id"].min(), "to", solution["date_id"].max())
print("Submission date range:", submission["date_id"].min(), "to", submission["date_id"].max())
print("Date IDs match:", list(solution["date_id"]) == list(submission["date_id"]))
print("Columns match:", list(solution.columns) == list(submission.columns))

display(solution.head())
display(submission.head())

# ------------------------------------------------------------
# 5. Official-style metric
# ------------------------------------------------------------

def rank_correlation_sharpe_ratio(merged_df: pd.DataFrame) -> float:
    prediction_cols = [col for col in merged_df.columns if col.startswith("prediction_")]
    target_cols_metric = [col for col in merged_df.columns if col.startswith("target_")]

    def _compute_rank_correlation(row):
        non_null_targets = [col for col in target_cols_metric if not pd.isnull(row[col])]

        matching_predictions = [
            col for col in prediction_cols
            if col.replace("prediction", "target") in non_null_targets
        ]

        if not non_null_targets:
            return np.nan

        if row[non_null_targets].std(ddof=0) == 0 or row[matching_predictions].std(ddof=0) == 0:
            return np.nan

        return np.corrcoef(
            row[matching_predictions].rank(method="average"),
            row[non_null_targets].rank(method="average")
        )[0, 1]

    daily_rank_corrs = merged_df.apply(_compute_rank_correlation, axis=1).dropna()

    std_dev = daily_rank_corrs.std(ddof=0)

    if std_dev == 0:
        raise ZeroDivisionError("Denominator is zero, unable to compute Sharpe ratio.")

    print("\nDaily rank correlation summary:")
    display(daily_rank_corrs.describe())

    print("\nMean daily rank correlation:", daily_rank_corrs.mean())
    print("Std daily rank correlation:", std_dev)

    return float(daily_rank_corrs.mean() / std_dev)


def score(solution: pd.DataFrame, submission: pd.DataFrame, row_id_column_name: str) -> float:
    solution = solution.copy()
    submission = submission.copy()

    del solution[row_id_column_name]
    del submission[row_id_column_name]

    assert all(solution.columns == submission.columns), "Solution and submission columns do not match."

    submission = submission.rename(
        columns={col: col.replace("target_", "prediction_") for col in submission.columns}
    )

    solution = solution.replace(SOLUTION_NULL_FILLER, None)

    return rank_correlation_sharpe_ratio(
        pd.concat([solution, submission], axis="columns")
    )

# ------------------------------------------------------------
# 6. Calculate score
# ------------------------------------------------------------

nonleaky_local_score = score(
    solution=solution,
    submission=submission,
    row_id_column_name="date_id"
)

print("\nNon-leaky local competition-style Sharpe score:")
print(nonleaky_local_score)

Submission shape: (134, 425)
Solution shape: (134, 425)
Solution date range: 1827 to 1960
Submission date range: 1827 to 1960
Date IDs match: True
Columns match: True

,date_id,target_0,target_1,target_2,target_3,target_4,target_5,target_6,target_7,target_8,...,target_414,target_415,target_416,target_417,target_418,target_419,target_420,target_421,target_422,target_423
0,1827,NaN,NaN,0.017868,-0.000205,-0.016391,-0.013827,0.009972,NaN,NaN,...,NaN,0.019701,NaN,-0.027030,0.043602,0.027982,NaN,NaN,0.002177,NaN
1,1828,0.002560,-0.004592,-0.001776,0.000271,-0.016696,-0.020025,0.002514,0.002204,-0.011962,...,0.012063,0.012081,-0.020068,0.002858,0.019154,0.019018,0.003875,-0.035202,0.011246,0.099241
2,1829,0.005346,-0.014539,0.019542,0.014626,-0.011631,-0.009223,-0.005199,-0.026092,-0.003865,...,-0.009004,0.016166,-0.028919,-0.007297,0.033262,0.023174,-0.028512,-0.017900,-0.002096,0.121451
3,1830,0.000082,-0.005226,0.011452,0.013346,0.008228,-0.014819,-0.011792,-0.007148,0.005712,...,-0.013857,-0.007742,-0.018436,0.004691,0.013311,0.000589,-0.014500,-0.046444,0.009058,0.109246
4,1831,-0.011469,0.016613,-0.023765,-0.018744,-0.011878,0.007257,0.019829,0.006618,-0.015351,...,-0.015625,-0.018850,-0.025373,0.031197,0.005873,-0.005650,-0.022926,-0.027990,0.011267,0.091318

,date_id,target_0,target_1,target_2,target_3,target_4,target_5,target_6,target_7,target_8,...,target_414,target_415,target_416,target_417,target_418,target_419,target_420,target_421,target_422,target_423
0,1827,0.001397,-0.007244,-0.003714,0.001716,0.004354,0.006134,-0.003262,-0.001005,-0.002267,...,0.014999,-0.000096,-0.004643,-0.014272,-0.004188,-0.005748,0.015238,-0.003963,-0.012463,-0.039340
1,1828,-0.000192,-0.001668,0.000783,0.002531,0.002945,0.003765,-0.004928,-0.002346,-0.000172,...,-0.004429,0.005148,-0.001666,-0.003991,0.002126,-0.000042,-0.014805,0.005662,-0.002776,-0.011279
2,1829,0.000522,-0.000267,-0.002634,-0.002265,0.004392,0.005285,-0.004283,0.001195,-0.000623,...,0.014770,-0.001177,-0.002916,-0.012869,-0.006690,-0.006117,0.010024,-0.003807,-0.008481,-0.045432
3,1830,0.001464,-0.000927,-0.001004,0.000064,0.000979,0.006482,-0.001933,0.001609,-0.000206,...,0.012618,0.000052,-0.004643,-0.001133,-0.005401,-0.009232,0.013605,-0.002726,-0.001440,-0.020131
4,1831,0.000205,-0.000881,-0.001867,-0.003818,0.001591,0.005174,-0.003177,0.001528,-0.001974,...,0.011643,-0.001033,-0.003363,-0.018808,-0.005433,-0.004857,0.009465,0.000193,-0.006613,-0.020118

Daily rank correlation summary:

count    134.000000
mean       0.003122
std        0.157294
min       -0.453540
25%       -0.127982
50%        0.001358
75%        0.105620
max        0.426189
dtype: float64

Mean daily rank correlation: 0.0031218972432591275
Std daily rank correlation: 0.15670566916411302

Non-leaky local competition-style Sharpe score:
0.019922044045449692

In [16]:
# ============================================================
# Improved Non-Leaky XGBoost
# Adds lagged target-label features from train_labels / lagged_test_labels
# Evaluates directly against local ground truth
# ============================================================

import os
import gc
import time
import numpy as np
import pandas as pd
from xgboost import XGBRegressor

SOLUTION_NULL_FILLER = -999999

competition_data_path = "/kaggle/input/competitions/mitsui-commodity-prediction-challenge"
ground_truth_path = "/kaggle/input/datasets/stephenweiler208/ground-truth"

# ------------------------------------------------------------
# 1. Load ground truth
# ------------------------------------------------------------

if os.path.isdir(ground_truth_path):
    csv_files = [f for f in os.listdir(ground_truth_path) if f.endswith(".csv")]
    if len(csv_files) == 0:
        raise FileNotFoundError("No CSV found in ground truth folder.")
    ground_truth_path = os.path.join(ground_truth_path, csv_files[0])

solution = pd.read_csv(ground_truth_path)

print("Ground truth shape:", solution.shape)
print("Ground truth date range:", solution["date_id"].min(), "to", solution["date_id"].max())

local_test_start = solution["date_id"].min()
local_test_end = solution["date_id"].max()

# ------------------------------------------------------------
# 2. Target metadata
# ------------------------------------------------------------

target_pairs = pd.read_csv(f"{competition_data_path}/target_pairs.csv")
target_cols = target_pairs["target"].tolist()

target_lag_map = target_pairs.set_index("target")["lag"].to_dict()

print("Number of targets:", len(target_cols))
print(target_pairs.head())

# ------------------------------------------------------------
# 3. Build lagged-label features for TRAIN - cleaner/faster
# ------------------------------------------------------------

lag_feature_dict = {}

for target in target_cols:
    lag = int(target_lag_map[target])
    lag_feature_dict[f"lag_label_{target}"] = train_labels[target].shift(lag)

train_label_lag_features = pd.DataFrame(lag_feature_dict)
train_label_lag_features.insert(0, "date_id", train_labels["date_id"].values)

# Defragment
train_label_lag_features = train_label_lag_features.copy()

print("Train lag-label feature shape:", train_label_lag_features.shape)
display(train_label_lag_features.head())

# ------------------------------------------------------------
# 4. Build lagged-label features for TEST
# ------------------------------------------------------------
# In the Kaggle gateway, these are the label_lags_1 through label_lags_4 inputs.
# Locally, we rebuild the same thing from lagged_test_labels.

test_label_lag_features = pd.DataFrame({"date_id": test["date_id"].values})

for lag in [1, 2, 3, 4]:
    lag_df = pd.read_csv(
        f"{competition_data_path}/lagged_test_labels/test_labels_lag_{lag}.csv"
    )

    lag_targets = target_pairs.loc[target_pairs["lag"] == lag, "target"].tolist()
    available_targets = [c for c in lag_targets if c in lag_df.columns]

    temp = lag_df[["date_id"] + available_targets].copy()

    rename_map = {c: f"lag_label_{c}" for c in available_targets}
    temp = temp.rename(columns=rename_map)

    test_label_lag_features = test_label_lag_features.merge(
        temp,
        on="date_id",
        how="left"
    )

print("Test lag-label feature shape:", test_label_lag_features.shape)
display(test_label_lag_features.head())

# ------------------------------------------------------------
# 5. Combine market features + lag-label features
# ------------------------------------------------------------

train_features_improved = train[["date_id"] + clean_feature_cols].merge(
    train_label_lag_features,
    on="date_id",
    how="left"
)

test_features_improved = test[["date_id"] + clean_feature_cols].merge(
    test_label_lag_features,
    on="date_id",
    how="left"
)

improved_feature_cols = [
    c for c in train_features_improved.columns
    if c != "date_id"
]

print("Original feature count:", len(clean_feature_cols))
print("Improved feature count:", len(improved_feature_cols))

# ------------------------------------------------------------
# 6. Non-leaky train/test split
# ------------------------------------------------------------

train_nonleaky_mask = train_features_improved["date_id"] < local_test_start

X_train_improved = train_features_improved.loc[train_nonleaky_mask, improved_feature_cols]
X_test_improved = test_features_improved[improved_feature_cols]

print("Non-leaky training rows:", X_train_improved.shape)
print("Local test rows:", X_test_improved.shape)
print("Training date range:",
      train_features_improved.loc[train_nonleaky_mask, "date_id"].min(),
      "to",
      train_features_improved.loc[train_nonleaky_mask, "date_id"].max())

# ------------------------------------------------------------
# 7. Train one XGBoost model per target
# ------------------------------------------------------------

best_config_params = {
    "n_estimators": 300,
    "learning_rate": 0.035,
    "max_depth": 2,
    "subsample": 0.9,
    "colsample_bytree": 0.85,
    "reg_alpha": 0.05,
    "reg_lambda": 3.0,
    "min_child_weight": 3,
}

submission_improved = pd.DataFrame(index=test.index)

start_time = time.time()

for i, target in enumerate(target_cols):
    y_train = train_labels.loc[train_nonleaky_mask, target].values
    target_mask = ~np.isnan(y_train)

    if target_mask.sum() < 100:
        submission_improved[target] = 0.0
        continue

    model = XGBRegressor(
        **best_config_params,
        objective="reg:squarederror",
        tree_method="hist",
        random_state=42,
        n_jobs=-1,
        eval_metric="rmse"
    )

    model.fit(
        X_train_improved.loc[target_mask],
        y_train[target_mask],
        verbose=False
    )

    submission_improved[target] = model.predict(X_test_improved)

    if (i + 1) % 50 == 0:
        elapsed = (time.time() - start_time) / 60
        print(f"Finished {i + 1}/{len(target_cols)} targets in {elapsed:.2f} minutes")

    del model
    gc.collect()

submission_improved.insert(0, "date_id", test["date_id"].values)

print("Improved submission shape:", submission_improved.shape)
display(submission_improved.head())

# ------------------------------------------------------------
# 8. Competition-style metric
# ------------------------------------------------------------

def rank_correlation_sharpe_ratio(merged_df: pd.DataFrame) -> float:
    prediction_cols = [col for col in merged_df.columns if col.startswith("prediction_")]
    target_cols_metric = [col for col in merged_df.columns if col.startswith("target_")]

    def _compute_rank_correlation(row):
        non_null_targets = [col for col in target_cols_metric if not pd.isnull(row[col])]

        matching_predictions = [
            col for col in prediction_cols
            if col.replace("prediction", "target") in non_null_targets
        ]

        if not non_null_targets:
            return np.nan

        if row[non_null_targets].std(ddof=0) == 0 or row[matching_predictions].std(ddof=0) == 0:
            return np.nan

        return np.corrcoef(
            row[matching_predictions].rank(method="average"),
            row[non_null_targets].rank(method="average")
        )[0, 1]

    daily_rank_corrs = merged_df.apply(_compute_rank_correlation, axis=1).dropna()

    std_dev = daily_rank_corrs.std(ddof=0)

    if std_dev == 0:
        raise ZeroDivisionError("Denominator is zero, unable to compute Sharpe ratio.")

    print("\nDaily rank correlation summary:")
    display(daily_rank_corrs.describe())

    print("\nMean daily rank correlation:", daily_rank_corrs.mean())
    print("Std daily rank correlation:", std_dev)

    return float(daily_rank_corrs.mean() / std_dev)


def score(solution: pd.DataFrame, submission: pd.DataFrame, row_id_column_name: str) -> float:
    solution = solution.copy()
    submission = submission.copy()

    del solution[row_id_column_name]
    del submission[row_id_column_name]

    assert all(solution.columns == submission.columns), "Solution and submission columns do not match."

    submission = submission.rename(
        columns={col: col.replace("target_", "prediction_") for col in submission.columns}
    )

    solution = solution.replace(SOLUTION_NULL_FILLER, None)

    return rank_correlation_sharpe_ratio(
        pd.concat([solution, submission], axis="columns")
    )

# ------------------------------------------------------------
# 9. Align and score
# ------------------------------------------------------------

solution_eval = solution[["date_id"] + target_cols].copy()
submission_eval = submission_improved[["date_id"] + target_cols].copy()

solution_eval = solution_eval.sort_values("date_id").reset_index(drop=True)
submission_eval = submission_eval.sort_values("date_id").reset_index(drop=True)

print("\nDate IDs match:", list(solution_eval["date_id"]) == list(submission_eval["date_id"]))
print("Columns match:", list(solution_eval.columns) == list(submission_eval.columns))

improved_score = score(
    solution=solution_eval,
    submission=submission_eval,
    row_id_column_name="date_id"
)

print("\nImproved non-leaky local competition-style Sharpe score:")
print(improved_score)

Ground truth shape: (134, 425)
Ground truth date range: 1827 to 1960
Number of targets: 424
     target  lag                                            pair
0  target_0    1                           US_Stock_VT_adj_close
1  target_1    1            LME_PB_Close - US_Stock_VT_adj_close
2  target_2    1                     LME_CA_Close - LME_ZS_Close
3  target_3    1                     LME_AH_Close - LME_ZS_Close
4  target_4    1  LME_AH_Close - JPX_Gold_Standard_Futures_Close
Train lag-label feature shape: (1961, 425)

,date_id,lag_label_target_0,lag_label_target_1,lag_label_target_2,lag_label_target_3,lag_label_target_4,lag_label_target_5,lag_label_target_6,lag_label_target_7,lag_label_target_8,...,lag_label_target_414,lag_label_target_415,lag_label_target_416,lag_label_target_417,lag_label_target_418,lag_label_target_419,lag_label_target_420,lag_label_target_421,lag_label_target_422,lag_label_target_423
0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,0.005948,-0.002851,-0.004675,-0.000639,NaN,NaN,-0.006729,0.006066,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,0.005783,-0.024118,-0.007052,-0.018955,-0.031852,-0.019452,0.003002,-0.006876,-0.002042,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,0.001048,0.023836,-0.008934,-0.022060,NaN,NaN,0.037449,0.007658,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,0.001700,-0.024618,0.011943,0.004778,NaN,NaN,-0.012519,-0.016896,NaN,...,NaN,0.021239,-0.005595,NaN,-0.004628,0.033793,NaN,0.038234,NaN,0.02731

Test lag-label feature shape: (134, 425)

,date_id,lag_label_target_0,lag_label_target_1,lag_label_target_2,lag_label_target_3,lag_label_target_4,lag_label_target_5,lag_label_target_6,lag_label_target_7,lag_label_target_8,...,lag_label_target_414,lag_label_target_415,lag_label_target_416,lag_label_target_417,lag_label_target_418,lag_label_target_419,lag_label_target_420,lag_label_target_421,lag_label_target_422,lag_label_target_423
0,1827,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1828,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1829,NaN,NaN,0.017868,-0.000205,-0.016391,-0.013827,0.009972,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1830,0.002560,-0.004592,-0.001776,0.000271,-0.016696,-0.020025,0.002514,0.002204,-0.011962,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1831,0.005346,-0.014539,0.019542,0.014626,-0.011631,-0.009223,-0.005199,-0.026092,-0.003865,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Original feature count: 552
Improved feature count: 976
Non-leaky training rows: (1827, 976)
Local test rows: (134, 976)
Training date range: 0 to 1826
Finished 50/424 targets in 6.82 minutes
Finished 100/424 targets in 13.44 minutes

/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)

Finished 150/424 targets in 20.25 minutes

/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)

Finished 200/424 targets in 26.81 minutes

/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)

Finished 250/424 targets in 33.37 minutes

/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)

Finished 300/424 targets in 39.93 minutes

/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)

Finished 350/424 targets in 46.58 minutes

/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)

Finished 400/424 targets in 53.35 minutes

/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)

Improved submission shape: (134, 425)

/tmp/ipykernel_57/2440537224.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved[target] = model.predict(X_test_improved)
/tmp/ipykernel_57/2440537224.py:189: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_improved.insert(0, "date_id", test["date_id"].values)

,date_id,target_0,target_1,target_2,target_3,target_4,target_5,target_6,target_7,target_8,...,target_414,target_415,target_416,target_417,target_418,target_419,target_420,target_421,target_422,target_423
0,1827,0.000199,-0.004756,0.001348,0.002029,-0.002466,-0.003424,0.002628,-0.005377,-0.001721,...,0.010415,0.009044,-0.002998,-0.005834,0.009665,-0.008783,0.013064,-0.000151,-0.003040,-0.002589
1,1828,0.001119,-0.003567,0.000975,0.003297,-0.001592,-0.004190,-0.000573,-0.006937,-0.000634,...,-0.001354,0.013304,0.000059,0.001522,0.012068,-0.003089,-0.012084,0.003514,0.000437,0.000640
2,1829,0.000148,-0.004049,0.000431,-0.000991,-0.003398,-0.004553,0.003426,-0.004228,-0.000813,...,0.010372,0.010407,-0.002998,-0.004294,0.004980,-0.006980,0.011751,-0.002638,0.000203,-0.012056
3,1830,0.002468,-0.003651,0.002886,0.000610,-0.002414,0.002542,0.001417,-0.003507,-0.000447,...,0.010201,0.008821,-0.003149,-0.001886,0.005314,-0.008023,0.012180,-0.003025,-0.003436,0.003685
4,1831,0.000036,-0.003934,-0.000207,-0.004526,0.000555,0.002394,0.002473,-0.000450,0.000121,...,0.007876,0.004935,-0.004009,-0.015645,0.000199,-0.007331,0.007486,-0.002094,-0.008293,0.011095

Date IDs match: True
Columns match: True

Daily rank correlation summary:

count    134.000000
mean       0.020860
std        0.204170
min       -0.579703
25%       -0.119633
50%        0.021209
75%        0.157433
max        0.486865
dtype: float64

Mean daily rank correlation: 0.020859988341959866
Std daily rank correlation: 0.20340721073879978

Improved non-leaky local competition-style Sharpe score:
0.1025528459202299

In [17]:
# ============================================================
# Best XGBoost Attempt: Non-Leaky + Corrected Lag Label Features
# + Rank Blend with Lag Baseline
# ============================================================

import os
import gc
import time
import warnings
import numpy as np
import pandas as pd

from xgboost import XGBRegressor

warnings.filterwarnings("ignore", category=pd.errors.PerformanceWarning)
warnings.filterwarnings("ignore", category=FutureWarning)

SOLUTION_NULL_FILLER = -999999

competition_data_path = "/kaggle/input/competitions/mitsui-commodity-prediction-challenge"
ground_truth_path = "/kaggle/input/datasets/stephenweiler208/ground-truth"

# ============================================================
# 1. Load Ground Truth
# ============================================================

if os.path.isdir(ground_truth_path):
    csv_files = [f for f in os.listdir(ground_truth_path) if f.endswith(".csv")]
    if len(csv_files) == 0:
        raise FileNotFoundError("No CSV file found in the ground truth folder.")
    ground_truth_path = os.path.join(ground_truth_path, csv_files[0])

solution = pd.read_csv(ground_truth_path)

print("Ground truth shape:", solution.shape)
print("Ground truth date range:", solution["date_id"].min(), "to", solution["date_id"].max())

local_test_start = solution["date_id"].min()
local_test_end = solution["date_id"].max()

# ============================================================
# 2. Metadata / Target Setup
# ============================================================

target_pairs = pd.read_csv(f"{competition_data_path}/target_pairs.csv")
target_cols = target_pairs["target"].tolist()
target_lag_map = target_pairs.set_index("target")["lag"].to_dict()

print("Number of targets:", len(target_cols))
display(target_pairs.head())

# ============================================================
# 3. Make Sure Clean Feature Columns Exist
# ============================================================

id_cols = ["date_id"]
feature_cols = [c for c in train.columns if c not in id_cols]

feature_missing_rate = train[feature_cols].isna().mean()
clean_feature_cols = feature_missing_rate[feature_missing_rate <= 0.50].index.tolist()

print("Original feature count:", len(feature_cols))
print("Clean feature count:", len(clean_feature_cols))

# ============================================================
# 4. Build Corrected Lag-Label Features for TRAIN
# No fragmentation: dictionary -> DataFrame
# ============================================================

lag_feature_dict = {}

for target in target_cols:
    lag = int(target_lag_map[target])

    # Corrected alignment:
    # test lag files show lag 1 labels for label_date_id 1827 appear at date_id 1829,
    # so training uses shift(lag + 1), not shift(lag).
    lag_feature_dict[f"lag_label_{target}"] = train_labels[target].shift(lag + 1)

train_label_lag_features = pd.DataFrame(lag_feature_dict)
train_label_lag_features.insert(0, "date_id", train_labels["date_id"].values)
train_label_lag_features = train_label_lag_features.copy()

print("Train lag-label feature shape:", train_label_lag_features.shape)
display(train_label_lag_features.head())

# ============================================================
# 5. Build Lag-Label Features for TEST
# No fragmentation: merge lag groups
# ============================================================

test_label_lag_features = pd.DataFrame({"date_id": test["date_id"].values})

for lag in [1, 2, 3, 4]:
    lag_df = pd.read_csv(
        f"{competition_data_path}/lagged_test_labels/test_labels_lag_{lag}.csv"
    )

    lag_targets = target_pairs.loc[target_pairs["lag"] == lag, "target"].tolist()
    available_targets = [c for c in lag_targets if c in lag_df.columns]

    temp = lag_df[["date_id"] + available_targets].copy()
    temp = temp.rename(columns={c: f"lag_label_{c}" for c in available_targets})

    test_label_lag_features = test_label_lag_features.merge(
        temp,
        on="date_id",
        how="left"
    )

test_label_lag_features = test_label_lag_features.copy()

print("Test lag-label feature shape:", test_label_lag_features.shape)
display(test_label_lag_features.head())

# ============================================================
# 6. Build Final Feature Matrices
# ============================================================

train_features_improved = train[["date_id"] + clean_feature_cols].merge(
    train_label_lag_features,
    on="date_id",
    how="left"
)

test_features_improved = test[["date_id"] + clean_feature_cols].merge(
    test_label_lag_features,
    on="date_id",
    how="left"
)

train_features_improved = train_features_improved.replace([np.inf, -np.inf], np.nan).copy()
test_features_improved = test_features_improved.replace([np.inf, -np.inf], np.nan).copy()

improved_feature_cols = [c for c in train_features_improved.columns if c != "date_id"]

print("Improved feature count:", len(improved_feature_cols))

# ============================================================
# 7. Non-Leaky Train / Local Test Split
# ============================================================

train_nonleaky_mask = train_features_improved["date_id"] < local_test_start

X_train_improved = train_features_improved.loc[train_nonleaky_mask, improved_feature_cols].copy()
X_test_improved = test_features_improved[improved_feature_cols].copy()

print("Non-leaky training rows:", X_train_improved.shape)
print("Local test rows:", X_test_improved.shape)
print(
    "Training date range:",
    train_features_improved.loc[train_nonleaky_mask, "date_id"].min(),
    "to",
    train_features_improved.loc[train_nonleaky_mask, "date_id"].max()
)

# ============================================================
# 8. Metric Functions
# ============================================================

def rank_correlation_sharpe_ratio(merged_df: pd.DataFrame) -> float:
    prediction_cols = [col for col in merged_df.columns if col.startswith("prediction_")]
    target_cols_metric = [col for col in merged_df.columns if col.startswith("target_")]

    daily_rank_corrs = []

    for _, row in merged_df.iterrows():
        non_null_targets = [col for col in target_cols_metric if not pd.isnull(row[col])]

        matching_predictions = [
            col for col in prediction_cols
            if col.replace("prediction", "target") in non_null_targets
        ]

        if len(non_null_targets) < 3:
            daily_rank_corrs.append(np.nan)
            continue

        if row[non_null_targets].std(ddof=0) == 0 or row[matching_predictions].std(ddof=0) == 0:
            daily_rank_corrs.append(np.nan)
            continue

        corr = np.corrcoef(
            row[matching_predictions].rank(method="average"),
            row[non_null_targets].rank(method="average")
        )[0, 1]

        daily_rank_corrs.append(corr)

    daily_rank_corrs = pd.Series(daily_rank_corrs).dropna()

    std_dev = daily_rank_corrs.std(ddof=0)

    if std_dev == 0:
        raise ZeroDivisionError("Denominator is zero, unable to compute Sharpe ratio.")

    print("\nDaily rank correlation summary:")
    display(daily_rank_corrs.describe())

    print("\nMean daily rank correlation:", daily_rank_corrs.mean())
    print("Std daily rank correlation:", std_dev)

    return float(daily_rank_corrs.mean() / std_dev)


def score(solution: pd.DataFrame, submission: pd.DataFrame, row_id_column_name: str) -> float:
    solution = solution.copy()
    submission = submission.copy()

    del solution[row_id_column_name]
    del submission[row_id_column_name]

    assert all(solution.columns == submission.columns), "Solution and submission columns do not match."

    submission = submission.rename(
        columns={col: col.replace("target_", "prediction_") for col in submission.columns}
    )

    solution = solution.replace(SOLUTION_NULL_FILLER, None)

    merged = pd.concat([solution, submission], axis="columns")

    return rank_correlation_sharpe_ratio(merged)


def evaluate_submission(submission_df, solution_df, target_cols, name="model"):
    solution_eval = solution_df[["date_id"] + target_cols].copy()
    submission_eval = submission_df[["date_id"] + target_cols].copy()

    solution_eval = solution_eval.sort_values("date_id").reset_index(drop=True)
    submission_eval = submission_eval.sort_values("date_id").reset_index(drop=True)

    print("\n" + "=" * 60)
    print(f"Evaluating: {name}")
    print("=" * 60)
    print("Date IDs match:", list(solution_eval["date_id"]) == list(submission_eval["date_id"]))
    print("Columns match:", list(solution_eval.columns) == list(submission_eval.columns))

    model_score = score(
        solution=solution_eval,
        submission=submission_eval,
        row_id_column_name="date_id"
    )

    print(f"\n{name} score:", model_score)

    return model_score


# ============================================================
# 9. Train XGBoost Models
# Stronger but still regularized
# ============================================================

best_config_params = {
    "n_estimators": 350,
    "learning_rate": 0.03,
    "max_depth": 2,
    "subsample": 0.9,
    "colsample_bytree": 0.8,
    "reg_alpha": 0.05,
    "reg_lambda": 4.0,
    "min_child_weight": 4,
}

submission_xgb = pd.DataFrame(index=test.index)

start_time = time.time()

for i, target in enumerate(target_cols):
    y_train = train_labels.loc[train_nonleaky_mask, target].values
    target_mask = ~np.isnan(y_train)

    if target_mask.sum() < 100:
        submission_xgb[target] = 0.0
        continue

    model = XGBRegressor(
        **best_config_params,
        objective="reg:squarederror",
        tree_method="hist",
        random_state=42,
        n_jobs=-1,
        eval_metric="rmse"
    )

    model.fit(
        X_train_improved.loc[target_mask],
        y_train[target_mask],
        verbose=False
    )

    submission_xgb[target] = model.predict(X_test_improved)

    if (i + 1) % 25 == 0:
        elapsed = (time.time() - start_time) / 60
        print(f"Finished {i + 1}/{len(target_cols)} targets in {elapsed:.2f} minutes")

    del model
    gc.collect()

submission_xgb.insert(0, "date_id", test["date_id"].values)
submission_xgb = submission_xgb[["date_id"] + target_cols].copy()

print("\nXGBoost prediction shape:", submission_xgb.shape)
display(submission_xgb.head())

# Save XGBoost predictions
submission_xgb.to_parquet("/kaggle/working/xgb_corrected_laglabel.parquet", index=False)

# ============================================================
# 10. Lag-Label Baseline
# ============================================================

submission_lag = pd.DataFrame(index=test.index)
submission_lag.insert(0, "date_id", test["date_id"].values)

for target in target_cols:
    col = f"lag_label_{target}"
    if col in test_label_lag_features.columns:
        submission_lag[target] = test_label_lag_features[col].values
    else:
        submission_lag[target] = 0.0

submission_lag = submission_lag[["date_id"] + target_cols].copy()
submission_lag[target_cols] = submission_lag[target_cols].fillna(0.0)

print("\nLag baseline shape:", submission_lag.shape)
display(submission_lag.head())

submission_lag.to_parquet("/kaggle/working/lag_baseline.parquet", index=False)

# ============================================================
# 11. Evaluate XGBoost Alone and Lag Baseline Alone
# ============================================================

xgb_score = evaluate_submission(
    submission_xgb,
    solution,
    target_cols,
    name="XGBoost corrected lag-label"
)

lag_score = evaluate_submission(
    submission_lag,
    solution,
    target_cols,
    name="Lag-label baseline"
)

# ============================================================
# 12. Rank-Blending Search
# ============================================================

solution_eval = solution[["date_id"] + target_cols].copy()
solution_eval = solution_eval.sort_values("date_id").reset_index(drop=True)

xgb_eval = submission_xgb.sort_values("date_id").reset_index(drop=True)
lag_eval = submission_lag.sort_values("date_id").reset_index(drop=True)

xgb_rank = xgb_eval[target_cols].rank(axis=1, method="average", ascending=True)
lag_rank = lag_eval[target_cols].rank(axis=1, method="average", ascending=True)

blend_scores = {}
blend_submissions = {}

for w_xgb in [0.00, 0.10, 0.20, 0.30, 0.40, 0.50, 0.60, 0.70, 0.80, 0.90, 1.00]:
    w_lag = 1.0 - w_xgb

    blended_values = (w_xgb * xgb_rank) + (w_lag * lag_rank)

    blended_submission = blended_values.copy()
    blended_submission.insert(0, "date_id", xgb_eval["date_id"].values)
    blended_submission = blended_submission[["date_id"] + target_cols].copy()

    blend_name = f"xgb_{w_xgb:.2f}_lag_{w_lag:.2f}"

    blend_score = evaluate_submission(
        blended_submission,
        solution,
        target_cols,
        name=blend_name
    )

    blend_scores[blend_name] = blend_score
    blend_submissions[blend_name] = blended_submission

blend_scores_series = pd.Series(blend_scores).sort_values(ascending=False)

print("\n" + "=" * 60)
print("Blend score results")
print("=" * 60)
display(blend_scores_series)

best_blend_name = blend_scores_series.index[0]
best_blend_score = blend_scores_series.iloc[0]

print("\nBest blend:", best_blend_name)
print("Best blend score:", best_blend_score)

best_submission = blend_submissions[best_blend_name]

# Save best local-eval blend
best_submission.to_parquet("/kaggle/working/submission_best_local_blend.parquet", index=False)

# Also save as submission.parquet for convenience
best_submission.to_parquet("/kaggle/working/submission.parquet", index=False)

print("\nSaved:")
print("/kaggle/working/xgb_corrected_laglabel.parquet")
print("/kaggle/working/lag_baseline.parquet")
print("/kaggle/working/submission_best_local_blend.parquet")
print("/kaggle/working/submission.parquet")

print("\nFiles in /kaggle/working:")
print(os.listdir("/kaggle/working"))

Ground truth shape: (134, 425)
Ground truth date range: 1827 to 1960
Number of targets: 424

     target  lag                                            pair
0  target_0    1                           US_Stock_VT_adj_close
1  target_1    1            LME_PB_Close - US_Stock_VT_adj_close
2  target_2    1                     LME_CA_Close - LME_ZS_Close
3  target_3    1                     LME_AH_Close - LME_ZS_Close
4  target_4    1  LME_AH_Close - JPX_Gold_Standard_Futures_Close

Original feature count: 557
Clean feature count: 552
Train lag-label feature shape: (1961, 425)

,date_id,lag_label_target_0,lag_label_target_1,lag_label_target_2,lag_label_target_3,lag_label_target_4,lag_label_target_5,lag_label_target_6,lag_label_target_7,lag_label_target_8,...,lag_label_target_414,lag_label_target_415,lag_label_target_416,lag_label_target_417,lag_label_target_418,lag_label_target_419,lag_label_target_420,lag_label_target_421,lag_label_target_422,lag_label_target_423
0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,0.005948,-0.002851,-0.004675,-0.000639,NaN,NaN,-0.006729,0.006066,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,0.005783,-0.024118,-0.007052,-0.018955,-0.031852,-0.019452,0.003002,-0.006876,-0.002042,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,0.001048,0.023836,-0.008934,-0.022060,NaN,NaN,0.037449,0.007658,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Test lag-label feature shape: (134, 425)

,date_id,lag_label_target_0,lag_label_target_1,lag_label_target_2,lag_label_target_3,lag_label_target_4,lag_label_target_5,lag_label_target_6,lag_label_target_7,lag_label_target_8,...,lag_label_target_414,lag_label_target_415,lag_label_target_416,lag_label_target_417,lag_label_target_418,lag_label_target_419,lag_label_target_420,lag_label_target_421,lag_label_target_422,lag_label_target_423
0,1827,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1828,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1829,NaN,NaN,0.017868,-0.000205,-0.016391,-0.013827,0.009972,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1830,0.002560,-0.004592,-0.001776,0.000271,-0.016696,-0.020025,0.002514,0.002204,-0.011962,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1831,0.005346,-0.014539,0.019542,0.014626,-0.011631,-0.009223,-0.005199,-0.026092,-0.003865,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Improved feature count: 976
Non-leaky training rows: (1827, 976)
Local test rows: (134, 976)
Training date range: 0 to 1826
Finished 25/424 targets in 3.18 minutes
Finished 50/424 targets in 6.31 minutes
Finished 75/424 targets in 9.29 minutes
Finished 100/424 targets in 12.30 minutes
Finished 125/424 targets in 15.40 minutes
Finished 150/424 targets in 18.49 minutes
Finished 175/424 targets in 21.61 minutes
Finished 200/424 targets in 24.61 minutes
Finished 225/424 targets in 27.56 minutes
Finished 250/424 targets in 30.58 minutes
Finished 275/424 targets in 33.71 minutes
Finished 300/424 targets in 36.84 minutes
Finished 325/424 targets in 39.93 minutes
Finished 350/424 targets in 43.00 minutes
Finished 375/424 targets in 46.03 minutes
Finished 400/424 targets in 49.00 minutes

XGBoost prediction shape: (134, 425)

,date_id,target_0,target_1,target_2,target_3,target_4,target_5,target_6,target_7,target_8,...,target_414,target_415,target_416,target_417,target_418,target_419,target_420,target_421,target_422,target_423
0,1827,0.000208,-0.010183,0.000916,0.001983,-0.000331,-0.000852,-0.001594,-0.006609,-0.000741,...,0.011657,0.007223,-0.003035,-0.013572,0.009447,-0.011487,0.008974,-0.002003,-0.007579,-0.005179
1,1828,0.000130,-0.003426,0.000742,0.004019,0.000930,-0.000321,-0.004772,-0.004270,-0.000386,...,-0.004467,0.008219,0.001398,-0.003417,0.015092,0.000319,-0.015690,0.002647,-0.004818,-0.012453
2,1829,0.000178,-0.002344,0.001945,0.001365,0.002097,0.000384,-0.002733,-0.004398,0.000062,...,0.011731,0.006489,-0.002690,-0.010699,0.003258,-0.010037,0.007415,-0.005933,-0.006336,-0.010804
3,1830,0.000858,-0.004184,0.001905,0.002380,-0.000203,0.000528,-0.000304,-0.004267,-0.000671,...,0.013452,0.007902,-0.003571,-0.003996,0.003981,-0.013794,0.011549,-0.007698,-0.002186,0.006892
4,1831,-0.000235,-0.000029,-0.001297,0.000467,-0.000181,0.002841,-0.002759,-0.002484,-0.002586,...,0.009611,0.002988,-0.003044,-0.014749,0.000913,-0.009785,0.007872,-0.007413,-0.008291,0.013141

Lag baseline shape: (134, 425)

,date_id,target_0,target_1,target_2,target_3,target_4,target_5,target_6,target_7,target_8,...,target_414,target_415,target_416,target_417,target_418,target_419,target_420,target_421,target_422,target_423
0,1827,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,1828,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,1829,0.000000,0.000000,0.017868,-0.000205,-0.016391,-0.013827,0.009972,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,1830,0.002560,-0.004592,-0.001776,0.000271,-0.016696,-0.020025,0.002514,0.002204,-0.011962,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,1831,0.005346,-0.014539,0.019542,0.014626,-0.011631,-0.009223,-0.005199,-0.026092,-0.003865,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

============================================================
Evaluating: XGBoost corrected lag-label
============================================================
Date IDs match: True
Columns match: True

Daily rank correlation summary:

count    134.000000
mean       0.022377
std        0.185004
min       -0.437484
25%       -0.109959
50%        0.024662
75%        0.144630
max        0.729522
dtype: float64

Mean daily rank correlation: 0.022377159221927217
Std daily rank correlation: 0.1843122075214335

XGBoost corrected lag-label score: 0.12140899142193279

============================================================
Evaluating: Lag-label baseline
============================================================
Date IDs match: True
Columns match: True

Daily rank correlation summary:

count    132.000000
mean      -0.047044
std        0.209357
min       -0.515929
25%       -0.191362
50%       -0.036086
75%        0.092287
max        0.618680
dtype: float64

Mean daily rank correlation: -0.04704360977519529
Std daily rank correlation: 0.20856238407729139

Lag-label baseline score: -0.22556133496134825

============================================================
Evaluating: xgb_0.00_lag_1.00
============================================================
Date IDs match: True
Columns match: True

Daily rank correlation summary:

count    132.000000
mean      -0.047044
std        0.209357
min       -0.515929
25%       -0.191362
50%       -0.036086
75%        0.092287
max        0.618680
dtype: float64

Mean daily rank correlation: -0.04704360977519529
Std daily rank correlation: 0.20856238407729139

xgb_0.00_lag_1.00 score: -0.22556133496134825

============================================================
Evaluating: xgb_0.10_lag_0.90
============================================================
Date IDs match: True
Columns match: True

Daily rank correlation summary:

count    134.000000
mean      -0.039920
std        0.208731
min       -0.497074
25%       -0.187815
50%       -0.028267
75%        0.098559
max        0.598042
dtype: float64

Mean daily rank correlation: -0.03991999600859027
Std daily rank correlation: 0.20795058127491076

xgb_0.10_lag_0.90 score: -0.19196866757403297

============================================================
Evaluating: xgb_0.20_lag_0.80
============================================================
Date IDs match: True
Columns match: True

Daily rank correlation summary:

count    134.000000
mean      -0.036335
std        0.205626
min       -0.505038
25%       -0.186609
50%       -0.038455
75%        0.105135
max        0.563428
dtype: float64

Mean daily rank correlation: -0.03633508405383259
Std daily rank correlation: 0.20485686107269493

xgb_0.20_lag_0.80 score: -0.17736815776425874

============================================================
Evaluating: xgb_0.30_lag_0.70
============================================================
Date IDs match: True
Columns match: True

Daily rank correlation summary:

count    134.000000
mean      -0.030827
std        0.200599
min       -0.501000
25%       -0.185595
50%       -0.030121
75%        0.103075
max        0.505076
dtype: float64

Mean daily rank correlation: -0.03082706150064063
Std daily rank correlation: 0.19984939512076882

xgb_0.30_lag_0.70 score: -0.154251462617697

============================================================
Evaluating: xgb_0.40_lag_0.60
============================================================
Date IDs match: True
Columns match: True

Daily rank correlation summary:

count    134.000000
mean      -0.023745
std        0.194087
min       -0.513808
25%       -0.173476
50%       -0.028489
75%        0.100736
max        0.414819
dtype: float64

Mean daily rank correlation: -0.023745464795996953
Std daily rank correlation: 0.1933611846170134

xgb_0.40_lag_0.60 score: -0.1228036787374318

============================================================
Evaluating: xgb_0.50_lag_0.50
============================================================
Date IDs match: True
Columns match: True

Daily rank correlation summary:

count    134.000000
mean      -0.014463
std        0.186518
min       -0.525137
25%       -0.163641
50%       -0.012968
75%        0.149381
max        0.537142
dtype: float64

Mean daily rank correlation: -0.014462627254461537
Std daily rank correlation: 0.18582075688603752

xgb_0.50_lag_0.50 score: -0.07783106417616929

============================================================
Evaluating: xgb_0.60_lag_0.40
============================================================
Date IDs match: True
Columns match: True

Daily rank correlation summary:

count    134.000000
mean      -0.004498
std        0.181136
min       -0.496205
25%       -0.136705
50%       -0.005309
75%        0.148531
max        0.625525
dtype: float64

Mean daily rank correlation: -0.004497607154516305
Std daily rank correlation: 0.1804585594818406

xgb_0.60_lag_0.40 score: -0.02492321321543573

============================================================
Evaluating: xgb_0.70_lag_0.30
============================================================
Date IDs match: True
Columns match: True

Daily rank correlation summary:

count    134.000000
mean       0.004670
std        0.180420
min       -0.445907
25%       -0.136197
50%        0.005304
75%        0.116552
max        0.683838
dtype: float64

Mean daily rank correlation: 0.004670039263198901
Std daily rank correlation: 0.17974600748024455

xgb_0.70_lag_0.30 score: 0.02598132402864177

============================================================
Evaluating: xgb_0.80_lag_0.20
============================================================
Date IDs match: True
Columns match: True

Daily rank correlation summary:

count    134.000000
mean       0.012079
std        0.181594
min       -0.449424
25%       -0.128516
50%        0.010429
75%        0.136044
max        0.712886
dtype: float64

Mean daily rank correlation: 0.012078775288026937
Std daily rank correlation: 0.1809154313480492

xgb_0.80_lag_0.20 score: 0.06676475963396133

============================================================
Evaluating: xgb_0.90_lag_0.10
============================================================
Date IDs match: True
Columns match: True

Daily rank correlation summary:

count    134.000000
mean       0.018100
std        0.183159
min       -0.443948
25%       -0.116547
50%        0.014694
75%        0.139954
max        0.729559
dtype: float64

Mean daily rank correlation: 0.01809982944431775
Std daily rank correlation: 0.18247393365512865

xgb_0.90_lag_0.10 score: 0.09919131506490124

============================================================
Evaluating: xgb_1.00_lag_0.00
============================================================
Date IDs match: True
Columns match: True

Daily rank correlation summary:

count    134.000000
mean       0.022377
std        0.185004
min       -0.437484
25%       -0.109959
50%        0.024662
75%        0.144630
max        0.729522
dtype: float64

Mean daily rank correlation: 0.022377159221927217
Std daily rank correlation: 0.1843122075214335

xgb_1.00_lag_0.00 score: 0.12140899142193279

============================================================
Blend score results
============================================================

xgb_1.00_lag_0.00    0.121409
xgb_0.90_lag_0.10    0.099191
xgb_0.80_lag_0.20    0.066765
xgb_0.70_lag_0.30    0.025981
xgb_0.60_lag_0.40   -0.024923
xgb_0.50_lag_0.50   -0.077831
xgb_0.40_lag_0.60   -0.122804
xgb_0.30_lag_0.70   -0.154251
xgb_0.20_lag_0.80   -0.177368
xgb_0.10_lag_0.90   -0.191969
xgb_0.00_lag_1.00   -0.225561
dtype: float64

Best blend: xgb_1.00_lag_0.00
Best blend score: 0.12140899142193279

Saved:
/kaggle/working/xgb_corrected_laglabel.parquet
/kaggle/working/lag_baseline.parquet
/kaggle/working/submission_best_local_blend.parquet
/kaggle/working/submission.parquet

Files in /kaggle/working:
['submission_best_local_blend.parquet', 'lag_baseline.parquet', 'submission.parquet', 'xgb_corrected_laglabel.parquet', '.virtual_documents']

In [18]:
# ============================================================
# Target-Specific Safe XGBoost Model
# Inspired by winner-style target-pair modeling
# NO negative lags, NO leakage
# ============================================================

import os
import gc
import time
import warnings
import numpy as np
import pandas as pd

from xgboost import XGBRegressor

warnings.filterwarnings("ignore", category=pd.errors.PerformanceWarning)
warnings.filterwarnings("ignore", category=FutureWarning)

SOLUTION_NULL_FILLER = -999999

competition_data_path = "/kaggle/input/competitions/mitsui-commodity-prediction-challenge"
ground_truth_path = "/kaggle/input/datasets/stephenweiler208/ground-truth"


# ============================================================
# 1. Load / confirm ground truth
# ============================================================

if os.path.isdir(ground_truth_path):
    csv_files = [f for f in os.listdir(ground_truth_path) if f.endswith(".csv")]
    if len(csv_files) == 0:
        raise FileNotFoundError("No CSV found in ground truth folder.")
    ground_truth_path = os.path.join(ground_truth_path, csv_files[0])

solution = pd.read_csv(ground_truth_path)

local_test_start = solution["date_id"].min()
local_test_end = solution["date_id"].max()

print("Ground truth shape:", solution.shape)
print("Ground truth date range:", local_test_start, "to", local_test_end)


# ============================================================
# 2. Target metadata
# ============================================================

target_pairs = pd.read_csv(f"{competition_data_path}/target_pairs.csv")
target_cols = target_pairs["target"].tolist()
target_lag_map = target_pairs.set_index("target")["lag"].to_dict()
target_pair_map = target_pairs.set_index("target")["pair"].to_dict()

print("Number of targets:", len(target_cols))
display(target_pairs.head())


# ============================================================
# 3. Metric functions
# ============================================================

def rank_correlation_sharpe_ratio(merged_df: pd.DataFrame) -> float:
    prediction_cols = [col for col in merged_df.columns if col.startswith("prediction_")]
    target_cols_metric = [col for col in merged_df.columns if col.startswith("target_")]

    daily_rank_corrs = []

    for _, row in merged_df.iterrows():
        non_null_targets = [col for col in target_cols_metric if not pd.isnull(row[col])]

        matching_predictions = [
            col for col in prediction_cols
            if col.replace("prediction", "target") in non_null_targets
        ]

        if len(non_null_targets) < 3:
            daily_rank_corrs.append(np.nan)
            continue

        if row[non_null_targets].std(ddof=0) == 0 or row[matching_predictions].std(ddof=0) == 0:
            daily_rank_corrs.append(np.nan)
            continue

        corr = np.corrcoef(
            row[matching_predictions].rank(method="average"),
            row[non_null_targets].rank(method="average")
        )[0, 1]

        daily_rank_corrs.append(corr)

    daily_rank_corrs = pd.Series(daily_rank_corrs).dropna()
    std_dev = daily_rank_corrs.std(ddof=0)

    if std_dev == 0:
        raise ZeroDivisionError("Denominator is zero, unable to compute Sharpe ratio.")

    print("\nDaily rank correlation summary:")
    display(daily_rank_corrs.describe())
    print("Mean daily rank correlation:", daily_rank_corrs.mean())
    print("Std daily rank correlation:", std_dev)

    return float(daily_rank_corrs.mean() / std_dev)


def score(solution: pd.DataFrame, submission: pd.DataFrame, row_id_column_name: str) -> float:
    solution = solution.copy()
    submission = submission.copy()

    del solution[row_id_column_name]
    del submission[row_id_column_name]

    assert all(solution.columns == submission.columns), "Solution and submission columns do not match."

    submission = submission.rename(
        columns={col: col.replace("target_", "prediction_") for col in submission.columns}
    )

    solution = solution.replace(SOLUTION_NULL_FILLER, None)

    merged = pd.concat([solution, submission], axis="columns")

    return rank_correlation_sharpe_ratio(merged)


def evaluate_submission(submission_df, solution_df, target_cols, name="model"):
    solution_eval = solution_df[["date_id"] + target_cols].copy()
    submission_eval = submission_df[["date_id"] + target_cols].copy()

    solution_eval = solution_eval.sort_values("date_id").reset_index(drop=True)
    submission_eval = submission_eval.sort_values("date_id").reset_index(drop=True)

    print("\n" + "=" * 70)
    print(f"Evaluating: {name}")
    print("=" * 70)
    print("Date IDs match:", list(solution_eval["date_id"]) == list(submission_eval["date_id"]))
    print("Columns match:", list(solution_eval.columns) == list(submission_eval.columns))

    model_score = score(
        solution=solution_eval,
        submission=submission_eval,
        row_id_column_name="date_id"
    )

    print(f"\n{name} score:", model_score)
    return model_score


# ============================================================
# 4. Helper functions for target-specific features
# ============================================================

def parse_pair_columns(pair_string):
    """
    Converts target_pairs pair strings into component column names.
    Examples:
    'US_Stock_VT_adj_close' -> ['US_Stock_VT_adj_close']
    'LME_PB_Close - US_Stock_VT_adj_close' -> ['LME_PB_Close', 'US_Stock_VT_adj_close']
    """
    if pd.isna(pair_string):
        return []

    return [p.strip() for p in str(pair_string).split(" - ")]


def safe_existing_columns(cols, train_df, test_df):
    """
    Keep only columns that exist in both train and test.
    """
    return [c for c in cols if c in train_df.columns and c in test_df.columns]


def build_target_specific_features(target):
    """
    Build safe target-specific features for one target.

    Features:
    - Pair asset raw values
    - Safe lags: 1, 2, 3, 5, 10
    - Safe rolling means/stds using shift(1)
    - Safe diffs: current - previous values
    - Pair spread features if target pair has two assets
    - Corrected lag-label feature using shift(lag + 1) for train
    """

    pair_string = target_pair_map[target]
    pair_cols = parse_pair_columns(pair_string)
    pair_cols = safe_existing_columns(pair_cols, train, test)

    # Fallback if pair cols are missing: use a small set of broad clean features
    if len(pair_cols) == 0:
        pair_cols = clean_feature_cols[:30]

    # Add a few broad market features so the model has context
    # Keep this small to avoid noisy huge feature sets.
    broad_context_cols = clean_feature_cols[:50]

    selected_cols = list(dict.fromkeys(pair_cols + broad_context_cols))

    combined = pd.concat(
        [
            train[["date_id"] + selected_cols],
            test[["date_id"] + selected_cols]
        ],
        axis=0,
        ignore_index=True
    ).sort_values("date_id").reset_index(drop=True)

    feature_frames = []

    # Raw selected columns
    raw_features = combined[selected_cols].copy()
    feature_frames.append(raw_features)

    # Safe lags and rolling features
    lags = [1, 2, 3, 5, 10]
    windows = [3, 5, 10, 20]
    diffs = [1, 2, 5]

    lag_dict = {}

    for col in selected_cols:
        for lag in lags:
            lag_dict[f"{col}_lag_{lag}"] = combined[col].shift(lag)

        shifted = combined[col].shift(1)

        for window in windows:
            lag_dict[f"{col}_roll_mean_{window}"] = shifted.rolling(window).mean()
            lag_dict[f"{col}_roll_std_{window}"] = shifted.rolling(window).std()

        for diff in diffs:
            lag_dict[f"{col}_diff_{diff}"] = combined[col].diff(diff)

    engineered = pd.DataFrame(lag_dict)
    feature_frames.append(engineered)

    # Pair spread features if two valid pair columns exist
    if len(pair_cols) == 2:
        a, b = pair_cols
        spread = combined[a] - combined[b]

        spread_dict = {
            f"{target}_spread": spread,
            f"{target}_spread_lag_1": spread.shift(1),
            f"{target}_spread_lag_2": spread.shift(2),
            f"{target}_spread_lag_3": spread.shift(3),
            f"{target}_spread_lag_5": spread.shift(5),
            f"{target}_spread_diff_1": spread.diff(1),
            f"{target}_spread_diff_2": spread.diff(2),
            f"{target}_spread_roll_mean_5": spread.shift(1).rolling(5).mean(),
            f"{target}_spread_roll_std_5": spread.shift(1).rolling(5).std(),
            f"{target}_spread_roll_mean_10": spread.shift(1).rolling(10).mean(),
            f"{target}_spread_roll_std_10": spread.shift(1).rolling(10).std(),
        }

        feature_frames.append(pd.DataFrame(spread_dict))

    # Combine features
    combined_features = pd.concat(feature_frames, axis=1)
    combined_features = combined_features.replace([np.inf, -np.inf], np.nan).copy()

    # Add date_id back
    combined_features.insert(0, "date_id", combined["date_id"].values)

    # Split train/test
    train_target_features = combined_features.iloc[:len(train)].copy()
    test_target_features = combined_features.iloc[len(train):].copy()

    # Add corrected lag-label feature for this target
    target_lag = int(target_lag_map[target])

    train_target_features[f"lag_label_{target}"] = train_labels[target].shift(target_lag + 1).values

    # For test, pull from correct lag file
    lag_file = f"{competition_data_path}/lagged_test_labels/test_labels_lag_{target_lag}.csv"
    lag_df = pd.read_csv(lag_file)

    if target in lag_df.columns:
        test_lag_feature = lag_df[["date_id", target]].copy()
        test_lag_feature = test_lag_feature.rename(columns={target: f"lag_label_{target}"})

        test_target_features = test_target_features.merge(
            test_lag_feature,
            on="date_id",
            how="left"
        )
    else:
        test_target_features[f"lag_label_{target}"] = np.nan

    # Final feature columns
    target_feature_cols = [c for c in train_target_features.columns if c != "date_id"]

    X_train_target_all = train_target_features[target_feature_cols]
    X_test_target = test_target_features[target_feature_cols]

    return X_train_target_all, X_test_target


# ============================================================
# 5. Train target-specific XGBoost models
# ============================================================

train_nonleaky_mask = train["date_id"] < local_test_start

pair_model_params = {
    "n_estimators": 250,
    "learning_rate": 0.04,
    "max_depth": 2,
    "subsample": 0.9,
    "colsample_bytree": 0.85,
    "reg_alpha": 0.05,
    "reg_lambda": 4.0,
    "min_child_weight": 4,
}

submission_pair_xgb = pd.DataFrame(index=test.index)

start_time = time.time()

for i, target in enumerate(target_cols):
    print(f"\nTraining target-specific model {i + 1}/{len(target_cols)}: {target}")

    X_train_target_all, X_test_target = build_target_specific_features(target)

    X_train_target = X_train_target_all.loc[train_nonleaky_mask]

    y_train = train_labels.loc[train_nonleaky_mask, target].values
    target_mask = ~np.isnan(y_train)

    if target_mask.sum() < 100:
        print(f"Skipping {target}: not enough non-missing labels.")
        submission_pair_xgb[target] = 0.0
        continue

    model = XGBRegressor(
        **pair_model_params,
        objective="reg:squarederror",
        tree_method="hist",
        random_state=42,
        n_jobs=-1,
        eval_metric="rmse"
    )

    model.fit(
        X_train_target.loc[target_mask],
        y_train[target_mask],
        verbose=False
    )

    submission_pair_xgb[target] = model.predict(X_test_target)

    if (i + 1) % 25 == 0:
        elapsed = (time.time() - start_time) / 60
        print("\n" + "-" * 60)
        print(f"Finished {i + 1}/{len(target_cols)} targets in {elapsed:.2f} minutes")
        print("-" * 60)

    del model, X_train_target_all, X_train_target, X_test_target
    gc.collect()

submission_pair_xgb.insert(0, "date_id", test["date_id"].values)
submission_pair_xgb = submission_pair_xgb[["date_id"] + target_cols].copy()

print("\nTarget-specific XGBoost prediction shape:", submission_pair_xgb.shape)
display(submission_pair_xgb.head())

submission_pair_xgb.to_parquet("/kaggle/working/pair_specific_xgb.parquet", index=False)


# ============================================================
# 6. Evaluate target-specific model
# ============================================================

pair_xgb_score = evaluate_submission(
    submission_pair_xgb,
    solution,
    target_cols,
    name="Target-specific safe XGBoost"
)

print("\nTarget-specific XGBoost score:")
print(pair_xgb_score)


# ============================================================
# 7. Optional blend with existing XGBoost result if available
# ============================================================
# This assumes you have a previous strong XGBoost prediction DataFrame called submission_xgb.
# If you do not have it in memory, this section will skip.

if "submission_xgb" in globals():
    print("\nFound existing submission_xgb. Running rank blend...")

    xgb_eval = submission_xgb.sort_values("date_id").reset_index(drop=True)
    pair_eval = submission_pair_xgb.sort_values("date_id").reset_index(drop=True)

    xgb_rank = xgb_eval[target_cols].rank(axis=1, method="average", ascending=True)
    pair_rank = pair_eval[target_cols].rank(axis=1, method="average", ascending=True)

    blend_scores = {}
    blend_submissions = {}

    for w_xgb in [0.10, 0.20, 0.30, 0.40, 0.50, 0.60, 0.70, 0.80, 0.90]:
        w_pair = 1.0 - w_xgb

        blended_values = (w_xgb * xgb_rank) + (w_pair * pair_rank)

        blended_submission = blended_values.copy()
        blended_submission.insert(0, "date_id", xgb_eval["date_id"].values)
        blended_submission = blended_submission[["date_id"] + target_cols].copy()

        blend_name = f"oldxgb_{w_xgb:.2f}_pairxgb_{w_pair:.2f}"

        blend_score = evaluate_submission(
            blended_submission,
            solution,
            target_cols,
            name=blend_name
        )

        blend_scores[blend_name] = blend_score
        blend_submissions[blend_name] = blended_submission

    blend_scores_series = pd.Series(blend_scores).sort_values(ascending=False)

    print("\n" + "=" * 70)
    print("Blend results: old XGBoost + target-specific XGBoost")
    print("=" * 70)
    display(blend_scores_series)

    best_blend_name = blend_scores_series.index[0]
    best_blend_submission = blend_submissions[best_blend_name]

    print("Best blend:", best_blend_name)
    print("Best blend score:", blend_scores_series.iloc[0])

    best_blend_submission.to_parquet("/kaggle/working/submission_pair_blend.parquet", index=False)
    best_blend_submission.to_parquet("/kaggle/working/submission.parquet", index=False)

else:
    print("\nNo existing submission_xgb found in memory.")
    print("Saving pair-specific XGBoost as submission.parquet.")
    submission_pair_xgb.to_parquet("/kaggle/working/submission.parquet", index=False)


print("\nFiles in /kaggle/working:")
print(os.listdir("/kaggle/working"))

Ground truth shape: (134, 425)
Ground truth date range: 1827 to 1960
Number of targets: 424

     target  lag                                            pair
0  target_0    1                           US_Stock_VT_adj_close
1  target_1    1            LME_PB_Close - US_Stock_VT_adj_close
2  target_2    1                     LME_CA_Close - LME_ZS_Close
3  target_3    1                     LME_AH_Close - LME_ZS_Close
4  target_4    1  LME_AH_Close - JPX_Gold_Standard_Futures_Close

Training target-specific model 1/424: target_0

Training target-specific model 2/424: target_1

Training target-specific model 3/424: target_2

Training target-specific model 4/424: target_3

Training target-specific model 5/424: target_4

Training target-specific model 6/424: target_5

Training target-specific model 7/424: target_6

Training target-specific model 8/424: target_7

Training target-specific model 9/424: target_8

Training target-specific model 10/424: target_9

Training target-specific model 11/424: target_10

Training target-specific model 12/424: target_11

Training target-specific model 13/424: target_12

Training target-specific model 14/424: target_13

Training target-specific model 15/424: target_14

Training target-specific model 16/424: target_15

Training target-specific model 17/424: target_16

Training target-specific model 18/424: target_17

Training target-specific model 19/424: target_18

Training target-specific model 20/424: target_19

Training target-specific model 21/424: target_20

Training target-specific model 22/424: target_21

Training target-specific model 23/424: target_22

Training target-specific model 24/424: target_23

Training target-specific model 25/424: target_24

------------------------------------------------------------
Finished 25/424 targets in 2.38 minutes
------------------------------------------------------------

Training target-specific model 26/424: target_25

Training target-specific model 27/424: target_26

Training target-specific model 28/424: target_27

Training target-specific model 29/424: target_28

Training target-specific model 30/424: target_29

Training target-specific model 31/424: target_30

Training target-specific model 32/424: target_31

Training target-specific model 33/424: target_32

Training target-specific model 34/424: target_33

Training target-specific model 35/424: target_34

Training target-specific model 36/424: target_35

Training target-specific model 37/424: target_36

Training target-specific model 38/424: target_37

Training target-specific model 39/424: target_38

Training target-specific model 40/424: target_39

Training target-specific model 41/424: target_40

Training target-specific model 42/424: target_41

Training target-specific model 43/424: target_42

Training target-specific model 44/424: target_43

Training target-specific model 45/424: target_44

Training target-specific model 46/424: target_45

Training target-specific model 47/424: target_46

Training target-specific model 48/424: target_47

Training target-specific model 49/424: target_48

Training target-specific model 50/424: target_49

------------------------------------------------------------
Finished 50/424 targets in 4.91 minutes
------------------------------------------------------------

Training target-specific model 51/424: target_50

Training target-specific model 52/424: target_51

Training target-specific model 53/424: target_52

Training target-specific model 54/424: target_53

Training target-specific model 55/424: target_54

Training target-specific model 56/424: target_55

Training target-specific model 57/424: target_56

Training target-specific model 58/424: target_57

Training target-specific model 59/424: target_58

Training target-specific model 60/424: target_59

Training target-specific model 61/424: target_60

Training target-specific model 62/424: target_61

Training target-specific model 63/424: target_62

Training target-specific model 64/424: target_63

Training target-specific model 65/424: target_64

Training target-specific model 66/424: target_65

Training target-specific model 67/424: target_66

Training target-specific model 68/424: target_67

Training target-specific model 69/424: target_68

Training target-specific model 70/424: target_69

Training target-specific model 71/424: target_70

Training target-specific model 72/424: target_71

Training target-specific model 73/424: target_72

Training target-specific model 74/424: target_73

Training target-specific model 75/424: target_74

------------------------------------------------------------
Finished 75/424 targets in 7.36 minutes
------------------------------------------------------------

Training target-specific model 76/424: target_75

Training target-specific model 77/424: target_76

Training target-specific model 78/424: target_77

Training target-specific model 79/424: target_78

Training target-specific model 80/424: target_79

Training target-specific model 81/424: target_80

Training target-specific model 82/424: target_81

Training target-specific model 83/424: target_82

Training target-specific model 84/424: target_83

Training target-specific model 85/424: target_84

Training target-specific model 86/424: target_85

Training target-specific model 87/424: target_86

Training target-specific model 88/424: target_87

Training target-specific model 89/424: target_88

Training target-specific model 90/424: target_89

Training target-specific model 91/424: target_90

Training target-specific model 92/424: target_91

Training target-specific model 93/424: target_92

Training target-specific model 94/424: target_93

Training target-specific model 95/424: target_94

Training target-specific model 96/424: target_95

Training target-specific model 97/424: target_96

Training target-specific model 98/424: target_97

Training target-specific model 99/424: target_98

Training target-specific model 100/424: target_99

------------------------------------------------------------
Finished 100/424 targets in 10.05 minutes
------------------------------------------------------------

Training target-specific model 101/424: target_100

Training target-specific model 102/424: target_101

Training target-specific model 103/424: target_102

Training target-specific model 104/424: target_103

Training target-specific model 105/424: target_104

Training target-specific model 106/424: target_105

Training target-specific model 107/424: target_106

Training target-specific model 108/424: target_107

Training target-specific model 109/424: target_108

Training target-specific model 110/424: target_109

Training target-specific model 111/424: target_110

Training target-specific model 112/424: target_111

Training target-specific model 113/424: target_112

Training target-specific model 114/424: target_113

Training target-specific model 115/424: target_114

Training target-specific model 116/424: target_115

Training target-specific model 117/424: target_116

Training target-specific model 118/424: target_117

Training target-specific model 119/424: target_118

Training target-specific model 120/424: target_119

Training target-specific model 121/424: target_120

Training target-specific model 122/424: target_121

Training target-specific model 123/424: target_122

Training target-specific model 124/424: target_123

Training target-specific model 125/424: target_124

------------------------------------------------------------
Finished 125/424 targets in 12.49 minutes
------------------------------------------------------------

Training target-specific model 126/424: target_125

Training target-specific model 127/424: target_126

Training target-specific model 128/424: target_127

Training target-specific model 129/424: target_128

Training target-specific model 130/424: target_129

Training target-specific model 131/424: target_130

Training target-specific model 132/424: target_131

Training target-specific model 133/424: target_132

Training target-specific model 134/424: target_133

Training target-specific model 135/424: target_134

Training target-specific model 136/424: target_135

Training target-specific model 137/424: target_136

Training target-specific model 138/424: target_137

Training target-specific model 139/424: target_138

Training target-specific model 140/424: target_139

Training target-specific model 141/424: target_140

Training target-specific model 142/424: target_141

Training target-specific model 143/424: target_142

Training target-specific model 144/424: target_143

Training target-specific model 145/424: target_144

Training target-specific model 146/424: target_145

Training target-specific model 147/424: target_146

Training target-specific model 148/424: target_147

Training target-specific model 149/424: target_148

Training target-specific model 150/424: target_149

------------------------------------------------------------
Finished 150/424 targets in 14.99 minutes
------------------------------------------------------------

Training target-specific model 151/424: target_150

Training target-specific model 152/424: target_151

Training target-specific model 153/424: target_152

Training target-specific model 154/424: target_153

Training target-specific model 155/424: target_154

Training target-specific model 156/424: target_155

Training target-specific model 157/424: target_156

Training target-specific model 158/424: target_157

Training target-specific model 159/424: target_158

Training target-specific model 160/424: target_159

Training target-specific model 161/424: target_160

Training target-specific model 162/424: target_161

Training target-specific model 163/424: target_162

Training target-specific model 164/424: target_163

Training target-specific model 165/424: target_164

Training target-specific model 166/424: target_165

Training target-specific model 167/424: target_166

Training target-specific model 168/424: target_167

Training target-specific model 169/424: target_168

Training target-specific model 170/424: target_169

Training target-specific model 171/424: target_170

Training target-specific model 172/424: target_171

Training target-specific model 173/424: target_172

Training target-specific model 174/424: target_173

Training target-specific model 175/424: target_174

------------------------------------------------------------
Finished 175/424 targets in 17.57 minutes
------------------------------------------------------------

Training target-specific model 176/424: target_175

Training target-specific model 177/424: target_176

Training target-specific model 178/424: target_177

Training target-specific model 179/424: target_178

Training target-specific model 180/424: target_179

Training target-specific model 181/424: target_180

Training target-specific model 182/424: target_181

Training target-specific model 183/424: target_182

Training target-specific model 184/424: target_183

Training target-specific model 185/424: target_184

Training target-specific model 186/424: target_185

Training target-specific model 187/424: target_186

Training target-specific model 188/424: target_187

Training target-specific model 189/424: target_188

Training target-specific model 190/424: target_189

Training target-specific model 191/424: target_190

Training target-specific model 192/424: target_191

Training target-specific model 193/424: target_192

Training target-specific model 194/424: target_193

Training target-specific model 195/424: target_194

Training target-specific model 196/424: target_195

Training target-specific model 197/424: target_196

Training target-specific model 198/424: target_197

Training target-specific model 199/424: target_198

Training target-specific model 200/424: target_199

------------------------------------------------------------
Finished 200/424 targets in 20.06 minutes
------------------------------------------------------------

Training target-specific model 201/424: target_200

Training target-specific model 202/424: target_201

Training target-specific model 203/424: target_202

Training target-specific model 204/424: target_203

Training target-specific model 205/424: target_204

Training target-specific model 206/424: target_205

Training target-specific model 207/424: target_206

Training target-specific model 208/424: target_207

Training target-specific model 209/424: target_208

Training target-specific model 210/424: target_209

Training target-specific model 211/424: target_210

Training target-specific model 212/424: target_211

Training target-specific model 213/424: target_212

Training target-specific model 214/424: target_213

Training target-specific model 215/424: target_214

Training target-specific model 216/424: target_215

Training target-specific model 217/424: target_216

Training target-specific model 218/424: target_217

Training target-specific model 219/424: target_218

Training target-specific model 220/424: target_219

Training target-specific model 221/424: target_220

Training target-specific model 222/424: target_221

Training target-specific model 223/424: target_222

Training target-specific model 224/424: target_223

Training target-specific model 225/424: target_224

------------------------------------------------------------
Finished 225/424 targets in 22.53 minutes
------------------------------------------------------------

Training target-specific model 226/424: target_225

Training target-specific model 227/424: target_226

Training target-specific model 228/424: target_227

Training target-specific model 229/424: target_228

Training target-specific model 230/424: target_229

Training target-specific model 231/424: target_230

Training target-specific model 232/424: target_231

Training target-specific model 233/424: target_232

Training target-specific model 234/424: target_233

Training target-specific model 235/424: target_234

Training target-specific model 236/424: target_235

Training target-specific model 237/424: target_236

Training target-specific model 238/424: target_237

Training target-specific model 239/424: target_238

Training target-specific model 240/424: target_239

Training target-specific model 241/424: target_240

Training target-specific model 242/424: target_241

Training target-specific model 243/424: target_242

Training target-specific model 244/424: target_243

Training target-specific model 245/424: target_244

Training target-specific model 246/424: target_245

Training target-specific model 247/424: target_246

Training target-specific model 248/424: target_247

Training target-specific model 249/424: target_248

Training target-specific model 250/424: target_249

------------------------------------------------------------
Finished 250/424 targets in 25.18 minutes
------------------------------------------------------------

Training target-specific model 251/424: target_250

Training target-specific model 252/424: target_251

Training target-specific model 253/424: target_252

Training target-specific model 254/424: target_253

Training target-specific model 255/424: target_254

Training target-specific model 256/424: target_255

Training target-specific model 257/424: target_256

Training target-specific model 258/424: target_257

Training target-specific model 259/424: target_258

Training target-specific model 260/424: target_259

Training target-specific model 261/424: target_260

Training target-specific model 262/424: target_261

Training target-specific model 263/424: target_262

Training target-specific model 264/424: target_263

Training target-specific model 265/424: target_264

Training target-specific model 266/424: target_265

Training target-specific model 267/424: target_266

Training target-specific model 268/424: target_267

Training target-specific model 269/424: target_268

Training target-specific model 270/424: target_269

Training target-specific model 271/424: target_270

Training target-specific model 272/424: target_271

Training target-specific model 273/424: target_272

Training target-specific model 274/424: target_273

Training target-specific model 275/424: target_274

------------------------------------------------------------
Finished 275/424 targets in 27.77 minutes
------------------------------------------------------------

Training target-specific model 276/424: target_275

Training target-specific model 277/424: target_276

Training target-specific model 278/424: target_277

Training target-specific model 279/424: target_278

Training target-specific model 280/424: target_279

Training target-specific model 281/424: target_280

Training target-specific model 282/424: target_281

Training target-specific model 283/424: target_282

Training target-specific model 284/424: target_283

Training target-specific model 285/424: target_284

Training target-specific model 286/424: target_285

Training target-specific model 287/424: target_286

Training target-specific model 288/424: target_287

Training target-specific model 289/424: target_288

Training target-specific model 290/424: target_289

Training target-specific model 291/424: target_290

Training target-specific model 292/424: target_291

Training target-specific model 293/424: target_292

Training target-specific model 294/424: target_293

Training target-specific model 295/424: target_294

Training target-specific model 296/424: target_295

Training target-specific model 297/424: target_296

Training target-specific model 298/424: target_297

Training target-specific model 299/424: target_298

Training target-specific model 300/424: target_299

------------------------------------------------------------
Finished 300/424 targets in 30.34 minutes
------------------------------------------------------------

Training target-specific model 301/424: target_300

Training target-specific model 302/424: target_301

Training target-specific model 303/424: target_302

Training target-specific model 304/424: target_303

Training target-specific model 305/424: target_304

Training target-specific model 306/424: target_305

Training target-specific model 307/424: target_306

Training target-specific model 308/424: target_307

Training target-specific model 309/424: target_308

Training target-specific model 310/424: target_309

Training target-specific model 311/424: target_310

Training target-specific model 312/424: target_311

Training target-specific model 313/424: target_312

Training target-specific model 314/424: target_313

Training target-specific model 315/424: target_314

Training target-specific model 316/424: target_315

Training target-specific model 317/424: target_316

Training target-specific model 318/424: target_317

Training target-specific model 319/424: target_318

Training target-specific model 320/424: target_319

Training target-specific model 321/424: target_320

Training target-specific model 322/424: target_321

Training target-specific model 323/424: target_322

Training target-specific model 324/424: target_323

Training target-specific model 325/424: target_324

------------------------------------------------------------
Finished 325/424 targets in 32.86 minutes
------------------------------------------------------------

Training target-specific model 326/424: target_325

Training target-specific model 327/424: target_326

Training target-specific model 328/424: target_327

Training target-specific model 329/424: target_328

Training target-specific model 330/424: target_329

Training target-specific model 331/424: target_330

Training target-specific model 332/424: target_331

Training target-specific model 333/424: target_332

Training target-specific model 334/424: target_333

Training target-specific model 335/424: target_334

Training target-specific model 336/424: target_335

Training target-specific model 337/424: target_336

Training target-specific model 338/424: target_337

Training target-specific model 339/424: target_338

Training target-specific model 340/424: target_339

Training target-specific model 341/424: target_340

Training target-specific model 342/424: target_341

Training target-specific model 343/424: target_342

Training target-specific model 344/424: target_343

Training target-specific model 345/424: target_344

Training target-specific model 346/424: target_345

Training target-specific model 347/424: target_346


,date_id,target_0,target_1,target_2,target_3,target_4,target_5,target_6,target_7,target_8,...,target_414,target_415,target_416,target_417,target_418,target_419,target_420,target_421,target_422,target_423
0,1827,-0.000672,0.000621,-0.001337,-0.001702,-0.000192,0.001441,-0.002319,-0.001913,0.000058,...,0.002144,0.000793,0.005017,0.016076,0.008261,0.005367,0.013486,0.004694,0.011556,0.005934
1,1828,-0.000204,0.003290,0.001647,-0.000836,0.000218,0.000832,0.003455,0.003098,0.001333,...,0.005494,-0.000650,0.009211,0.018788,0.005529,0.001271,0.019775,0.008731,0.008379,0.007897
2,1829,-0.006396,0.006178,0.000970,-0.000477,-0.002327,-0.006177,0.002066,0.000475,-0.001401,...,0.004935,-0.001149,0.005106,0.018742,0.008616,0.010143,0.015526,0.011140,0.007980,0.014975
3,1830,-0.003574,0.003073,0.002299,0.000656,-0.000126,-0.002431,0.004850,0.002418,-0.002603,...,0.000214,0.000089,0.004717,0.011832,0.011153,0.010883,0.009186,0.006577,0.001481,0.010408
4,1831,0.001139,-0.001219,-0.000121,0.000323,0.000216,0.002006,0.004261,0.001883,0.003240,...,-0.002149,0.001743,0.000325,-0.004024,0.008695,0.005385,0.008530,0.000737,-0.001654,0.012660

======================================================================
Evaluating: Target-specific safe XGBoost
======================================================================
Date IDs match: True
Columns match: True

Daily rank correlation summary:

count    134.000000
mean      -0.022844
std        0.167513
min       -0.529537
25%       -0.139058
50%       -0.018377
75%        0.076538
max        0.456914
dtype: float64

Mean daily rank correlation: -0.022844269744739833
Std daily rank correlation: 0.16688634785424816

Target-specific safe XGBoost score: -0.13688519185937906

Target-specific XGBoost score:
-0.13688519185937906

Found existing submission_xgb. Running rank blend...

======================================================================
Evaluating: oldxgb_0.10_pairxgb_0.90
======================================================================
Date IDs match: True
Columns match: True

Daily rank correlation summary:

count    134.000000
mean      -0.020001
std        0.167386
min       -0.507635
25%       -0.132745
50%       -0.012075
75%        0.086723
max        0.460975
dtype: float64

Mean daily rank correlation: -0.020000631511838566
Std daily rank correlation: 0.16676069231869936

oldxgb_0.10_pairxgb_0.90 score: -0.11993612663597605

======================================================================
Evaluating: oldxgb_0.20_pairxgb_0.80
======================================================================
Date IDs match: True
Columns match: True

Daily rank correlation summary:

count    134.000000
mean      -0.016810
std        0.168309
min       -0.471743
25%       -0.127060
50%       -0.022497
75%        0.086349
max        0.477845
dtype: float64

Mean daily rank correlation: -0.01680954878555493
Std daily rank correlation: 0.16767991186005504

oldxgb_0.20_pairxgb_0.80 score: -0.10024783886804586

======================================================================
Evaluating: oldxgb_0.30_pairxgb_0.70
======================================================================
Date IDs match: True
Columns match: True

Daily rank correlation summary:

count    134.000000
mean      -0.012515
std        0.169860
min       -0.426583
25%       -0.115266
50%       -0.018275
75%        0.097125
max        0.546040
dtype: float64

Mean daily rank correlation: -0.012515077972761652
Std daily rank correlation: 0.16922490238495178

oldxgb_0.30_pairxgb_0.70 score: -0.07395529733734121

======================================================================
Evaluating: oldxgb_0.40_pairxgb_0.60
======================================================================
Date IDs match: True
Columns match: True

Daily rank correlation summary:

count    134.000000
mean      -0.006651
std        0.171588
min       -0.408252
25%       -0.116657
50%       -0.013882
75%        0.096223
max        0.610009
dtype: float64

Mean daily rank correlation: -0.006650924488833983
Std daily rank correlation: 0.17094647522633985

oldxgb_0.40_pairxgb_0.60 score: -0.038906473386057815

======================================================================
Evaluating: oldxgb_0.50_pairxgb_0.50
======================================================================
Date IDs match: True
Columns match: True

Daily rank correlation summary:

count    134.000000
mean       0.000169
std        0.174262
min       -0.363388
25%       -0.129928
50%       -0.005815
75%        0.100941
max        0.665813
dtype: float64

Mean daily rank correlation: 0.00016883105099347342
Std daily rank correlation: 0.1736106203588907

oldxgb_0.50_pairxgb_0.50 score: 0.0009724696026341196

======================================================================
Evaluating: oldxgb_0.60_pairxgb_0.40
======================================================================
Date IDs match: True
Columns match: True

Daily rank correlation summary:

count    134.000000
mean       0.006883
std        0.177001
min       -0.333327
25%       -0.127909
50%       -0.005724
75%        0.127366
max        0.703860
dtype: float64

Mean daily rank correlation: 0.0068827476925378325
Std daily rank correlation: 0.17633980399548047

oldxgb_0.60_pairxgb_0.40 score: 0.039031163336862025

======================================================================
Evaluating: oldxgb_0.70_pairxgb_0.30
======================================================================
Date IDs match: True
Columns match: True

Daily rank correlation summary:

count    134.000000
mean       0.012288
std        0.179705
min       -0.326888
25%       -0.119977
50%        0.008037
75%        0.132228
max        0.731017
dtype: float64

Mean daily rank correlation: 0.012287712344369716
Std daily rank correlation: 0.17903361538013265

oldxgb_0.70_pairxgb_0.30 score: 0.06863354861197359

======================================================================
Evaluating: oldxgb_0.80_pairxgb_0.20
======================================================================
Date IDs match: True
Columns match: True

Daily rank correlation summary:

count    134.000000
mean       0.016880
std        0.182429
min       -0.372839
25%       -0.114853
50%        0.008623
75%        0.133014
max        0.746967
dtype: float64

Mean daily rank correlation: 0.01688030571115678
Std daily rank correlation: 0.18174670787109865

oldxgb_0.80_pairxgb_0.20 score: 0.09287819245193099

======================================================================
Evaluating: oldxgb_0.90_pairxgb_0.10
======================================================================
Date IDs match: True
Columns match: True

Daily rank correlation summary:

count    134.000000
mean       0.020099
std        0.184082
min       -0.409242
25%       -0.116017
50%        0.019404
75%        0.150780
max        0.746125
dtype: float64

Mean daily rank correlation: 0.02009871965033043
Std daily rank correlation: 0.1833942305537299

oldxgb_0.90_pairxgb_0.10 score: 0.10959297677819811

======================================================================
Blend results: old XGBoost + target-specific XGBoost
======================================================================

oldxgb_0.90_pairxgb_0.10    0.109593
oldxgb_0.80_pairxgb_0.20    0.092878
oldxgb_0.70_pairxgb_0.30    0.068634
oldxgb_0.60_pairxgb_0.40    0.039031
oldxgb_0.50_pairxgb_0.50    0.000972
oldxgb_0.40_pairxgb_0.60   -0.038906
oldxgb_0.30_pairxgb_0.70   -0.073955
oldxgb_0.20_pairxgb_0.80   -0.100248
oldxgb_0.10_pairxgb_0.90   -0.119936
dtype: float64

Best blend: oldxgb_0.90_pairxgb_0.10
Best blend score: 0.10959297677819811

Files in /kaggle/working:
['submission_best_local_blend.parquet', 'lag_baseline.parquet', 'submission.parquet', 'submission_pair_blend.parquet', 'xgb_corrected_laglabel.parquet', '.virtual_documents', 'pair_specific_xgb.parquet']

In [19]:
# ============================================================
# LightGBM Setup: Non-Leaky + Corrected Lag Label Features
# Trains 424 target models and blends with existing XGBoost
# ============================================================

import os
import gc
import time
import warnings
import numpy as np
import pandas as pd

warnings.filterwarnings("ignore", category=pd.errors.PerformanceWarning)
warnings.filterwarnings("ignore", category=FutureWarning)

from lightgbm import LGBMRegressor

SOLUTION_NULL_FILLER = -999999

competition_data_path = "/kaggle/input/competitions/mitsui-commodity-prediction-challenge"
ground_truth_path = "/kaggle/input/datasets/stephenweiler208/ground-truth"

# ============================================================
# 1. Load ground truth
# ============================================================

if os.path.isdir(ground_truth_path):
    csv_files = [f for f in os.listdir(ground_truth_path) if f.endswith(".csv")]
    if len(csv_files) == 0:
        raise FileNotFoundError("No CSV found in ground truth folder.")
    ground_truth_path = os.path.join(ground_truth_path, csv_files[0])

solution = pd.read_csv(ground_truth_path)

local_test_start = solution["date_id"].min()
local_test_end = solution["date_id"].max()

print("Ground truth shape:", solution.shape)
print("Ground truth date range:", local_test_start, "to", local_test_end)

# ============================================================
# 2. Target metadata
# ============================================================

target_pairs = pd.read_csv(f"{competition_data_path}/target_pairs.csv")
target_cols = target_pairs["target"].tolist()
target_lag_map = target_pairs.set_index("target")["lag"].to_dict()

print("Number of targets:", len(target_cols))
display(target_pairs.head())

# ============================================================
# 3. Clean base features
# ============================================================

id_cols = ["date_id"]
feature_cols = [c for c in train.columns if c not in id_cols]

feature_missing_rate = train[feature_cols].isna().mean()
clean_feature_cols = feature_missing_rate[feature_missing_rate <= 0.50].index.tolist()

print("Original feature count:", len(feature_cols))
print("Clean feature count:", len(clean_feature_cols))

# ============================================================
# 4. Build corrected lag-label features for TRAIN
# No fragmentation: dictionary -> DataFrame
# ============================================================

lag_feature_dict = {}

for target in target_cols:
    lag = int(target_lag_map[target])
    lag_feature_dict[f"lag_label_{target}"] = train_labels[target].shift(lag + 1)

train_label_lag_features = pd.DataFrame(lag_feature_dict)
train_label_lag_features.insert(0, "date_id", train_labels["date_id"].values)
train_label_lag_features = train_label_lag_features.copy()

print("Train lag-label feature shape:", train_label_lag_features.shape)
display(train_label_lag_features.head())

# ============================================================
# 5. Build lag-label features for TEST
# ============================================================

test_label_lag_features = pd.DataFrame({"date_id": test["date_id"].values})

for lag in [1, 2, 3, 4]:
    lag_df = pd.read_csv(
        f"{competition_data_path}/lagged_test_labels/test_labels_lag_{lag}.csv"
    )

    lag_targets = target_pairs.loc[target_pairs["lag"] == lag, "target"].tolist()
    available_targets = [c for c in lag_targets if c in lag_df.columns]

    temp = lag_df[["date_id"] + available_targets].copy()
    temp = temp.rename(columns={c: f"lag_label_{c}" for c in available_targets})

    test_label_lag_features = test_label_lag_features.merge(
        temp,
        on="date_id",
        how="left"
    )

test_label_lag_features = test_label_lag_features.copy()

print("Test lag-label feature shape:", test_label_lag_features.shape)
display(test_label_lag_features.head())

# ============================================================
# 6. Build final feature matrices
# ============================================================

train_features_lgbm = train[["date_id"] + clean_feature_cols].merge(
    train_label_lag_features,
    on="date_id",
    how="left"
)

test_features_lgbm = test[["date_id"] + clean_feature_cols].merge(
    test_label_lag_features,
    on="date_id",
    how="left"
)

train_features_lgbm = train_features_lgbm.replace([np.inf, -np.inf], np.nan).copy()
test_features_lgbm = test_features_lgbm.replace([np.inf, -np.inf], np.nan).copy()

lgbm_feature_cols = [c for c in train_features_lgbm.columns if c != "date_id"]

train_nonleaky_mask = train_features_lgbm["date_id"] < local_test_start

X_train_lgbm = train_features_lgbm.loc[train_nonleaky_mask, lgbm_feature_cols].copy()
X_test_lgbm = test_features_lgbm[lgbm_feature_cols].copy()

print("LightGBM feature count:", len(lgbm_feature_cols))
print("Non-leaky training rows:", X_train_lgbm.shape)
print("Local test rows:", X_test_lgbm.shape)
print(
    "Training date range:",
    train_features_lgbm.loc[train_nonleaky_mask, "date_id"].min(),
    "to",
    train_features_lgbm.loc[train_nonleaky_mask, "date_id"].max()
)

# ============================================================
# 7. Metric functions
# ============================================================

def rank_correlation_sharpe_ratio(merged_df: pd.DataFrame) -> float:
    prediction_cols = [col for col in merged_df.columns if col.startswith("prediction_")]
    target_cols_metric = [col for col in merged_df.columns if col.startswith("target_")]

    daily_rank_corrs = []

    for _, row in merged_df.iterrows():
        non_null_targets = [col for col in target_cols_metric if not pd.isnull(row[col])]

        matching_predictions = [
            col for col in prediction_cols
            if col.replace("prediction", "target") in non_null_targets
        ]

        if len(non_null_targets) < 3:
            daily_rank_corrs.append(np.nan)
            continue

        if row[non_null_targets].std(ddof=0) == 0 or row[matching_predictions].std(ddof=0) == 0:
            daily_rank_corrs.append(np.nan)
            continue

        corr = np.corrcoef(
            row[matching_predictions].rank(method="average"),
            row[non_null_targets].rank(method="average")
        )[0, 1]

        daily_rank_corrs.append(corr)

    daily_rank_corrs = pd.Series(daily_rank_corrs).dropna()

    std_dev = daily_rank_corrs.std(ddof=0)

    if std_dev == 0:
        raise ZeroDivisionError("Denominator is zero, unable to compute Sharpe ratio.")

    print("\nDaily rank correlation summary:")
    display(daily_rank_corrs.describe())

    print("\nMean daily rank correlation:", daily_rank_corrs.mean())
    print("Std daily rank correlation:", std_dev)

    return float(daily_rank_corrs.mean() / std_dev)


def score(solution: pd.DataFrame, submission: pd.DataFrame, row_id_column_name: str) -> float:
    solution = solution.copy()
    submission = submission.copy()

    del solution[row_id_column_name]
    del submission[row_id_column_name]

    assert all(solution.columns == submission.columns), "Solution and submission columns do not match."

    submission = submission.rename(
        columns={col: col.replace("target_", "prediction_") for col in submission.columns}
    )

    solution = solution.replace(SOLUTION_NULL_FILLER, None)

    merged = pd.concat([solution, submission], axis="columns")

    return rank_correlation_sharpe_ratio(merged)


def evaluate_submission(submission_df, solution_df, target_cols, name="model"):
    solution_eval = solution_df[["date_id"] + target_cols].copy()
    submission_eval = submission_df[["date_id"] + target_cols].copy()

    solution_eval = solution_eval.sort_values("date_id").reset_index(drop=True)
    submission_eval = submission_eval.sort_values("date_id").reset_index(drop=True)

    print("\n" + "=" * 70)
    print(f"Evaluating: {name}")
    print("=" * 70)
    print("Date IDs match:", list(solution_eval["date_id"]) == list(submission_eval["date_id"]))
    print("Columns match:", list(solution_eval.columns) == list(submission_eval.columns))

    model_score = score(
        solution=solution_eval,
        submission=submission_eval,
        row_id_column_name="date_id"
    )

    print(f"\n{name} score:", model_score)

    return model_score

# ============================================================
# 8. Train LightGBM models
# ============================================================

lgbm_params = {
    "n_estimators": 400,
    "learning_rate": 0.025,
    "max_depth": 2,
    "num_leaves": 7,
    "min_child_samples": 80,
    "subsample": 0.9,
    "subsample_freq": 1,
    "colsample_bytree": 0.8,
    "reg_alpha": 0.1,
    "reg_lambda": 5.0,
    "random_state": 42,
    "n_jobs": -1,
    "verbose": -1,
}

submission_lgbm = pd.DataFrame(index=test.index)

start_time = time.time()

for i, target in enumerate(target_cols):
    y_train = train_labels.loc[train_nonleaky_mask, target].values
    target_mask = ~np.isnan(y_train)

    if target_mask.sum() < 100:
        submission_lgbm[target] = 0.0
        continue

    model = LGBMRegressor(**lgbm_params)

    model.fit(
        X_train_lgbm.loc[target_mask],
        y_train[target_mask]
    )

    submission_lgbm[target] = model.predict(X_test_lgbm)

    if (i + 1) % 25 == 0:
        elapsed = (time.time() - start_time) / 60
        print(f"Finished {i + 1}/{len(target_cols)} LightGBM targets in {elapsed:.2f} minutes")

    del model
    gc.collect()

submission_lgbm.insert(0, "date_id", test["date_id"].values)
submission_lgbm = submission_lgbm[["date_id"] + target_cols].copy()

print("\nLightGBM prediction shape:", submission_lgbm.shape)
display(submission_lgbm.head())

submission_lgbm.to_parquet("/kaggle/working/lgbm_corrected_laglabel.parquet", index=False)

# ============================================================
# 9. Evaluate LightGBM alone
# ============================================================

lgbm_score = evaluate_submission(
    submission_lgbm,
    solution,
    target_cols,
    name="LightGBM corrected lag-label"
)

print("\nLightGBM score:", lgbm_score)

# ============================================================
# 10. Blend with existing XGBoost if available
# ============================================================

# Try to find XGBoost predictions from memory or saved file
if "submission_xgb" in globals():
    print("\nFound submission_xgb in memory.")
    xgb_pred = submission_xgb.copy()

elif os.path.exists("/kaggle/working/xgb_corrected_laglabel.parquet"):
    print("\nLoading XGBoost predictions from /kaggle/working/xgb_corrected_laglabel.parquet")
    xgb_pred = pd.read_parquet("/kaggle/working/xgb_corrected_laglabel.parquet")

elif os.path.exists("/kaggle/working/submission_best_local_blend.parquet"):
    print("\nLoading previous best XGBoost/blend predictions from /kaggle/working/submission_best_local_blend.parquet")
    xgb_pred = pd.read_parquet("/kaggle/working/submission_best_local_blend.parquet")

else:
    xgb_pred = None
    print("\nNo existing XGBoost prediction file found. Skipping blend.")

if xgb_pred is not None:
    xgb_pred = xgb_pred[["date_id"] + target_cols].copy()

    xgb_score = evaluate_submission(
        xgb_pred,
        solution,
        target_cols,
        name="Existing XGBoost / previous best"
    )

    xgb_eval = xgb_pred.sort_values("date_id").reset_index(drop=True)
    lgbm_eval = submission_lgbm.sort_values("date_id").reset_index(drop=True)

    xgb_rank = xgb_eval[target_cols].rank(axis=1, method="average", ascending=True)
    lgbm_rank = lgbm_eval[target_cols].rank(axis=1, method="average", ascending=True)

    blend_scores = {}
    blend_submissions = {}

    for w_xgb in [0.10, 0.20, 0.30, 0.40, 0.50, 0.60, 0.70, 0.80, 0.90]:
        w_lgbm = 1.0 - w_xgb

        blended_values = (w_xgb * xgb_rank) + (w_lgbm * lgbm_rank)

        blended_submission = blended_values.copy()
        blended_submission.insert(0, "date_id", xgb_eval["date_id"].values)
        blended_submission = blended_submission[["date_id"] + target_cols].copy()

        blend_name = f"xgb_{w_xgb:.2f}_lgbm_{w_lgbm:.2f}"

        blend_score = evaluate_submission(
            blended_submission,
            solution,
            target_cols,
            name=blend_name
        )

        blend_scores[blend_name] = blend_score
        blend_submissions[blend_name] = blended_submission

    blend_scores_series = pd.Series(blend_scores).sort_values(ascending=False)

    print("\n" + "=" * 70)
    print("Blend results: XGBoost + LightGBM")
    print("=" * 70)
    display(blend_scores_series)

    best_blend_name = blend_scores_series.index[0]
    best_blend_score = blend_scores_series.iloc[0]
    best_blend_submission = blend_submissions[best_blend_name]

    print("\nBest blend:", best_blend_name)
    print("Best blend score:", best_blend_score)

    best_blend_submission.to_parquet("/kaggle/working/submission_xgb_lgbm_blend.parquet", index=False)
    best_blend_submission.to_parquet("/kaggle/working/submission.parquet", index=False)

else:
    submission_lgbm.to_parquet("/kaggle/working/submission.parquet", index=False)

print("\nFiles in /kaggle/working:")
print(os.listdir("/kaggle/working"))

Ground truth shape: (134, 425)
Ground truth date range: 1827 to 1960
Number of targets: 424

     target  lag                                            pair
0  target_0    1                           US_Stock_VT_adj_close
1  target_1    1            LME_PB_Close - US_Stock_VT_adj_close
2  target_2    1                     LME_CA_Close - LME_ZS_Close
3  target_3    1                     LME_AH_Close - LME_ZS_Close
4  target_4    1  LME_AH_Close - JPX_Gold_Standard_Futures_Close

Original feature count: 557
Clean feature count: 552
Train lag-label feature shape: (1961, 425)

,date_id,lag_label_target_0,lag_label_target_1,lag_label_target_2,lag_label_target_3,lag_label_target_4,lag_label_target_5,lag_label_target_6,lag_label_target_7,lag_label_target_8,...,lag_label_target_414,lag_label_target_415,lag_label_target_416,lag_label_target_417,lag_label_target_418,lag_label_target_419,lag_label_target_420,lag_label_target_421,lag_label_target_422,lag_label_target_423
0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,0.005948,-0.002851,-0.004675,-0.000639,NaN,NaN,-0.006729,0.006066,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,0.005783,-0.024118,-0.007052,-0.018955,-0.031852,-0.019452,0.003002,-0.006876,-0.002042,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,0.001048,0.023836,-0.008934,-0.022060,NaN,NaN,0.037449,0.007658,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Test lag-label feature shape: (134, 425)

,date_id,lag_label_target_0,lag_label_target_1,lag_label_target_2,lag_label_target_3,lag_label_target_4,lag_label_target_5,lag_label_target_6,lag_label_target_7,lag_label_target_8,...,lag_label_target_414,lag_label_target_415,lag_label_target_416,lag_label_target_417,lag_label_target_418,lag_label_target_419,lag_label_target_420,lag_label_target_421,lag_label_target_422,lag_label_target_423
0,1827,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1828,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1829,NaN,NaN,0.017868,-0.000205,-0.016391,-0.013827,0.009972,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1830,0.002560,-0.004592,-0.001776,0.000271,-0.016696,-0.020025,0.002514,0.002204,-0.011962,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1831,0.005346,-0.014539,0.019542,0.014626,-0.011631,-0.009223,-0.005199,-0.026092,-0.003865,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

LightGBM feature count: 976
Non-leaky training rows: (1827, 976)
Local test rows: (134, 976)
Training date range: 0 to 1826
Finished 25/424 LightGBM targets in 1.23 minutes
Finished 50/424 LightGBM targets in 2.44 minutes
Finished 75/424 LightGBM targets in 3.64 minutes
Finished 100/424 LightGBM targets in 4.84 minutes
Finished 125/424 LightGBM targets in 6.06 minutes
Finished 150/424 LightGBM targets in 7.27 minutes
Finished 175/424 LightGBM targets in 8.49 minutes
Finished 200/424 LightGBM targets in 9.69 minutes
Finished 225/424 LightGBM targets in 10.92 minutes
Finished 250/424 LightGBM targets in 12.13 minutes
Finished 275/424 LightGBM targets in 13.33 minutes
Finished 300/424 LightGBM targets in 14.54 minutes
Finished 325/424 LightGBM targets in 15.73 minutes
Finished 350/424 LightGBM targets in 16.89 minutes
Finished 375/424 LightGBM targets in 18.08 minutes
Finished 400/424 LightGBM targets in 19.28 minutes

LightGBM prediction shape: (134, 425)

,date_id,target_0,target_1,target_2,target_3,target_4,target_5,target_6,target_7,target_8,...,target_414,target_415,target_416,target_417,target_418,target_419,target_420,target_421,target_422,target_423
0,1827,0.000075,-0.003152,0.001482,0.002220,-0.000683,-0.000365,-0.001034,-0.003489,0.000339,...,0.005235,0.008195,-0.004148,-0.010208,0.003594,-0.012137,0.009734,-0.003191,-0.008931,-0.002435
1,1828,-0.000284,-0.004462,0.000334,0.003501,0.001585,0.000009,-0.004526,-0.005233,-0.000453,...,-0.006060,0.011617,-0.002252,-0.003426,0.011989,0.000591,-0.013592,0.006801,-0.005997,-0.011452
2,1829,0.000431,-0.003127,0.001889,0.002506,0.001551,0.001209,-0.002764,-0.004234,-0.000277,...,0.005613,0.008337,-0.004085,-0.008887,0.001532,-0.009294,0.004456,-0.004937,-0.007529,-0.003702
3,1830,0.001671,-0.004052,0.002540,0.003195,-0.001192,0.000012,-0.001601,-0.005095,0.000344,...,0.008481,0.010034,-0.004737,-0.003323,0.002848,-0.010806,0.017139,-0.005951,-0.002105,-0.000017
4,1831,0.001381,-0.000423,-0.001129,0.001597,-0.001038,0.001608,-0.002933,-0.001646,-0.003091,...,0.001288,0.004096,-0.005401,-0.013584,0.002150,-0.007383,0.009509,-0.005329,-0.010854,0.006857

======================================================================
Evaluating: LightGBM corrected lag-label
======================================================================
Date IDs match: True
Columns match: True

Daily rank correlation summary:

count    134.000000
mean       0.032815
std        0.197160
min       -0.440396
25%       -0.095259
50%        0.023214
75%        0.153123
max        0.648022
dtype: float64

Mean daily rank correlation: 0.032815067641498226
Std daily rank correlation: 0.196422871683535

LightGBM corrected lag-label score: 0.16706337383340947

LightGBM score: 0.16706337383340947

Found submission_xgb in memory.

======================================================================
Evaluating: Existing XGBoost / previous best
======================================================================
Date IDs match: True
Columns match: True

Daily rank correlation summary:

count    134.000000
mean       0.022377
std        0.185004
min       -0.437484
25%       -0.109959
50%        0.024662
75%        0.144630
max        0.729522
dtype: float64

Mean daily rank correlation: 0.022377159221927217
Std daily rank correlation: 0.1843122075214335

Existing XGBoost / previous best score: 0.12140899142193279

======================================================================
Evaluating: xgb_0.10_lgbm_0.90
======================================================================
Date IDs match: True
Columns match: True

Daily rank correlation summary:

count    134.000000
mean       0.032176
std        0.198519
min       -0.452511
25%       -0.095595
50%        0.016397
75%        0.156830
max        0.666463
dtype: float64

Mean daily rank correlation: 0.03217550671498707
Std daily rank correlation: 0.19777736609239738

xgb_0.10_lgbm_0.90 score: 0.16268548495056484

======================================================================
Evaluating: xgb_0.20_lgbm_0.80
======================================================================
Date IDs match: True
Columns match: True

Daily rank correlation summary:

count    134.000000
mean       0.031189
std        0.199034
min       -0.462720
25%       -0.093305
50%        0.018833
75%        0.158524
max        0.679797
dtype: float64

Mean daily rank correlation: 0.031188683160777834
Std daily rank correlation: 0.1982903736476411

xgb_0.20_lgbm_0.80 score: 0.15728793378643605

======================================================================
Evaluating: xgb_0.30_lgbm_0.70
======================================================================
Date IDs match: True
Columns match: True

Daily rank correlation summary:

count    134.000000
mean       0.030014
std        0.198724
min       -0.470363
25%       -0.102201
50%        0.019293
75%        0.163956
max        0.693362
dtype: float64

Mean daily rank correlation: 0.03001363389056315
Std daily rank correlation: 0.19798072529966082

xgb_0.30_lgbm_0.70 score: 0.151598767229158

======================================================================
Evaluating: xgb_0.40_lgbm_0.60
======================================================================
Date IDs match: True
Columns match: True

Daily rank correlation summary:

count    134.000000
mean       0.029130
std        0.198235
min       -0.475042
25%       -0.114482
50%        0.018681
75%        0.165742
max        0.703252
dtype: float64

Mean daily rank correlation: 0.02912951151427046
Std daily rank correlation: 0.1974942346188413

xgb_0.40_lgbm_0.60 score: 0.14749550320033217

======================================================================
Evaluating: xgb_0.50_lgbm_0.50
======================================================================
Date IDs match: True
Columns match: True

Daily rank correlation summary:

count    134.000000
mean       0.028032
std        0.197038
min       -0.477338
25%       -0.118572
50%        0.023659
75%        0.169674
max        0.716514
dtype: float64

Mean daily rank correlation: 0.02803189363805636
Std daily rank correlation: 0.19630148025962305

xgb_0.50_lgbm_0.50 score: 0.14280021526573378

======================================================================
Evaluating: xgb_0.60_lgbm_0.40
======================================================================
Date IDs match: True
Columns match: True

Daily rank correlation summary:

count    134.000000
mean       0.026748
std        0.195335
min       -0.474617
25%       -0.110400
50%        0.026027
75%        0.161260
max        0.726557
dtype: float64

Mean daily rank correlation: 0.02674804085638937
Std daily rank correlation: 0.19460459429632884

xgb_0.60_lgbm_0.40 score: 0.13744814685957268

======================================================================
Evaluating: xgb_0.70_lgbm_0.30
======================================================================
Date IDs match: True
Columns match: True

Daily rank correlation summary:

count    134.000000
mean       0.025581
std        0.192873
min       -0.470463
25%       -0.105685
50%        0.029541
75%        0.149161
max        0.731653
dtype: float64

Mean daily rank correlation: 0.025580913367962116
Std daily rank correlation: 0.19215224824440033

xgb_0.70_lgbm_0.30 score: 0.13312835838082676

======================================================================
Evaluating: xgb_0.80_lgbm_0.20
======================================================================
Date IDs match: True
Columns match: True

Daily rank correlation summary:

count    134.000000
mean       0.024430
std        0.190025
min       -0.461132
25%       -0.105624
50%        0.026466
75%        0.149790
max        0.730763
dtype: float64

Mean daily rank correlation: 0.02443001289257357
Std daily rank correlation: 0.1893150259885258

xgb_0.80_lgbm_0.20 score: 0.1290442360029798

======================================================================
Evaluating: xgb_0.90_lgbm_0.10
======================================================================
Date IDs match: True
Columns match: True

Daily rank correlation summary:

count    134.000000
mean       0.023427
std        0.187554
min       -0.449865
25%       -0.108878
50%        0.026207
75%        0.148785
max        0.732020
dtype: float64

Mean daily rank correlation: 0.023427403233886517
Std daily rank correlation: 0.18685279957562376

xgb_0.90_lgbm_0.10 score: 0.1253789254808831

======================================================================
Blend results: XGBoost + LightGBM
======================================================================

xgb_0.10_lgbm_0.90    0.162685
xgb_0.20_lgbm_0.80    0.157288
xgb_0.30_lgbm_0.70    0.151599
xgb_0.40_lgbm_0.60    0.147496
xgb_0.50_lgbm_0.50    0.142800
xgb_0.60_lgbm_0.40    0.137448
xgb_0.70_lgbm_0.30    0.133128
xgb_0.80_lgbm_0.20    0.129044
xgb_0.90_lgbm_0.10    0.125379
dtype: float64

Best blend: xgb_0.10_lgbm_0.90
Best blend score: 0.16268548495056484

Files in /kaggle/working:
['submission_best_local_blend.parquet', 'lag_baseline.parquet', 'submission.parquet', 'submission_pair_blend.parquet', 'submission_xgb_lgbm_blend.parquet', 'lgbm_corrected_laglabel.parquet', 'xgb_corrected_laglabel.parquet', '.virtual_documents', 'pair_specific_xgb.parquet']

In [20]:
# ============================================================
# Score each XGB + LGBM blend
# Requires your existing evaluate_submission() function
# ============================================================

blend_scores = {}

for blend_name, blend_df in blend_submissions.items():
    blend_score = evaluate_submission(
        blend_df,
        solution,
        target_cols,
        name=blend_name
    )

    blend_scores[blend_name] = blend_score

blend_scores_series = pd.Series(blend_scores).sort_values(ascending=False)

print("\nBlend score results:")
display(blend_scores_series)

best_blend_name = blend_scores_series.index[0]
best_blend_score = blend_scores_series.iloc[0]
best_blend_submission = blend_submissions[best_blend_name]

print("\nBest blend:", best_blend_name)
print("Best blend score:", best_blend_score)

# Save best ensemble
best_blend_submission.to_parquet("/kaggle/working/submission_xgb_lgbm_best_blend.parquet", index=False)
best_blend_submission.to_parquet("/kaggle/working/submission.parquet", index=False)

print("\nSaved best blend to:")
print("/kaggle/working/submission_xgb_lgbm_best_blend.parquet")
print("/kaggle/working/submission.parquet")

======================================================================
Evaluating: xgb_0.10_lgbm_0.90
======================================================================
Date IDs match: True
Columns match: True

Daily rank correlation summary:

count    134.000000
mean       0.032176
std        0.198519
min       -0.452511
25%       -0.095595
50%        0.016397
75%        0.156830
max        0.666463
dtype: float64

Mean daily rank correlation: 0.03217550671498707
Std daily rank correlation: 0.19777736609239738

xgb_0.10_lgbm_0.90 score: 0.16268548495056484

======================================================================
Evaluating: xgb_0.20_lgbm_0.80
======================================================================
Date IDs match: True
Columns match: True

Daily rank correlation summary:

count    134.000000
mean       0.031189
std        0.199034
min       -0.462720
25%       -0.093305
50%        0.018833
75%        0.158524
max        0.679797
dtype: float64

Mean daily rank correlation: 0.031188683160777834
Std daily rank correlation: 0.1982903736476411

xgb_0.20_lgbm_0.80 score: 0.15728793378643605

======================================================================
Evaluating: xgb_0.30_lgbm_0.70
======================================================================
Date IDs match: True
Columns match: True

Daily rank correlation summary:

count    134.000000
mean       0.030014
std        0.198724
min       -0.470363
25%       -0.102201
50%        0.019293
75%        0.163956
max        0.693362
dtype: float64

Mean daily rank correlation: 0.03001363389056315
Std daily rank correlation: 0.19798072529966082

xgb_0.30_lgbm_0.70 score: 0.151598767229158

======================================================================
Evaluating: xgb_0.40_lgbm_0.60
======================================================================
Date IDs match: True
Columns match: True

Daily rank correlation summary:

count    134.000000
mean       0.029130
std        0.198235
min       -0.475042
25%       -0.114482
50%        0.018681
75%        0.165742
max        0.703252
dtype: float64

Mean daily rank correlation: 0.02912951151427046
Std daily rank correlation: 0.1974942346188413

xgb_0.40_lgbm_0.60 score: 0.14749550320033217

======================================================================
Evaluating: xgb_0.50_lgbm_0.50
======================================================================
Date IDs match: True
Columns match: True

Daily rank correlation summary:

count    134.000000
mean       0.028032
std        0.197038
min       -0.477338
25%       -0.118572
50%        0.023659
75%        0.169674
max        0.716514
dtype: float64

Mean daily rank correlation: 0.02803189363805636
Std daily rank correlation: 0.19630148025962305

xgb_0.50_lgbm_0.50 score: 0.14280021526573378

======================================================================
Evaluating: xgb_0.60_lgbm_0.40
======================================================================
Date IDs match: True
Columns match: True

Daily rank correlation summary:

count    134.000000
mean       0.026748
std        0.195335
min       -0.474617
25%       -0.110400
50%        0.026027
75%        0.161260
max        0.726557
dtype: float64

Mean daily rank correlation: 0.02674804085638937
Std daily rank correlation: 0.19460459429632884

xgb_0.60_lgbm_0.40 score: 0.13744814685957268

======================================================================
Evaluating: xgb_0.70_lgbm_0.30
======================================================================
Date IDs match: True
Columns match: True

Daily rank correlation summary:

count    134.000000
mean       0.025581
std        0.192873
min       -0.470463
25%       -0.105685
50%        0.029541
75%        0.149161
max        0.731653
dtype: float64

Mean daily rank correlation: 0.025580913367962116
Std daily rank correlation: 0.19215224824440033

xgb_0.70_lgbm_0.30 score: 0.13312835838082676

======================================================================
Evaluating: xgb_0.80_lgbm_0.20
======================================================================
Date IDs match: True
Columns match: True

Daily rank correlation summary:

count    134.000000
mean       0.024430
std        0.190025
min       -0.461132
25%       -0.105624
50%        0.026466
75%        0.149790
max        0.730763
dtype: float64

Mean daily rank correlation: 0.02443001289257357
Std daily rank correlation: 0.1893150259885258

xgb_0.80_lgbm_0.20 score: 0.1290442360029798

======================================================================
Evaluating: xgb_0.90_lgbm_0.10
======================================================================
Date IDs match: True
Columns match: True

Daily rank correlation summary:

count    134.000000
mean       0.023427
std        0.187554
min       -0.449865
25%       -0.108878
50%        0.026207
75%        0.148785
max        0.732020
dtype: float64

Mean daily rank correlation: 0.023427403233886517
Std daily rank correlation: 0.18685279957562376

xgb_0.90_lgbm_0.10 score: 0.1253789254808831

Blend score results:

xgb_0.10_lgbm_0.90    0.162685
xgb_0.20_lgbm_0.80    0.157288
xgb_0.30_lgbm_0.70    0.151599
xgb_0.40_lgbm_0.60    0.147496
xgb_0.50_lgbm_0.50    0.142800
xgb_0.60_lgbm_0.40    0.137448
xgb_0.70_lgbm_0.30    0.133128
xgb_0.80_lgbm_0.20    0.129044
xgb_0.90_lgbm_0.10    0.125379
dtype: float64

Best blend: xgb_0.10_lgbm_0.90
Best blend score: 0.16268548495056484

Saved best blend to:
/kaggle/working/submission_xgb_lgbm_best_blend.parquet
/kaggle/working/submission.parquet

In [21]:
# ============================================================
# Score each XGB + LGBM blend
# Requires your existing evaluate_submission() function
# ============================================================

blend_scores = {}

for blend_name, blend_df in blend_submissions.items():
    blend_score = evaluate_submission(
        blend_df,
        solution,
        target_cols,
        name=blend_name
    )

    blend_scores[blend_name] = blend_score

blend_scores_series = pd.Series(blend_scores).sort_values(ascending=False)

print("\nBlend score results:")
display(blend_scores_series)

best_blend_name = blend_scores_series.index[0]
best_blend_score = blend_scores_series.iloc[0]
best_blend_submission = blend_submissions[best_blend_name]

print("\nBest blend:", best_blend_name)
print("Best blend score:", best_blend_score)

# Save best ensemble
best_blend_submission.to_parquet("/kaggle/working/submission_xgb_lgbm_best_blend.parquet", index=False)
best_blend_submission.to_parquet("/kaggle/working/submission.parquet", index=False)

print("\nSaved best blend to:")
print("/kaggle/working/submission_xgb_lgbm_best_blend.parquet")
print("/kaggle/working/submission.parquet")

======================================================================
Evaluating: xgb_0.10_lgbm_0.90
======================================================================
Date IDs match: True
Columns match: True

Daily rank correlation summary:

count    134.000000
mean       0.032176
std        0.198519
min       -0.452511
25%       -0.095595
50%        0.016397
75%        0.156830
max        0.666463
dtype: float64

Mean daily rank correlation: 0.03217550671498707
Std daily rank correlation: 0.19777736609239738

xgb_0.10_lgbm_0.90 score: 0.16268548495056484

======================================================================
Evaluating: xgb_0.20_lgbm_0.80
======================================================================
Date IDs match: True
Columns match: True

Daily rank correlation summary:

count    134.000000
mean       0.031189
std        0.199034
min       -0.462720
25%       -0.093305
50%        0.018833
75%        0.158524
max        0.679797
dtype: float64

Mean daily rank correlation: 0.031188683160777834
Std daily rank correlation: 0.1982903736476411

xgb_0.20_lgbm_0.80 score: 0.15728793378643605

======================================================================
Evaluating: xgb_0.30_lgbm_0.70
======================================================================
Date IDs match: True
Columns match: True

Daily rank correlation summary:

count    134.000000
mean       0.030014
std        0.198724
min       -0.470363
25%       -0.102201
50%        0.019293
75%        0.163956
max        0.693362
dtype: float64

Mean daily rank correlation: 0.03001363389056315
Std daily rank correlation: 0.19798072529966082

xgb_0.30_lgbm_0.70 score: 0.151598767229158

======================================================================
Evaluating: xgb_0.40_lgbm_0.60
======================================================================
Date IDs match: True
Columns match: True

Daily rank correlation summary:

count    134.000000
mean       0.029130
std        0.198235
min       -0.475042
25%       -0.114482
50%        0.018681
75%        0.165742
max        0.703252
dtype: float64

Mean daily rank correlation: 0.02912951151427046
Std daily rank correlation: 0.1974942346188413

xgb_0.40_lgbm_0.60 score: 0.14749550320033217

======================================================================
Evaluating: xgb_0.50_lgbm_0.50
======================================================================
Date IDs match: True
Columns match: True

Daily rank correlation summary:

count    134.000000
mean       0.028032
std        0.197038
min       -0.477338
25%       -0.118572
50%        0.023659
75%        0.169674
max        0.716514
dtype: float64

Mean daily rank correlation: 0.02803189363805636
Std daily rank correlation: 0.19630148025962305

xgb_0.50_lgbm_0.50 score: 0.14280021526573378

======================================================================
Evaluating: xgb_0.60_lgbm_0.40
======================================================================
Date IDs match: True
Columns match: True

Daily rank correlation summary:

count    134.000000
mean       0.026748
std        0.195335
min       -0.474617
25%       -0.110400
50%        0.026027
75%        0.161260
max        0.726557
dtype: float64

Mean daily rank correlation: 0.02674804085638937
Std daily rank correlation: 0.19460459429632884

xgb_0.60_lgbm_0.40 score: 0.13744814685957268

======================================================================
Evaluating: xgb_0.70_lgbm_0.30
======================================================================
Date IDs match: True
Columns match: True

Daily rank correlation summary:

count    134.000000
mean       0.025581
std        0.192873
min       -0.470463
25%       -0.105685
50%        0.029541
75%        0.149161
max        0.731653
dtype: float64

Mean daily rank correlation: 0.025580913367962116
Std daily rank correlation: 0.19215224824440033

xgb_0.70_lgbm_0.30 score: 0.13312835838082676

======================================================================
Evaluating: xgb_0.80_lgbm_0.20
======================================================================
Date IDs match: True
Columns match: True

Daily rank correlation summary:

count    134.000000
mean       0.024430
std        0.190025
min       -0.461132
25%       -0.105624
50%        0.026466
75%        0.149790
max        0.730763
dtype: float64

Mean daily rank correlation: 0.02443001289257357
Std daily rank correlation: 0.1893150259885258

xgb_0.80_lgbm_0.20 score: 0.1290442360029798

======================================================================
Evaluating: xgb_0.90_lgbm_0.10
======================================================================
Date IDs match: True
Columns match: True

Daily rank correlation summary:

count    134.000000
mean       0.023427
std        0.187554
min       -0.449865
25%       -0.108878
50%        0.026207
75%        0.148785
max        0.732020
dtype: float64

Mean daily rank correlation: 0.023427403233886517
Std daily rank correlation: 0.18685279957562376

xgb_0.90_lgbm_0.10 score: 0.1253789254808831

Blend score results:

xgb_0.10_lgbm_0.90    0.162685
xgb_0.20_lgbm_0.80    0.157288
xgb_0.30_lgbm_0.70    0.151599
xgb_0.40_lgbm_0.60    0.147496
xgb_0.50_lgbm_0.50    0.142800
xgb_0.60_lgbm_0.40    0.137448
xgb_0.70_lgbm_0.30    0.133128
xgb_0.80_lgbm_0.20    0.129044
xgb_0.90_lgbm_0.10    0.125379
dtype: float64

Best blend: xgb_0.10_lgbm_0.90
Best blend score: 0.16268548495056484

Saved best blend to:
/kaggle/working/submission_xgb_lgbm_best_blend.parquet
/kaggle/working/submission.parquet

In [22]:
# ============================================================
# Random Forest Test: Non-Leaky + Corrected Lag Label Features
# Uses existing X_train_lgbm / X_test_lgbm feature matrices
# ============================================================

import gc
import time
import numpy as np
import pandas as pd

from sklearn.ensemble import RandomForestRegressor

rf_params = {
    "n_estimators": 200,
    "max_depth": 5,
    "min_samples_leaf": 20,
    "max_features": "sqrt",
    "random_state": 42,
    "n_jobs": -1,
}

submission_rf = pd.DataFrame(index=test.index)

start_time = time.time()

for i, target in enumerate(target_cols):
    y_train = train_labels.loc[train_nonleaky_mask, target].values
    target_mask = ~np.isnan(y_train)

    if target_mask.sum() < 100:
        submission_rf[target] = 0.0
        continue

    model = RandomForestRegressor(**rf_params)

    model.fit(
        X_train_lgbm.loc[target_mask],
        y_train[target_mask]
    )

    submission_rf[target] = model.predict(X_test_lgbm)

    if (i + 1) % 25 == 0:
        elapsed = (time.time() - start_time) / 60
        print(f"Finished {i + 1}/{len(target_cols)} RF targets in {elapsed:.2f} minutes")

    del model
    gc.collect()

submission_rf.insert(0, "date_id", test["date_id"].values)
submission_rf = submission_rf[["date_id"] + target_cols].copy()

submission_rf.to_parquet("/kaggle/working/random_forest_laglabel.parquet", index=False)

rf_score = evaluate_submission(
    submission_rf,
    solution,
    target_cols,
    name="Random Forest corrected lag-label"
)

print("Random Forest score:", rf_score)

Finished 25/424 RF targets in 0.91 minutes
Finished 50/424 RF targets in 1.83 minutes
Finished 75/424 RF targets in 2.72 minutes
Finished 100/424 RF targets in 3.63 minutes
Finished 125/424 RF targets in 4.53 minutes
Finished 150/424 RF targets in 5.42 minutes
Finished 175/424 RF targets in 6.33 minutes
Finished 200/424 RF targets in 7.23 minutes
Finished 225/424 RF targets in 8.13 minutes
Finished 250/424 RF targets in 9.04 minutes
Finished 275/424 RF targets in 9.92 minutes
Finished 300/424 RF targets in 10.81 minutes
Finished 325/424 RF targets in 11.71 minutes
Finished 350/424 RF targets in 12.59 minutes
Finished 375/424 RF targets in 13.50 minutes
Finished 400/424 RF targets in 14.40 minutes

======================================================================
Evaluating: Random Forest corrected lag-label
======================================================================
Date IDs match: True
Columns match: True

Daily rank correlation summary:

count    134.000000
mean       0.029027
std        0.182692
min       -0.414482
25%       -0.088253
50%        0.029744
75%        0.158131
max        0.560958
dtype: float64

Mean daily rank correlation: 0.029027481611147644
Std daily rank correlation: 0.18200951471613655

Random Forest corrected lag-label score: 0.15948331962985082
Random Forest score: 0.15948331962985082

In [23]:
# ============================================================
# Blend LightGBM + Random Forest
# ============================================================

import pandas as pd

lgbm_pred = pd.read_parquet("/kaggle/working/lgbm_corrected_laglabel.parquet")
rf_pred = pd.read_parquet("/kaggle/working/random_forest_laglabel.parquet")

lgbm_pred = lgbm_pred[["date_id"] + target_cols].sort_values("date_id").reset_index(drop=True)
rf_pred = rf_pred[["date_id"] + target_cols].sort_values("date_id").reset_index(drop=True)

assert list(lgbm_pred["date_id"]) == list(rf_pred["date_id"])

lgbm_rank = lgbm_pred[target_cols].rank(axis=1, method="average", ascending=True)
rf_rank = rf_pred[target_cols].rank(axis=1, method="average", ascending=True)

blend_scores = {}
blend_submissions = {}

for w_lgbm in [0.50, 0.60, 0.70, 0.75, 0.80, 0.85, 0.90, 0.95]:
    w_rf = 1.0 - w_lgbm

    blended_values = (w_lgbm * lgbm_rank) + (w_rf * rf_rank)

    blended_submission = blended_values.copy()
    blended_submission.insert(0, "date_id", lgbm_pred["date_id"].values)
    blended_submission = blended_submission[["date_id"] + target_cols].copy()

    blend_name = f"lgbm_{w_lgbm:.2f}_rf_{w_rf:.2f}"

    blend_score = evaluate_submission(
        blended_submission,
        solution,
        target_cols,
        name=blend_name
    )

    blend_scores[blend_name] = blend_score
    blend_submissions[blend_name] = blended_submission

blend_scores_series = pd.Series(blend_scores).sort_values(ascending=False)

print("\nLightGBM + RF blend results:")
display(blend_scores_series)

best_name = blend_scores_series.index[0]
best_score = blend_scores_series.iloc[0]
best_submission = blend_submissions[best_name]

print("Best blend:", best_name)
print("Best blend score:", best_score)

best_submission.to_parquet("/kaggle/working/submission_lgbm_rf_blend.parquet", index=False)
best_submission.to_parquet("/kaggle/working/submission.parquet", index=False)

======================================================================
Evaluating: lgbm_0.50_rf_0.50
======================================================================
Date IDs match: True
Columns match: True

Daily rank correlation summary:

count    134.000000
mean       0.033594
std        0.194924
min       -0.436757
25%       -0.102650
50%        0.037143
75%        0.155321
max        0.573673
dtype: float64

Mean daily rank correlation: 0.03359417218732935
Std daily rank correlation: 0.1941949941540524

lgbm_0.50_rf_0.50 score: 0.17299195756137528

======================================================================
Evaluating: lgbm_0.60_rf_0.40
======================================================================
Date IDs match: True
Columns match: True

Daily rank correlation summary:

count    134.000000
mean       0.034001
std        0.196995
min       -0.444710
25%       -0.108448
50%        0.040201
75%        0.158199
max        0.603986
dtype: float64

Mean daily rank correlation: 0.03400144964105989
Std daily rank correlation: 0.1962581458666252

lgbm_0.60_rf_0.40 score: 0.17324860321551638

======================================================================
Evaluating: lgbm_0.70_rf_0.30
======================================================================
Date IDs match: True
Columns match: True

Daily rank correlation summary:

count    134.000000
mean       0.033917
std        0.198222
min       -0.452229
25%       -0.104839
50%        0.034871
75%        0.154170
max        0.627525
dtype: float64

Mean daily rank correlation: 0.03391711486145646
Std daily rank correlation: 0.19748074272229837

lgbm_0.70_rf_0.30 score: 0.1717489735652424

======================================================================
Evaluating: lgbm_0.75_rf_0.25
======================================================================
Date IDs match: True
Columns match: True

Daily rank correlation summary:

count    134.000000
mean       0.033919
std        0.198236
min       -0.452675
25%       -0.104650
50%        0.034271
75%        0.152448
max        0.632293
dtype: float64

Mean daily rank correlation: 0.033918560040583946
Std daily rank correlation: 0.197494491065618

lgbm_0.75_rf_0.25 score: 0.17174433503218287

======================================================================
Evaluating: lgbm_0.80_rf_0.20
======================================================================
Date IDs match: True
Columns match: True

Daily rank correlation summary:

count    134.000000
mean       0.033890
std        0.198664
min       -0.451518
25%       -0.101513
50%        0.028667
75%        0.154247
max        0.635195
dtype: float64

Mean daily rank correlation: 0.03388981092147977
Std daily rank correlation: 0.19792143793552472

lgbm_0.80_rf_0.20 score: 0.17122860097914092

======================================================================
Evaluating: lgbm_0.85_rf_0.15
======================================================================
Date IDs match: True
Columns match: True

Daily rank correlation summary:

count    134.000000
mean       0.033609
std        0.198590
min       -0.448981
25%       -0.098850
50%        0.025553
75%        0.156612
max        0.640455
dtype: float64

Mean daily rank correlation: 0.03360918806120498
Std daily rank correlation: 0.19784766104187146

lgbm_0.85_rf_0.15 score: 0.1698740732350235

======================================================================
Evaluating: lgbm_0.90_rf_0.10
======================================================================
Date IDs match: True
Columns match: True

Daily rank correlation summary:

count    134.000000
mean       0.033473
std        0.198405
min       -0.446755
25%       -0.097081
50%        0.027070
75%        0.155130
max        0.644943
dtype: float64

Mean daily rank correlation: 0.03347349396440517
Std daily rank correlation: 0.1976637691883493

lgbm_0.90_rf_0.10 score: 0.16934562212313697

======================================================================
Evaluating: lgbm_0.95_rf_0.05
======================================================================
Date IDs match: True
Columns match: True

Daily rank correlation summary:

count    134.000000
mean       0.033347
std        0.197789
min       -0.444991
25%       -0.090607
50%        0.021292
75%        0.155055
max        0.648390
dtype: float64

Mean daily rank correlation: 0.033347018623197035
Std daily rank correlation: 0.19704937740289583

lgbm_0.95_rf_0.05 score: 0.16923178881714634

LightGBM + RF blend results:

lgbm_0.60_rf_0.40    0.173249
lgbm_0.50_rf_0.50    0.172992
lgbm_0.70_rf_0.30    0.171749
lgbm_0.75_rf_0.25    0.171744
lgbm_0.80_rf_0.20    0.171229
lgbm_0.85_rf_0.15    0.169874
lgbm_0.90_rf_0.10    0.169346
lgbm_0.95_rf_0.05    0.169232
dtype: float64

Best blend: lgbm_0.60_rf_0.40
Best blend score: 0.17324860321551638

In [24]:
# ============================================================
# Try LightGBM + Random Forest + small XGBoost blend
# ============================================================

xgb_pred = pd.read_parquet("/kaggle/working/xgb_corrected_laglabel.parquet")
lgbm_pred = pd.read_parquet("/kaggle/working/lgbm_corrected_laglabel.parquet")
rf_pred = pd.read_parquet("/kaggle/working/random_forest_laglabel.parquet")

xgb_pred = xgb_pred[["date_id"] + target_cols].sort_values("date_id").reset_index(drop=True)
lgbm_pred = lgbm_pred[["date_id"] + target_cols].sort_values("date_id").reset_index(drop=True)
rf_pred = rf_pred[["date_id"] + target_cols].sort_values("date_id").reset_index(drop=True)

xgb_rank = xgb_pred[target_cols].rank(axis=1, method="average", ascending=True)
lgbm_rank = lgbm_pred[target_cols].rank(axis=1, method="average", ascending=True)
rf_rank = rf_pred[target_cols].rank(axis=1, method="average", ascending=True)

blend_scores = {}
blend_submissions = {}

weight_grid = [
    (0.05, 0.57, 0.38),
    (0.10, 0.54, 0.36),
    (0.15, 0.51, 0.34),
    (0.20, 0.48, 0.32),
    (0.00, 0.60, 0.40),  # current best baseline
]

for w_xgb, w_lgbm, w_rf in weight_grid:
    blended_values = (
        w_xgb * xgb_rank
        + w_lgbm * lgbm_rank
        + w_rf * rf_rank
    )

    blended_submission = blended_values.copy()
    blended_submission.insert(0, "date_id", lgbm_pred["date_id"].values)
    blended_submission = blended_submission[["date_id"] + target_cols].copy()

    blend_name = f"xgb_{w_xgb:.2f}_lgbm_{w_lgbm:.2f}_rf_{w_rf:.2f}"

    blend_score = evaluate_submission(
        blended_submission,
        solution,
        target_cols,
        name=blend_name
    )

    blend_scores[blend_name] = blend_score
    blend_submissions[blend_name] = blended_submission

blend_scores_series = pd.Series(blend_scores).sort_values(ascending=False)

print("Three-way blend results:")
display(blend_scores_series)

best_name = blend_scores_series.index[0]
best_score = blend_scores_series.iloc[0]
best_submission = blend_submissions[best_name]

print("Best three-way blend:", best_name)
print("Best three-way blend score:", best_score)

best_submission.to_parquet("/kaggle/working/submission_best_ensemble.parquet", index=False)
best_submission.to_parquet("/kaggle/working/submission.parquet", index=False)

======================================================================
Evaluating: xgb_0.05_lgbm_0.57_rf_0.38
======================================================================
Date IDs match: True
Columns match: True

Daily rank correlation summary:

count    134.000000
mean       0.033569
std        0.197677
min       -0.451354
25%       -0.114727
50%        0.039086
75%        0.153501
max        0.618726
dtype: float64

Mean daily rank correlation: 0.03356935584746159
Std daily rank correlation: 0.19693827539696573

xgb_0.05_lgbm_0.57_rf_0.38 score: 0.1704562293936834

======================================================================
Evaluating: xgb_0.10_lgbm_0.54_rf_0.36
======================================================================
Date IDs match: True
Columns match: True

Daily rank correlation summary:

count    134.000000
mean       0.033205
std        0.198012
min       -0.455949
25%       -0.111281
50%        0.038254
75%        0.146354
max        0.628977
dtype: float64

Mean daily rank correlation: 0.03320525159511417
Std daily rank correlation: 0.19727189502309994

xgb_0.10_lgbm_0.54_rf_0.36 score: 0.16832226197870678

======================================================================
Evaluating: xgb_0.15_lgbm_0.51_rf_0.34
======================================================================
Date IDs match: True
Columns match: True

Daily rank correlation summary:

count    134.000000
mean       0.032672
std        0.198058
min       -0.459944
25%       -0.110846
50%        0.037345
75%        0.147443
max        0.640047
dtype: float64

Mean daily rank correlation: 0.032672308315469675
Std daily rank correlation: 0.19731756992986518

xgb_0.15_lgbm_0.51_rf_0.34 score: 0.1655823570454611

======================================================================
Evaluating: xgb_0.20_lgbm_0.48_rf_0.32
======================================================================
Date IDs match: True
Columns match: True

Daily rank correlation summary:

count    134.000000
mean       0.032152
std        0.198171
min       -0.465913
25%       -0.111137
50%        0.033985
75%        0.143460
max        0.647989
dtype: float64

Mean daily rank correlation: 0.03215185270010866
Std daily rank correlation: 0.19742976767133238

xgb_0.20_lgbm_0.48_rf_0.32 score: 0.16285210218974108

======================================================================
Evaluating: xgb_0.00_lgbm_0.60_rf_0.40
======================================================================
Date IDs match: True
Columns match: True

Daily rank correlation summary:

count    134.000000
mean       0.034001
std        0.196995
min       -0.444710
25%       -0.108448
50%        0.040201
75%        0.158199
max        0.603986
dtype: float64

Mean daily rank correlation: 0.03400144964105989
Std daily rank correlation: 0.1962581458666252

xgb_0.00_lgbm_0.60_rf_0.40 score: 0.17324860321551638
Three-way blend results:

xgb_0.00_lgbm_0.60_rf_0.40    0.173249
xgb_0.05_lgbm_0.57_rf_0.38    0.170456
xgb_0.10_lgbm_0.54_rf_0.36    0.168322
xgb_0.15_lgbm_0.51_rf_0.34    0.165582
xgb_0.20_lgbm_0.48_rf_0.32    0.162852
dtype: float64

Best three-way blend: xgb_0.00_lgbm_0.60_rf_0.40
Best three-way blend score: 0.17324860321551638

In [6]:
# ============================================================
# Self-contained ensemble:
# Your Random Forest output + Friend's LightGBM output
# ============================================================

import os
import numpy as np
import pandas as pd

# ============================================================
# 1. Paths
# ============================================================

COMPETITION_PATH = "/kaggle/input/competitions/mitsui-commodity-prediction-challenge"
GROUND_TRUTH_PATH = "/kaggle/input/datasets/stephenweiler208/ground-truth"

# Friend's LightGBM output folder
lgbm_path = "/kaggle/input/datasets/stephenweiler208/lgbm-adam"

# Your Random Forest output
# Change this if your RF file has a different name
possible_rf_paths = "/kaggle/input/datasets/stephenweiler208/random-forest1"

# ============================================================
# 2. Helper: load a parquet/csv from file or folder
# ============================================================

def load_prediction_file(path):
    """
    Loads either:
    - a .parquet file
    - a .csv file
    - a folder containing one .parquet or .csv file
    """

    if not os.path.exists(path):
        raise FileNotFoundError(f"Path does not exist: {path}")

    if os.path.isdir(path):
        files = os.listdir(path)
        print(f"\nFiles in folder {path}:")
        print(files)

        parquet_files = [f for f in files if f.endswith(".parquet")]
        csv_files = [f for f in files if f.endswith(".csv")]

        if len(parquet_files) > 0:
            file_path = os.path.join(path, parquet_files[0])
            print("Loading parquet:", file_path)
            return pd.read_parquet(file_path)

        if len(csv_files) > 0:
            file_path = os.path.join(path, csv_files[0])
            print("Loading csv:", file_path)
            return pd.read_csv(file_path)

        raise FileNotFoundError(f"No .parquet or .csv file found in folder: {path}")

    if path.endswith(".parquet"):
        print("Loading parquet:", path)
        return pd.read_parquet(path)

    if path.endswith(".csv"):
        print("Loading csv:", path)
        return pd.read_csv(path)

    raise ValueError(f"Unsupported file type or folder: {path}")


def find_existing_path(paths):
    for path in paths:
        if os.path.exists(path):
            return path
    raise FileNotFoundError(
        "None of the possible RF paths exist. Check /kaggle/working or upload the RF file as a dataset."
    )


# ============================================================
# 3. Load competition metadata and ground truth
# ============================================================

target_pairs = pd.read_csv(f"{COMPETITION_PATH}/target_pairs.csv")
target_cols = target_pairs["target"].tolist()

test = pd.read_csv(f"{COMPETITION_PATH}/test.csv")
test_date_ids = test["date_id"].values

if os.path.isdir(GROUND_TRUTH_PATH):
    gt_files = os.listdir(GROUND_TRUTH_PATH)
    print("\nFiles in ground truth folder:")
    print(gt_files)

    gt_csvs = [f for f in gt_files if f.endswith(".csv")]

    if len(gt_csvs) == 0:
        raise FileNotFoundError("No CSV found in ground truth folder.")

    ground_truth_file = os.path.join(GROUND_TRUTH_PATH, gt_csvs[0])
else:
    ground_truth_file = GROUND_TRUTH_PATH

solution = pd.read_csv(ground_truth_file)

print("\nLoaded metadata:")
print("target_pairs:", target_pairs.shape)
print("test:", test.shape)
print("solution:", solution.shape)
print("Number of targets:", len(target_cols))

# ============================================================
# 4. Load RF and friend's LGBM predictions
# ============================================================

rf_path = possible_rf_paths

rf_pred = load_prediction_file(rf_path)
friend_lgbm_pred = load_prediction_file(friend_lgbm_path)

print("\nRaw prediction shapes:")
print("RF:", rf_pred.shape)
print("Friend LGBM:", friend_lgbm_pred.shape)

display(rf_pred.head())
display(friend_lgbm_pred.head())

# ============================================================
# 5. Add date_id if missing
# ============================================================

if "date_id" not in rf_pred.columns:
    rf_pred = rf_pred.copy()
    rf_pred.insert(0, "date_id", test_date_ids[:len(rf_pred)])

if "date_id" not in friend_lgbm_pred.columns:
    friend_lgbm_pred = friend_lgbm_pred.copy()
    friend_lgbm_pred.insert(0, "date_id", test_date_ids[:len(friend_lgbm_pred)])

# ============================================================
# 6. Align rows and columns
# ============================================================

# Only keep target columns that appear in all three files
available_targets = [
    c for c in target_cols
    if c in rf_pred.columns and c in friend_lgbm_pred.columns and c in solution.columns
]

if len(available_targets) != len(target_cols):
    print("Warning: not all target columns were found.")
    print("Expected:", len(target_cols))
    print("Available:", len(available_targets))

target_cols = available_targets

rf_pred = rf_pred[["date_id"] + target_cols].sort_values("date_id").reset_index(drop=True)
friend_lgbm_pred = friend_lgbm_pred[["date_id"] + target_cols].sort_values("date_id").reset_index(drop=True)
solution = solution[["date_id"] + target_cols].sort_values("date_id").reset_index(drop=True)

# Keep only dates common to all three
common_dates = sorted(
    set(rf_pred["date_id"])
    & set(friend_lgbm_pred["date_id"])
    & set(solution["date_id"])
)

rf_pred = rf_pred[rf_pred["date_id"].isin(common_dates)].sort_values("date_id").reset_index(drop=True)
friend_lgbm_pred = friend_lgbm_pred[friend_lgbm_pred["date_id"].isin(common_dates)].sort_values("date_id").reset_index(drop=True)
solution = solution[solution["date_id"].isin(common_dates)].sort_values("date_id").reset_index(drop=True)

print("\nAligned shapes:")
print("RF:", rf_pred.shape)
print("Friend LGBM:", friend_lgbm_pred.shape)
print("Solution:", solution.shape)

print("\nDate ranges:")
print("RF:", rf_pred["date_id"].min(), "to", rf_pred["date_id"].max())
print("Friend LGBM:", friend_lgbm_pred["date_id"].min(), "to", friend_lgbm_pred["date_id"].max())
print("Solution:", solution["date_id"].min(), "to", solution["date_id"].max())

assert list(rf_pred["date_id"]) == list(friend_lgbm_pred["date_id"]), "RF and LGBM date_id mismatch"
assert list(rf_pred["date_id"]) == list(solution["date_id"]), "Prediction and solution date_id mismatch"
assert list(rf_pred.columns) == list(friend_lgbm_pred.columns), "Prediction columns mismatch"
assert list(rf_pred.columns) == list(solution.columns), "Solution columns mismatch"

# ============================================================
# 7. Competition-style scoring functions
# ============================================================

SOLUTION_NULL_FILLER = -999999

def rank_correlation_sharpe_ratio(merged_df: pd.DataFrame) -> float:
    prediction_cols = [col for col in merged_df.columns if col.startswith("prediction_")]
    target_cols_metric = [col for col in merged_df.columns if col.startswith("target_")]

    daily_rank_corrs = []

    for _, row in merged_df.iterrows():
        non_null_targets = [col for col in target_cols_metric if not pd.isnull(row[col])]

        matching_predictions = [
            col for col in prediction_cols
            if col.replace("prediction", "target") in non_null_targets
        ]

        if len(non_null_targets) < 3:
            daily_rank_corrs.append(np.nan)
            continue

        if row[non_null_targets].std(ddof=0) == 0 or row[matching_predictions].std(ddof=0) == 0:
            daily_rank_corrs.append(np.nan)
            continue

        corr = np.corrcoef(
            row[matching_predictions].rank(method="average"),
            row[non_null_targets].rank(method="average")
        )[0, 1]

        daily_rank_corrs.append(corr)

    daily_rank_corrs = pd.Series(daily_rank_corrs).dropna()

    std_dev = daily_rank_corrs.std(ddof=0)

    if std_dev == 0:
        raise ZeroDivisionError("Daily rank correlation standard deviation is zero.")

    print("\nDaily rank correlation summary:")
    display(daily_rank_corrs.describe())

    print("Mean daily rank correlation:", daily_rank_corrs.mean())
    print("Std daily rank correlation:", std_dev)

    return float(daily_rank_corrs.mean() / std_dev)


def score(solution_df: pd.DataFrame, submission_df: pd.DataFrame, row_id_column_name: str) -> float:
    solution_df = solution_df.copy()
    submission_df = submission_df.copy()

    del solution_df[row_id_column_name]
    del submission_df[row_id_column_name]

    assert all(solution_df.columns == submission_df.columns), "Solution and submission columns do not match."

    submission_df = submission_df.rename(
        columns={col: col.replace("target_", "prediction_") for col in submission_df.columns}
    )

    solution_df = solution_df.replace(SOLUTION_NULL_FILLER, None)

    merged_df = pd.concat([solution_df, submission_df], axis="columns")

    return rank_correlation_sharpe_ratio(merged_df)


def evaluate_submission(submission_df, solution_df, target_cols, name="model"):
    solution_eval = solution_df[["date_id"] + target_cols].copy()
    submission_eval = submission_df[["date_id"] + target_cols].copy()

    solution_eval = solution_eval.sort_values("date_id").reset_index(drop=True)
    submission_eval = submission_eval.sort_values("date_id").reset_index(drop=True)

    assert list(solution_eval["date_id"]) == list(submission_eval["date_id"]), "date_id mismatch"
    assert list(solution_eval.columns) == list(submission_eval.columns), "column mismatch"

    model_score = score(
        solution_df=solution_eval,
        submission_df=submission_eval,
        row_id_column_name="date_id"
    )

    print(f"\n{name} score:", model_score)

    return model_score

# ============================================================
# 8. Score individual models
# ============================================================

rf_score = evaluate_submission(
    rf_pred,
    solution,
    target_cols,
    name="Your Random Forest"
)

friend_lgbm_score = evaluate_submission(
    friend_lgbm_pred,
    solution,
    target_cols,
    name="Friend LightGBM"
)

print("\nIndividual scores:")
print("RF:", rf_score)
print("Friend LGBM:", friend_lgbm_score)

# ============================================================
# 9. Rank-blend RF + friend's LGBM
# ============================================================

rf_rank = rf_pred[target_cols].rank(axis=1, method="average", ascending=True)
friend_lgbm_rank = friend_lgbm_pred[target_cols].rank(axis=1, method="average", ascending=True)

blend_scores = {}
blend_submissions = {}

for w_lgbm in [0.05, 0.10, 0.20, 0.30, 0.40, 0.50, 0.60, 0.70, 0.80, 0.90, 0.95]:
    w_rf = 1.0 - w_lgbm

    blended_values = (w_lgbm * friend_lgbm_rank) + (w_rf * rf_rank)

    blended_submission = blended_values.copy()
    blended_submission.insert(0, "date_id", rf_pred["date_id"].values)
    blended_submission = blended_submission[["date_id"] + target_cols].copy()

    blend_name = f"friendlgbm_{w_lgbm:.2f}_rf_{w_rf:.2f}"

    blend_score = evaluate_submission(
        blended_submission,
        solution,
        target_cols,
        name=blend_name
    )

    blend_scores[blend_name] = blend_score
    blend_submissions[blend_name] = blended_submission

blend_scores_series = pd.Series(blend_scores).sort_values(ascending=False)

print("\nRF + Friend LGBM blend results:")
display(blend_scores_series)

best_blend_name = blend_scores_series.index[0]
best_blend_score = blend_scores_series.iloc[0]
best_blend_submission = blend_submissions[best_blend_name]

print("\nBest blend:", best_blend_name)
print("Best blend score:", best_blend_score)

# ============================================================
# 10. Save best blend
# ============================================================

best_blend_submission.to_parquet("/kaggle/working/submission_rf_friend_lgbm_blend.parquet", index=False)
best_blend_submission.to_parquet("/kaggle/working/submission.parquet", index=False)

print("\nSaved:")
print("/kaggle/working/submission_rf_friend_lgbm_blend.parquet")
print("/kaggle/working/submission.parquet")

Files in ground truth folder:
['test_ground_truth.csv']

Loaded metadata:
target_pairs: (424, 3)
test: (134, 559)
solution: (134, 425)
Number of targets: 424

Files in folder /kaggle/input/datasets/stephenweiler208/random-forest1:
['final_rf.parquet']
Loading parquet: /kaggle/input/datasets/stephenweiler208/random-forest1/final_rf.parquet

Files in folder /kaggle/input/datasets/stephenweiler208/lgbm-adam:
['lgbm_attempt_6_preds.csv']
Loading csv: /kaggle/input/datasets/stephenweiler208/lgbm-adam/lgbm_attempt_6_preds.csv

Raw prediction shapes:
RF: (134, 425)
Friend LGBM: (134, 425)

,date_id,target_0,target_1,target_2,target_3,target_4,target_5,target_6,target_7,target_8,...,target_414,target_415,target_416,target_417,target_418,target_419,target_420,target_421,target_422,target_423
0,1827,0.000542,-0.001736,0.000947,0.002727,-0.000125,-0.002352,-0.001238,-0.002643,-0.001167,...,0.008610,0.003964,-0.003466,-0.000404,0.011858,-0.002264,0.003797,-0.001001,-0.000707,-0.005888
1,1828,0.000392,-0.001721,0.001131,0.002645,0.000144,-0.002539,-0.002039,-0.002455,-0.000446,...,0.002971,0.006599,-0.002097,-0.000241,0.012500,0.000133,-0.003624,0.003511,0.000261,-0.002492
2,1829,0.000408,-0.001545,0.000929,0.002524,0.000427,-0.001225,-0.001715,-0.002260,-0.001136,...,0.008226,0.003662,-0.003272,-0.000022,0.007452,-0.003023,0.004235,-0.001315,-0.000323,-0.003021
3,1830,0.000514,-0.000945,0.000627,0.001903,-0.000410,-0.000682,-0.001238,-0.002314,-0.000803,...,0.009518,0.003595,-0.003057,-0.000272,0.004149,-0.003867,0.006917,-0.002192,-0.000700,-0.003821
4,1831,0.000104,-0.000589,-0.000636,0.000762,0.000642,0.000032,-0.001352,-0.000642,-0.001318,...,0.008628,0.002299,-0.003054,-0.000872,0.003570,-0.004610,0.006826,-0.002171,0.000172,-0.002635

,target_0,target_1,target_2,target_3,target_4,target_5,target_6,target_7,target_8,target_9,...,target_415,target_416,target_417,target_418,target_419,target_420,target_421,target_422,target_423,date_id
0,0.379757,-0.253012,0.046811,0.006876,0.026638,0.019046,-0.257864,-0.204564,-0.035790,0.078567,...,0.464076,-1.723873,1.051687,2.173097,1.582261,0.156068,-0.537551,-0.458391,1.560904,1827
1,-0.027414,-0.066457,0.123311,0.098150,-0.172800,0.213187,0.053324,-0.038704,-0.031049,0.214653,...,0.771118,-0.249862,0.866575,0.931262,2.173303,1.189797,1.159896,0.477263,-3.825306,1828
2,0.177088,-0.090531,0.092564,0.062670,0.149296,-0.016066,-0.037252,-0.094133,0.094453,0.173660,...,0.997747,-0.581766,0.197647,1.201510,1.610565,0.881193,1.501372,0.137999,-4.165816,1829
3,0.642734,-0.068774,0.158775,0.114431,-0.049261,-0.155497,0.254004,-0.018825,0.124117,0.156651,...,0.458848,-0.518872,0.399647,-0.706438,1.607357,1.071170,1.036806,0.543802,-3.883422,1830
4,0.219913,-0.069919,0.093091,0.047233,0.072095,-0.112527,0.126800,-0.045324,0.169112,0.184145,...,0.862428,0.097322,0.498023,-0.745395,1.769844,0.703760,0.030788,-0.177073,-3.651847,1831

Aligned shapes:
RF: (134, 425)
Friend LGBM: (134, 425)
Solution: (134, 425)

Date ranges:
RF: 1827 to 1960
Friend LGBM: 1827 to 1960
Solution: 1827 to 1960

Daily rank correlation summary:

count    134.000000
mean       0.029027
std        0.182692
min       -0.414482
25%       -0.088253
50%        0.029744
75%        0.158131
max        0.560958
dtype: float64

Mean daily rank correlation: 0.029027481611147644
Std daily rank correlation: 0.18200951471613655

Your Random Forest score: 0.15948331962985082

Daily rank correlation summary:

count    134.000000
mean       0.035028
std        0.159951
min       -0.381461
25%       -0.066395
50%        0.043824
75%        0.134581
max        0.504698
dtype: float64

Mean daily rank correlation: 0.03502815848808383
Std daily rank correlation: 0.15935278969500608

Friend LightGBM score: 0.21981515701812385

Individual scores:
RF: 0.15948331962985082
Friend LGBM: 0.21981515701812385

Daily rank correlation summary:

count    134.000000
mean       0.030200
std        0.183104
min       -0.425137
25%       -0.089439
50%        0.027466
75%        0.148148
max        0.564353
dtype: float64

Mean daily rank correlation: 0.030199848888592017
Std daily rank correlation: 0.18241951034877518

friendlgbm_0.05_rf_0.95 score: 0.1655516388069002

Daily rank correlation summary:

count    134.000000
mean       0.031644
std        0.183262
min       -0.435218
25%       -0.088816
50%        0.029326
75%        0.145594
max        0.564296
dtype: float64

Mean daily rank correlation: 0.03164402852700668
Std daily rank correlation: 0.18257714535151023

friendlgbm_0.10_rf_0.90 score: 0.17331867286063318

Daily rank correlation summary:

count    134.000000
mean       0.034392
std        0.182300
min       -0.454328
25%       -0.086371
50%        0.031077
75%        0.148008
max        0.567305
dtype: float64

Mean daily rank correlation: 0.034392232757921755
Std daily rank correlation: 0.18161883849587365

friendlgbm_0.20_rf_0.80 score: 0.18936489762158204

Daily rank correlation summary:

count    134.000000
mean       0.037061
std        0.180057
min       -0.471914
25%       -0.079156
50%        0.046159
75%        0.165575
max        0.557678
dtype: float64

Mean daily rank correlation: 0.03706077663614535
Std daily rank correlation: 0.17938420947989375

friendlgbm_0.30_rf_0.70 score: 0.20659999418900524

Daily rank correlation summary:

count    134.000000
mean       0.039932
std        0.177206
min       -0.484637
25%       -0.088832
50%        0.040363
75%        0.168319
max        0.541212
dtype: float64

Mean daily rank correlation: 0.039932347697990256
Std daily rank correlation: 0.1765436578921216

friendlgbm_0.40_rf_0.60 score: 0.22618964722250876

Daily rank correlation summary:

count    134.000000
mean       0.041372
std        0.173718
min       -0.487627
25%       -0.085587
50%        0.040571
75%        0.153606
max        0.505066
dtype: float64

Mean daily rank correlation: 0.04137191881168144
Std daily rank correlation: 0.17306865230966118

friendlgbm_0.50_rf_0.50 score: 0.23904917649475416

Daily rank correlation summary:

count    134.000000
mean       0.041617
std        0.170688
min       -0.472970
25%       -0.081182
50%        0.046568
75%        0.135268
max        0.487014
dtype: float64

Mean daily rank correlation: 0.04161704945086986
Std daily rank correlation: 0.17005005857643724

friendlgbm_0.60_rf_0.40 score: 0.24473410829295927

Daily rank correlation summary:

count    134.000000
mean       0.040708
std        0.167927
min       -0.447286
25%       -0.081455
50%        0.049498
75%        0.143479
max        0.504763
dtype: float64

Mean daily rank correlation: 0.04070797120630938
Std daily rank correlation: 0.16729965758664325

friendlgbm_0.70_rf_0.30 score: 0.24332369709260776

Daily rank correlation summary:

count    134.000000
mean       0.039201
std        0.165233
min       -0.421082
25%       -0.061530
50%        0.042543
75%        0.142502
max        0.511591
dtype: float64

Mean daily rank correlation: 0.039200638203313806
Std daily rank correlation: 0.16461570658296348

friendlgbm_0.80_rf_0.20 score: 0.2381342522960126

Daily rank correlation summary:

count    134.000000
mean       0.037258
std        0.162547
min       -0.391666
25%       -0.055855
50%        0.037905
75%        0.138769
max        0.510492
dtype: float64

Mean daily rank correlation: 0.03725794686100397
Std daily rank correlation: 0.16193885447955408

friendlgbm_0.90_rf_0.10 score: 0.2300741658371311

Daily rank correlation summary:

count    134.000000
mean       0.036244
std        0.161120
min       -0.383175
25%       -0.062553
50%        0.044059
75%        0.137302
max        0.508823
dtype: float64

Mean daily rank correlation: 0.03624425305716044
Std daily rank correlation: 0.1605180503653022

friendlgbm_0.95_rf_0.05 score: 0.2257954976071342

RF + Friend LGBM blend results:

friendlgbm_0.60_rf_0.40    0.244734
friendlgbm_0.70_rf_0.30    0.243324
friendlgbm_0.50_rf_0.50    0.239049
friendlgbm_0.80_rf_0.20    0.238134
friendlgbm_0.90_rf_0.10    0.230074
friendlgbm_0.40_rf_0.60    0.226190
friendlgbm_0.95_rf_0.05    0.225795
friendlgbm_0.30_rf_0.70    0.206600
friendlgbm_0.20_rf_0.80    0.189365
friendlgbm_0.10_rf_0.90    0.173319
friendlgbm_0.05_rf_0.95    0.165552
dtype: float64

Best blend: friendlgbm_0.60_rf_0.40
Best blend score: 0.24473410829295927

Saved:
/kaggle/working/submission_rf_friend_lgbm_blend.parquet
/kaggle/working/submission.parquet